// Code generated by ent, DO NOT EDIT.

package quotaviewerdevicesession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldDeviceID, v))
}

// FamilyID applies equality check predicate on the "family_id" field. It's identical to FamilyIDEQ.
func FamilyID(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldFamilyID, v))
}

// RefreshTokenHash applies equality check predicate on the "refresh_token_hash" field. It's identical to RefreshTokenHashEQ.
func RefreshTokenHash(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldRefreshTokenHash, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldStatus, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ConsumedAt applies equality check predicate on the "consumed_at" field. It's identical to ConsumedAtEQ.
func ConsumedAt(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldConsumedAt, v))
}

// RotationID applies equality check predicate on the "rotation_id" field. It's identical to RotationIDEQ.
func RotationID(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldRotationID, v))
}

// ReplacementTokenHash applies equality check predicate on the "replacement_token_hash" field. It's identical to ReplacementTokenHashEQ.
func ReplacementTokenHash(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldReplacementTokenHash, v))
}

// RecoveryExpiresAt applies equality check predicate on the "recovery_expires_at" field. It's identical to RecoveryExpiresAtEQ.
func RecoveryExpiresAt(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldRecoveryExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...int64) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldDeviceID, vs...))
}

// FamilyIDEQ applies the EQ predicate on the "family_id" field.
func FamilyIDEQ(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldFamilyID, v))
}

// FamilyIDNEQ applies the NEQ predicate on the "family_id" field.
func FamilyIDNEQ(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldFamilyID, v))
}

// FamilyIDIn applies the In predicate on the "family_id" field.
func FamilyIDIn(vs ...string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldFamilyID, vs...))
}

// FamilyIDNotIn applies the NotIn predicate on the "family_id" field.
func FamilyIDNotIn(vs ...string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldFamilyID, vs...))
}

// FamilyIDGT applies the GT predicate on the "family_id" field.
func FamilyIDGT(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldFamilyID, v))
}

// FamilyIDGTE applies the GTE predicate on the "family_id" field.
func FamilyIDGTE(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldFamilyID, v))
}

// FamilyIDLT applies the LT predicate on the "family_id" field.
func FamilyIDLT(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldFamilyID, v))
}

// FamilyIDLTE applies the LTE predicate on the "family_id" field.
func FamilyIDLTE(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldFamilyID, v))
}

// FamilyIDContains applies the Contains predicate on the "family_id" field.
func FamilyIDContains(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldContains(FieldFamilyID, v))
}

// FamilyIDHasPrefix applies the HasPrefix predicate on the "family_id" field.
func FamilyIDHasPrefix(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldHasPrefix(FieldFamilyID, v))
}

// FamilyIDHasSuffix applies the HasSuffix predicate on the "family_id" field.
func FamilyIDHasSuffix(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldHasSuffix(FieldFamilyID, v))
}

// FamilyIDEqualFold applies the EqualFold predicate on the "family_id" field.
func FamilyIDEqualFold(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEqualFold(FieldFamilyID, v))
}

// FamilyIDContainsFold applies the ContainsFold predicate on the "family_id" field.
func FamilyIDContainsFold(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldContainsFold(FieldFamilyID, v))
}

// RefreshTokenHashEQ applies the EQ predicate on the "refresh_token_hash" field.
func RefreshTokenHashEQ(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldRefreshTokenHash, v))
}

// RefreshTokenHashNEQ applies the NEQ predicate on the "refresh_token_hash" field.
func RefreshTokenHashNEQ(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldRefreshTokenHash, v))
}

// RefreshTokenHashIn applies the In predicate on the "refresh_token_hash" field.
func RefreshTokenHashIn(vs ...string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldRefreshTokenHash, vs...))
}

// RefreshTokenHashNotIn applies the NotIn predicate on the "refresh_token_hash" field.
func RefreshTokenHashNotIn(vs ...string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldRefreshTokenHash, vs...))
}

// RefreshTokenHashGT applies the GT predicate on the "refresh_token_hash" field.
func RefreshTokenHashGT(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldRefreshTokenHash, v))
}

// RefreshTokenHashGTE applies the GTE predicate on the "refresh_token_hash" field.
func RefreshTokenHashGTE(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldRefreshTokenHash, v))
}

// RefreshTokenHashLT applies the LT predicate on the "refresh_token_hash" field.
func RefreshTokenHashLT(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldRefreshTokenHash, v))
}

// RefreshTokenHashLTE applies the LTE predicate on the "refresh_token_hash" field.
func RefreshTokenHashLTE(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldRefreshTokenHash, v))
}

// RefreshTokenHashContains applies the Contains predicate on the "refresh_token_hash" field.
func RefreshTokenHashContains(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldContains(FieldRefreshTokenHash, v))
}

// RefreshTokenHashHasPrefix applies the HasPrefix predicate on the "refresh_token_hash" field.
func RefreshTokenHashHasPrefix(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldHasPrefix(FieldRefreshTokenHash, v))
}

// RefreshTokenHashHasSuffix applies the HasSuffix predicate on the "refresh_token_hash" field.
func RefreshTokenHashHasSuffix(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldHasSuffix(FieldRefreshTokenHash, v))
}

// RefreshTokenHashEqualFold applies the EqualFold predicate on the "refresh_token_hash" field.
func RefreshTokenHashEqualFold(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEqualFold(FieldRefreshTokenHash, v))
}

// RefreshTokenHashContainsFold applies the ContainsFold predicate on the "refresh_token_hash" field.
func RefreshTokenHashContainsFold(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldContainsFold(FieldRefreshTokenHash, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldContainsFold(FieldStatus, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldExpiresAt, v))
}

// ConsumedAtEQ applies the EQ predicate on the "consumed_at" field.
func ConsumedAtEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldConsumedAt, v))
}

// ConsumedAtNEQ applies the NEQ predicate on the "consumed_at" field.
func ConsumedAtNEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldConsumedAt, v))
}

// ConsumedAtIn applies the In predicate on the "consumed_at" field.
func ConsumedAtIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldConsumedAt, vs...))
}

// ConsumedAtNotIn applies the NotIn predicate on the "consumed_at" field.
func ConsumedAtNotIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldConsumedAt, vs...))
}

// ConsumedAtGT applies the GT predicate on the "consumed_at" field.
func ConsumedAtGT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldConsumedAt, v))
}

// ConsumedAtGTE applies the GTE predicate on the "consumed_at" field.
func ConsumedAtGTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldConsumedAt, v))
}

// ConsumedAtLT applies the LT predicate on the "consumed_at" field.
func ConsumedAtLT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldConsumedAt, v))
}

// ConsumedAtLTE applies the LTE predicate on the "consumed_at" field.
func ConsumedAtLTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldConsumedAt, v))
}

// ConsumedAtIsNil applies the IsNil predicate on the "consumed_at" field.
func ConsumedAtIsNil() predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIsNull(FieldConsumedAt))
}

// ConsumedAtNotNil applies the NotNil predicate on the "consumed_at" field.
func ConsumedAtNotNil() predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotNull(FieldConsumedAt))
}

// RotationIDEQ applies the EQ predicate on the "rotation_id" field.
func RotationIDEQ(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldRotationID, v))
}

// RotationIDNEQ applies the NEQ predicate on the "rotation_id" field.
func RotationIDNEQ(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldRotationID, v))
}

// RotationIDIn applies the In predicate on the "rotation_id" field.
func RotationIDIn(vs ...string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldRotationID, vs...))
}

// RotationIDNotIn applies the NotIn predicate on the "rotation_id" field.
func RotationIDNotIn(vs ...string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldRotationID, vs...))
}

// RotationIDGT applies the GT predicate on the "rotation_id" field.
func RotationIDGT(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldRotationID, v))
}

// RotationIDGTE applies the GTE predicate on the "rotation_id" field.
func RotationIDGTE(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldRotationID, v))
}

// RotationIDLT applies the LT predicate on the "rotation_id" field.
func RotationIDLT(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldRotationID, v))
}

// RotationIDLTE applies the LTE predicate on the "rotation_id" field.
func RotationIDLTE(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldRotationID, v))
}

// RotationIDContains applies the Contains predicate on the "rotation_id" field.
func RotationIDContains(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldContains(FieldRotationID, v))
}

// RotationIDHasPrefix applies the HasPrefix predicate on the "rotation_id" field.
func RotationIDHasPrefix(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldHasPrefix(FieldRotationID, v))
}

// RotationIDHasSuffix applies the HasSuffix predicate on the "rotation_id" field.
func RotationIDHasSuffix(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldHasSuffix(FieldRotationID, v))
}

// RotationIDIsNil applies the IsNil predicate on the "rotation_id" field.
func RotationIDIsNil() predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIsNull(FieldRotationID))
}

// RotationIDNotNil applies the NotNil predicate on the "rotation_id" field.
func RotationIDNotNil() predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotNull(FieldRotationID))
}

// RotationIDEqualFold applies the EqualFold predicate on the "rotation_id" field.
func RotationIDEqualFold(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEqualFold(FieldRotationID, v))
}

// RotationIDContainsFold applies the ContainsFold predicate on the "rotation_id" field.
func RotationIDContainsFold(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldContainsFold(FieldRotationID, v))
}

// ReplacementTokenHashEQ applies the EQ predicate on the "replacement_token_hash" field.
func ReplacementTokenHashEQ(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldReplacementTokenHash, v))
}

// ReplacementTokenHashNEQ applies the NEQ predicate on the "replacement_token_hash" field.
func ReplacementTokenHashNEQ(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldReplacementTokenHash, v))
}

// ReplacementTokenHashIn applies the In predicate on the "replacement_token_hash" field.
func ReplacementTokenHashIn(vs ...string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldReplacementTokenHash, vs...))
}

// ReplacementTokenHashNotIn applies the NotIn predicate on the "replacement_token_hash" field.
func ReplacementTokenHashNotIn(vs ...string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldReplacementTokenHash, vs...))
}

// ReplacementTokenHashGT applies the GT predicate on the "replacement_token_hash" field.
func ReplacementTokenHashGT(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldReplacementTokenHash, v))
}

// ReplacementTokenHashGTE applies the GTE predicate on the "replacement_token_hash" field.
func ReplacementTokenHashGTE(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldReplacementTokenHash, v))
}

// ReplacementTokenHashLT applies the LT predicate on the "replacement_token_hash" field.
func ReplacementTokenHashLT(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldReplacementTokenHash, v))
}

// ReplacementTokenHashLTE applies the LTE predicate on the "replacement_token_hash" field.
func ReplacementTokenHashLTE(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldReplacementTokenHash, v))
}

// ReplacementTokenHashContains applies the Contains predicate on the "replacement_token_hash" field.
func ReplacementTokenHashContains(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldContains(FieldReplacementTokenHash, v))
}

// ReplacementTokenHashHasPrefix applies the HasPrefix predicate on the "replacement_token_hash" field.
func ReplacementTokenHashHasPrefix(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldHasPrefix(FieldReplacementTokenHash, v))
}

// ReplacementTokenHashHasSuffix applies the HasSuffix predicate on the "replacement_token_hash" field.
func ReplacementTokenHashHasSuffix(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldHasSuffix(FieldReplacementTokenHash, v))
}

// ReplacementTokenHashIsNil applies the IsNil predicate on the "replacement_token_hash" field.
func ReplacementTokenHashIsNil() predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIsNull(FieldReplacementTokenHash))
}

// ReplacementTokenHashNotNil applies the NotNil predicate on the "replacement_token_hash" field.
func ReplacementTokenHashNotNil() predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotNull(FieldReplacementTokenHash))
}

// ReplacementTokenHashEqualFold applies the EqualFold predicate on the "replacement_token_hash" field.
func ReplacementTokenHashEqualFold(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEqualFold(FieldReplacementTokenHash, v))
}

// ReplacementTokenHashContainsFold applies the ContainsFold predicate on the "replacement_token_hash" field.
func ReplacementTokenHashContainsFold(v string) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldContainsFold(FieldReplacementTokenHash, v))
}

// RecoveryExpiresAtEQ applies the EQ predicate on the "recovery_expires_at" field.
func RecoveryExpiresAtEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldRecoveryExpiresAt, v))
}

// RecoveryExpiresAtNEQ applies the NEQ predicate on the "recovery_expires_at" field.
func RecoveryExpiresAtNEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldRecoveryExpiresAt, v))
}

// RecoveryExpiresAtIn applies the In predicate on the "recovery_expires_at" field.
func RecoveryExpiresAtIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldRecoveryExpiresAt, vs...))
}

// RecoveryExpiresAtNotIn applies the NotIn predicate on the "recovery_expires_at" field.
func RecoveryExpiresAtNotIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldRecoveryExpiresAt, vs...))
}

// RecoveryExpiresAtGT applies the GT predicate on the "recovery_expires_at" field.
func RecoveryExpiresAtGT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldRecoveryExpiresAt, v))
}

// RecoveryExpiresAtGTE applies the GTE predicate on the "recovery_expires_at" field.
func RecoveryExpiresAtGTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldRecoveryExpiresAt, v))
}

// RecoveryExpiresAtLT applies the LT predicate on the "recovery_expires_at" field.
func RecoveryExpiresAtLT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldRecoveryExpiresAt, v))
}

// RecoveryExpiresAtLTE applies the LTE predicate on the "recovery_expires_at" field.
func RecoveryExpiresAtLTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldRecoveryExpiresAt, v))
}

// RecoveryExpiresAtIsNil applies the IsNil predicate on the "recovery_expires_at" field.
func RecoveryExpiresAtIsNil() predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIsNull(FieldRecoveryExpiresAt))
}

// RecoveryExpiresAtNotNil applies the NotNil predicate on the "recovery_expires_at" field.
func RecoveryExpiresAtNotNil() predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotNull(FieldRecoveryExpiresAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.FieldNotNull(FieldRevokedAt))
}

// HasDevice applies the HasEdge predicate on the "device" edge.
func HasDevice() predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceWith applies the HasEdge predicate on the "device" edge with a given conditions (other predicates).
func HasDeviceWith(preds ...predicate.QuotaViewerDevice) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(func(s *sql.Selector) {
		step := newDeviceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QuotaViewerDeviceSession) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QuotaViewerDeviceSession) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QuotaViewerDeviceSession) predicate.QuotaViewerDeviceSession {
	return predicate.QuotaViewerDeviceSession(sql.NotPredicates(p))
}
