// Code generated by ent, DO NOT EDIT.

package desktopdevice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the desktopdevice type in the database.
	Label = "desktop_device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldInstallationIDHash holds the string denoting the installation_id_hash field in the database.
	FieldInstallationIDHash = "installation_id_hash"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldArchitecture holds the string denoting the architecture field in the database.
	FieldArchitecture = "architecture"
	// FieldOsVersion holds the string denoting the os_version field in the database.
	FieldOsVersion = "os_version"
	// FieldAppVersion holds the string denoting the app_version field in the database.
	FieldAppVersion = "app_version"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTokenVersion holds the string denoting the token_version field in the database.
	FieldTokenVersion = "token_version"
	// FieldReleaseChannel holds the string denoting the release_channel field in the database.
	FieldReleaseChannel = "release_channel"
	// FieldPairingExpiresAt holds the string denoting the pairing_expires_at field in the database.
	FieldPairingExpiresAt = "pairing_expires_at"
	// FieldApprovedAt holds the string denoting the approved_at field in the database.
	FieldApprovedAt = "approved_at"
	// FieldActivatedAt holds the string denoting the activated_at field in the database.
	FieldActivatedAt = "activated_at"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgeManagedKeys holds the string denoting the managed_keys edge name in mutations.
	EdgeManagedKeys = "managed_keys"
	// EdgeDiagnostics holds the string denoting the diagnostics edge name in mutations.
	EdgeDiagnostics = "diagnostics"
	// Table holds the table name of the desktopdevice in the database.
	Table = "desktop_devices"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "desktop_devices"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "desktop_device_sessions"
	// SessionsInverseTable is the table name for the DesktopDeviceSession entity.
	// It exists in this package in order to avoid circular dependency with the "desktopdevicesession" package.
	SessionsInverseTable = "desktop_device_sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "device_id"
	// ManagedKeysTable is the table that holds the managed_keys relation/edge.
	ManagedKeysTable = "api_keys"
	// ManagedKeysInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	ManagedKeysInverseTable = "api_keys"
	// ManagedKeysColumn is the table column denoting the managed_keys relation/edge.
	ManagedKeysColumn = "managed_device_id"
	// DiagnosticsTable is the table that holds the diagnostics relation/edge.
	DiagnosticsTable = "desktop_diagnostics"
	// DiagnosticsInverseTable is the table name for the DesktopDiagnostic entity.
	// It exists in this package in order to avoid circular dependency with the "desktopdiagnostic" package.
	DiagnosticsInverseTable = "desktop_diagnostics"
	// DiagnosticsColumn is the table column denoting the diagnostics relation/edge.
	DiagnosticsColumn = "device_id"
)

// Columns holds all SQL columns for desktopdevice fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldPublicID,
	FieldInstallationIDHash,
	FieldName,
	FieldPlatform,
	FieldArchitecture,
	FieldOsVersion,
	FieldAppVersion,
	FieldStatus,
	FieldTokenVersion,
	FieldReleaseChannel,
	FieldPairingExpiresAt,
	FieldApprovedAt,
	FieldActivatedAt,
	FieldLastSeenAt,
	FieldRevokedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// InstallationIDHashValidator is a validator for the "installation_id_hash" field. It is called by the builders before save.
	InstallationIDHashValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// ArchitectureValidator is a validator for the "architecture" field. It is called by the builders before save.
	ArchitectureValidator func(string) error
	// DefaultOsVersion holds the default value on creation for the "os_version" field.
	DefaultOsVersion string
	// OsVersionValidator is a validator for the "os_version" field. It is called by the builders before save.
	OsVersionValidator func(string) error
	// DefaultAppVersion holds the default value on creation for the "app_version" field.
	DefaultAppVersion string
	// AppVersionValidator is a validator for the "app_version" field. It is called by the builders before save.
	AppVersionValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultTokenVersion holds the default value on creation for the "token_version" field.
	DefaultTokenVersion int64
	// DefaultReleaseChannel holds the default value on creation for the "release_channel" field.
	DefaultReleaseChannel string
	// ReleaseChannelValidator is a validator for the "release_channel" field. It is called by the builders before save.
	ReleaseChannelValidator func(string) error
)

// OrderOption defines the ordering options for the DesktopDevice queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByInstallationIDHash orders the results by the installation_id_hash field.
func ByInstallationIDHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInstallationIDHash, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByArchitecture orders the results by the architecture field.
func ByArchitecture(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArchitecture, opts...).ToFunc()
}

// ByOsVersion orders the results by the os_version field.
func ByOsVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOsVersion, opts...).ToFunc()
}

// ByAppVersion orders the results by the app_version field.
func ByAppVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppVersion, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTokenVersion orders the results by the token_version field.
func ByTokenVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenVersion, opts...).ToFunc()
}

// ByReleaseChannel orders the results by the release_channel field.
func ByReleaseChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReleaseChannel, opts...).ToFunc()
}

// ByPairingExpiresAt orders the results by the pairing_expires_at field.
func ByPairingExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPairingExpiresAt, opts...).ToFunc()
}

// ByApprovedAt orders the results by the approved_at field.
func ByApprovedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApprovedAt, opts...).ToFunc()
}

// ByActivatedAt orders the results by the activated_at field.
func ByActivatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActivatedAt, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByManagedKeysCount orders the results by managed_keys count.
func ByManagedKeysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newManagedKeysStep(), opts...)
	}
}

// ByManagedKeys orders the results by managed_keys terms.
func ByManagedKeys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagedKeysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDiagnosticsCount orders the results by diagnostics count.
func ByDiagnosticsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDiagnosticsStep(), opts...)
	}
}

// ByDiagnostics orders the results by diagnostics terms.
func ByDiagnostics(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDiagnosticsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
func newManagedKeysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagedKeysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ManagedKeysTable, ManagedKeysColumn),
	)
}
func newDiagnosticsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DiagnosticsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DiagnosticsTable, DiagnosticsColumn),
	)
}
