// Code generated by ent, DO NOT EDIT.

package desktopdevice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldUserID, v))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldPublicID, v))
}

// InstallationIDHash applies equality check predicate on the "installation_id_hash" field. It's identical to InstallationIDHashEQ.
func InstallationIDHash(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldInstallationIDHash, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldPlatform, v))
}

// Architecture applies equality check predicate on the "architecture" field. It's identical to ArchitectureEQ.
func Architecture(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldArchitecture, v))
}

// OsVersion applies equality check predicate on the "os_version" field. It's identical to OsVersionEQ.
func OsVersion(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldOsVersion, v))
}

// AppVersion applies equality check predicate on the "app_version" field. It's identical to AppVersionEQ.
func AppVersion(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldAppVersion, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldStatus, v))
}

// TokenVersion applies equality check predicate on the "token_version" field. It's identical to TokenVersionEQ.
func TokenVersion(v int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldTokenVersion, v))
}

// ReleaseChannel applies equality check predicate on the "release_channel" field. It's identical to ReleaseChannelEQ.
func ReleaseChannel(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldReleaseChannel, v))
}

// PairingExpiresAt applies equality check predicate on the "pairing_expires_at" field. It's identical to PairingExpiresAtEQ.
func PairingExpiresAt(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldPairingExpiresAt, v))
}

// ApprovedAt applies equality check predicate on the "approved_at" field. It's identical to ApprovedAtEQ.
func ApprovedAt(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldApprovedAt, v))
}

// ActivatedAt applies equality check predicate on the "activated_at" field. It's identical to ActivatedAtEQ.
func ActivatedAt(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldActivatedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldLastSeenAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldUserID, vs...))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldPublicID, v))
}

// PublicIDContains applies the Contains predicate on the "public_id" field.
func PublicIDContains(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContains(FieldPublicID, v))
}

// PublicIDHasPrefix applies the HasPrefix predicate on the "public_id" field.
func PublicIDHasPrefix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasPrefix(FieldPublicID, v))
}

// PublicIDHasSuffix applies the HasSuffix predicate on the "public_id" field.
func PublicIDHasSuffix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasSuffix(FieldPublicID, v))
}

// PublicIDEqualFold applies the EqualFold predicate on the "public_id" field.
func PublicIDEqualFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEqualFold(FieldPublicID, v))
}

// PublicIDContainsFold applies the ContainsFold predicate on the "public_id" field.
func PublicIDContainsFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContainsFold(FieldPublicID, v))
}

// InstallationIDHashEQ applies the EQ predicate on the "installation_id_hash" field.
func InstallationIDHashEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldInstallationIDHash, v))
}

// InstallationIDHashNEQ applies the NEQ predicate on the "installation_id_hash" field.
func InstallationIDHashNEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldInstallationIDHash, v))
}

// InstallationIDHashIn applies the In predicate on the "installation_id_hash" field.
func InstallationIDHashIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldInstallationIDHash, vs...))
}

// InstallationIDHashNotIn applies the NotIn predicate on the "installation_id_hash" field.
func InstallationIDHashNotIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldInstallationIDHash, vs...))
}

// InstallationIDHashGT applies the GT predicate on the "installation_id_hash" field.
func InstallationIDHashGT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldInstallationIDHash, v))
}

// InstallationIDHashGTE applies the GTE predicate on the "installation_id_hash" field.
func InstallationIDHashGTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldInstallationIDHash, v))
}

// InstallationIDHashLT applies the LT predicate on the "installation_id_hash" field.
func InstallationIDHashLT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldInstallationIDHash, v))
}

// InstallationIDHashLTE applies the LTE predicate on the "installation_id_hash" field.
func InstallationIDHashLTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldInstallationIDHash, v))
}

// InstallationIDHashContains applies the Contains predicate on the "installation_id_hash" field.
func InstallationIDHashContains(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContains(FieldInstallationIDHash, v))
}

// InstallationIDHashHasPrefix applies the HasPrefix predicate on the "installation_id_hash" field.
func InstallationIDHashHasPrefix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasPrefix(FieldInstallationIDHash, v))
}

// InstallationIDHashHasSuffix applies the HasSuffix predicate on the "installation_id_hash" field.
func InstallationIDHashHasSuffix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasSuffix(FieldInstallationIDHash, v))
}

// InstallationIDHashEqualFold applies the EqualFold predicate on the "installation_id_hash" field.
func InstallationIDHashEqualFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEqualFold(FieldInstallationIDHash, v))
}

// InstallationIDHashContainsFold applies the ContainsFold predicate on the "installation_id_hash" field.
func InstallationIDHashContainsFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContainsFold(FieldInstallationIDHash, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContainsFold(FieldName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContainsFold(FieldPlatform, v))
}

// ArchitectureEQ applies the EQ predicate on the "architecture" field.
func ArchitectureEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldArchitecture, v))
}

// ArchitectureNEQ applies the NEQ predicate on the "architecture" field.
func ArchitectureNEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldArchitecture, v))
}

// ArchitectureIn applies the In predicate on the "architecture" field.
func ArchitectureIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldArchitecture, vs...))
}

// ArchitectureNotIn applies the NotIn predicate on the "architecture" field.
func ArchitectureNotIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldArchitecture, vs...))
}

// ArchitectureGT applies the GT predicate on the "architecture" field.
func ArchitectureGT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldArchitecture, v))
}

// ArchitectureGTE applies the GTE predicate on the "architecture" field.
func ArchitectureGTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldArchitecture, v))
}

// ArchitectureLT applies the LT predicate on the "architecture" field.
func ArchitectureLT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldArchitecture, v))
}

// ArchitectureLTE applies the LTE predicate on the "architecture" field.
func ArchitectureLTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldArchitecture, v))
}

// ArchitectureContains applies the Contains predicate on the "architecture" field.
func ArchitectureContains(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContains(FieldArchitecture, v))
}

// ArchitectureHasPrefix applies the HasPrefix predicate on the "architecture" field.
func ArchitectureHasPrefix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasPrefix(FieldArchitecture, v))
}

// ArchitectureHasSuffix applies the HasSuffix predicate on the "architecture" field.
func ArchitectureHasSuffix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasSuffix(FieldArchitecture, v))
}

// ArchitectureEqualFold applies the EqualFold predicate on the "architecture" field.
func ArchitectureEqualFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEqualFold(FieldArchitecture, v))
}

// ArchitectureContainsFold applies the ContainsFold predicate on the "architecture" field.
func ArchitectureContainsFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContainsFold(FieldArchitecture, v))
}

// OsVersionEQ applies the EQ predicate on the "os_version" field.
func OsVersionEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldOsVersion, v))
}

// OsVersionNEQ applies the NEQ predicate on the "os_version" field.
func OsVersionNEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldOsVersion, v))
}

// OsVersionIn applies the In predicate on the "os_version" field.
func OsVersionIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldOsVersion, vs...))
}

// OsVersionNotIn applies the NotIn predicate on the "os_version" field.
func OsVersionNotIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldOsVersion, vs...))
}

// OsVersionGT applies the GT predicate on the "os_version" field.
func OsVersionGT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldOsVersion, v))
}

// OsVersionGTE applies the GTE predicate on the "os_version" field.
func OsVersionGTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldOsVersion, v))
}

// OsVersionLT applies the LT predicate on the "os_version" field.
func OsVersionLT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldOsVersion, v))
}

// OsVersionLTE applies the LTE predicate on the "os_version" field.
func OsVersionLTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldOsVersion, v))
}

// OsVersionContains applies the Contains predicate on the "os_version" field.
func OsVersionContains(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContains(FieldOsVersion, v))
}

// OsVersionHasPrefix applies the HasPrefix predicate on the "os_version" field.
func OsVersionHasPrefix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasPrefix(FieldOsVersion, v))
}

// OsVersionHasSuffix applies the HasSuffix predicate on the "os_version" field.
func OsVersionHasSuffix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasSuffix(FieldOsVersion, v))
}

// OsVersionEqualFold applies the EqualFold predicate on the "os_version" field.
func OsVersionEqualFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEqualFold(FieldOsVersion, v))
}

// OsVersionContainsFold applies the ContainsFold predicate on the "os_version" field.
func OsVersionContainsFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContainsFold(FieldOsVersion, v))
}

// AppVersionEQ applies the EQ predicate on the "app_version" field.
func AppVersionEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldAppVersion, v))
}

// AppVersionNEQ applies the NEQ predicate on the "app_version" field.
func AppVersionNEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldAppVersion, v))
}

// AppVersionIn applies the In predicate on the "app_version" field.
func AppVersionIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldAppVersion, vs...))
}

// AppVersionNotIn applies the NotIn predicate on the "app_version" field.
func AppVersionNotIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldAppVersion, vs...))
}

// AppVersionGT applies the GT predicate on the "app_version" field.
func AppVersionGT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldAppVersion, v))
}

// AppVersionGTE applies the GTE predicate on the "app_version" field.
func AppVersionGTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldAppVersion, v))
}

// AppVersionLT applies the LT predicate on the "app_version" field.
func AppVersionLT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldAppVersion, v))
}

// AppVersionLTE applies the LTE predicate on the "app_version" field.
func AppVersionLTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldAppVersion, v))
}

// AppVersionContains applies the Contains predicate on the "app_version" field.
func AppVersionContains(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContains(FieldAppVersion, v))
}

// AppVersionHasPrefix applies the HasPrefix predicate on the "app_version" field.
func AppVersionHasPrefix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasPrefix(FieldAppVersion, v))
}

// AppVersionHasSuffix applies the HasSuffix predicate on the "app_version" field.
func AppVersionHasSuffix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasSuffix(FieldAppVersion, v))
}

// AppVersionEqualFold applies the EqualFold predicate on the "app_version" field.
func AppVersionEqualFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEqualFold(FieldAppVersion, v))
}

// AppVersionContainsFold applies the ContainsFold predicate on the "app_version" field.
func AppVersionContainsFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContainsFold(FieldAppVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContainsFold(FieldStatus, v))
}

// TokenVersionEQ applies the EQ predicate on the "token_version" field.
func TokenVersionEQ(v int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldTokenVersion, v))
}

// TokenVersionNEQ applies the NEQ predicate on the "token_version" field.
func TokenVersionNEQ(v int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldTokenVersion, v))
}

// TokenVersionIn applies the In predicate on the "token_version" field.
func TokenVersionIn(vs ...int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldTokenVersion, vs...))
}

// TokenVersionNotIn applies the NotIn predicate on the "token_version" field.
func TokenVersionNotIn(vs ...int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldTokenVersion, vs...))
}

// TokenVersionGT applies the GT predicate on the "token_version" field.
func TokenVersionGT(v int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldTokenVersion, v))
}

// TokenVersionGTE applies the GTE predicate on the "token_version" field.
func TokenVersionGTE(v int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldTokenVersion, v))
}

// TokenVersionLT applies the LT predicate on the "token_version" field.
func TokenVersionLT(v int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldTokenVersion, v))
}

// TokenVersionLTE applies the LTE predicate on the "token_version" field.
func TokenVersionLTE(v int64) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldTokenVersion, v))
}

// ReleaseChannelEQ applies the EQ predicate on the "release_channel" field.
func ReleaseChannelEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldReleaseChannel, v))
}

// ReleaseChannelNEQ applies the NEQ predicate on the "release_channel" field.
func ReleaseChannelNEQ(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldReleaseChannel, v))
}

// ReleaseChannelIn applies the In predicate on the "release_channel" field.
func ReleaseChannelIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldReleaseChannel, vs...))
}

// ReleaseChannelNotIn applies the NotIn predicate on the "release_channel" field.
func ReleaseChannelNotIn(vs ...string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldReleaseChannel, vs...))
}

// ReleaseChannelGT applies the GT predicate on the "release_channel" field.
func ReleaseChannelGT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldReleaseChannel, v))
}

// ReleaseChannelGTE applies the GTE predicate on the "release_channel" field.
func ReleaseChannelGTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldReleaseChannel, v))
}

// ReleaseChannelLT applies the LT predicate on the "release_channel" field.
func ReleaseChannelLT(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldReleaseChannel, v))
}

// ReleaseChannelLTE applies the LTE predicate on the "release_channel" field.
func ReleaseChannelLTE(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldReleaseChannel, v))
}

// ReleaseChannelContains applies the Contains predicate on the "release_channel" field.
func ReleaseChannelContains(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContains(FieldReleaseChannel, v))
}

// ReleaseChannelHasPrefix applies the HasPrefix predicate on the "release_channel" field.
func ReleaseChannelHasPrefix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasPrefix(FieldReleaseChannel, v))
}

// ReleaseChannelHasSuffix applies the HasSuffix predicate on the "release_channel" field.
func ReleaseChannelHasSuffix(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldHasSuffix(FieldReleaseChannel, v))
}

// ReleaseChannelEqualFold applies the EqualFold predicate on the "release_channel" field.
func ReleaseChannelEqualFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEqualFold(FieldReleaseChannel, v))
}

// ReleaseChannelContainsFold applies the ContainsFold predicate on the "release_channel" field.
func ReleaseChannelContainsFold(v string) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldContainsFold(FieldReleaseChannel, v))
}

// PairingExpiresAtEQ applies the EQ predicate on the "pairing_expires_at" field.
func PairingExpiresAtEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldPairingExpiresAt, v))
}

// PairingExpiresAtNEQ applies the NEQ predicate on the "pairing_expires_at" field.
func PairingExpiresAtNEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldPairingExpiresAt, v))
}

// PairingExpiresAtIn applies the In predicate on the "pairing_expires_at" field.
func PairingExpiresAtIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldPairingExpiresAt, vs...))
}

// PairingExpiresAtNotIn applies the NotIn predicate on the "pairing_expires_at" field.
func PairingExpiresAtNotIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldPairingExpiresAt, vs...))
}

// PairingExpiresAtGT applies the GT predicate on the "pairing_expires_at" field.
func PairingExpiresAtGT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldPairingExpiresAt, v))
}

// PairingExpiresAtGTE applies the GTE predicate on the "pairing_expires_at" field.
func PairingExpiresAtGTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldPairingExpiresAt, v))
}

// PairingExpiresAtLT applies the LT predicate on the "pairing_expires_at" field.
func PairingExpiresAtLT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldPairingExpiresAt, v))
}

// PairingExpiresAtLTE applies the LTE predicate on the "pairing_expires_at" field.
func PairingExpiresAtLTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldPairingExpiresAt, v))
}

// ApprovedAtEQ applies the EQ predicate on the "approved_at" field.
func ApprovedAtEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldApprovedAt, v))
}

// ApprovedAtNEQ applies the NEQ predicate on the "approved_at" field.
func ApprovedAtNEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldApprovedAt, v))
}

// ApprovedAtIn applies the In predicate on the "approved_at" field.
func ApprovedAtIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldApprovedAt, vs...))
}

// ApprovedAtNotIn applies the NotIn predicate on the "approved_at" field.
func ApprovedAtNotIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldApprovedAt, vs...))
}

// ApprovedAtGT applies the GT predicate on the "approved_at" field.
func ApprovedAtGT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldApprovedAt, v))
}

// ApprovedAtGTE applies the GTE predicate on the "approved_at" field.
func ApprovedAtGTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldApprovedAt, v))
}

// ApprovedAtLT applies the LT predicate on the "approved_at" field.
func ApprovedAtLT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldApprovedAt, v))
}

// ApprovedAtLTE applies the LTE predicate on the "approved_at" field.
func ApprovedAtLTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldApprovedAt, v))
}

// ApprovedAtIsNil applies the IsNil predicate on the "approved_at" field.
func ApprovedAtIsNil() predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIsNull(FieldApprovedAt))
}

// ApprovedAtNotNil applies the NotNil predicate on the "approved_at" field.
func ApprovedAtNotNil() predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotNull(FieldApprovedAt))
}

// ActivatedAtEQ applies the EQ predicate on the "activated_at" field.
func ActivatedAtEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldActivatedAt, v))
}

// ActivatedAtNEQ applies the NEQ predicate on the "activated_at" field.
func ActivatedAtNEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldActivatedAt, v))
}

// ActivatedAtIn applies the In predicate on the "activated_at" field.
func ActivatedAtIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldActivatedAt, vs...))
}

// ActivatedAtNotIn applies the NotIn predicate on the "activated_at" field.
func ActivatedAtNotIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldActivatedAt, vs...))
}

// ActivatedAtGT applies the GT predicate on the "activated_at" field.
func ActivatedAtGT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldActivatedAt, v))
}

// ActivatedAtGTE applies the GTE predicate on the "activated_at" field.
func ActivatedAtGTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldActivatedAt, v))
}

// ActivatedAtLT applies the LT predicate on the "activated_at" field.
func ActivatedAtLT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldActivatedAt, v))
}

// ActivatedAtLTE applies the LTE predicate on the "activated_at" field.
func ActivatedAtLTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldActivatedAt, v))
}

// ActivatedAtIsNil applies the IsNil predicate on the "activated_at" field.
func ActivatedAtIsNil() predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIsNull(FieldActivatedAt))
}

// ActivatedAtNotNil applies the NotNil predicate on the "activated_at" field.
func ActivatedAtNotNil() predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotNull(FieldActivatedAt))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldLastSeenAt, v))
}

// LastSeenAtIsNil applies the IsNil predicate on the "last_seen_at" field.
func LastSeenAtIsNil() predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIsNull(FieldLastSeenAt))
}

// LastSeenAtNotNil applies the NotNil predicate on the "last_seen_at" field.
func LastSeenAtNotNil() predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotNull(FieldLastSeenAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.FieldNotNull(FieldRevokedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.DesktopDevice {
	return predicate.DesktopDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.DesktopDevice {
	return predicate.DesktopDevice(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSessions applies the HasEdge predicate on the "sessions" edge.
func HasSessions() predicate.DesktopDevice {
	return predicate.DesktopDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionsWith applies the HasEdge predicate on the "sessions" edge with a given conditions (other predicates).
func HasSessionsWith(preds ...predicate.DesktopDeviceSession) predicate.DesktopDevice {
	return predicate.DesktopDevice(func(s *sql.Selector) {
		step := newSessionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasManagedKeys applies the HasEdge predicate on the "managed_keys" edge.
func HasManagedKeys() predicate.DesktopDevice {
	return predicate.DesktopDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ManagedKeysTable, ManagedKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasManagedKeysWith applies the HasEdge predicate on the "managed_keys" edge with a given conditions (other predicates).
func HasManagedKeysWith(preds ...predicate.APIKey) predicate.DesktopDevice {
	return predicate.DesktopDevice(func(s *sql.Selector) {
		step := newManagedKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDiagnostics applies the HasEdge predicate on the "diagnostics" edge.
func HasDiagnostics() predicate.DesktopDevice {
	return predicate.DesktopDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DiagnosticsTable, DiagnosticsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDiagnosticsWith applies the HasEdge predicate on the "diagnostics" edge with a given conditions (other predicates).
func HasDiagnosticsWith(preds ...predicate.DesktopDiagnostic) predicate.DesktopDevice {
	return predicate.DesktopDevice(func(s *sql.Selector) {
		step := newDiagnosticsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DesktopDevice) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DesktopDevice) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DesktopDevice) predicate.DesktopDevice {
	return predicate.DesktopDevice(sql.NotPredicates(p))
}
