-- Reviewed Simplified Chinese catalog copy for skills.sh ranks 168-334.
-- Keep upstream Skill packages and immutable marketplace slugs unchanged.
WITH localized (
    rank,
    slug,
    display_name,
    summary,
    capability,
    source,
    original_slug,
    excluded_count,
    license_unverified
) AS (
    VALUES
    (168, 'entra-agent-id', $zh239$Microsoft Entra 代理身份配置$zh239$,
        $zh239$通过 Microsoft Graph 配置 Entra 代理身份蓝图、主体和实例身份，并设置 OAuth 2.0 令牌交换。$zh239$,
        $zh239$用于通过 Microsoft Graph 预配 Microsoft Entra Agent Identity Blueprint、BlueprintPrincipal 和逐实例 Agent Identity，并配置 fmi_path、OBO、跨租户等 OAuth 2.0 令牌交换及 AgentID SDK sidecar。不适用于普通应用注册或 Foundry 代理创作。$zh239$,
        'microsoft/azure-skills', 'entra-agent-id', 0, FALSE),
    (169, 'diagnose', $zh239$系统化疑难诊断$zh239$,
        $zh239$以复现、最小化、假设、插桩、修复和回归测试的闭环诊断复杂缺陷与性能退化。$zh239$,
        $zh239$用于困难缺陷、异常、失败和性能退化的严谨诊断。先稳定复现并缩小问题，再提出可证伪假设、添加观测手段、实施最小修复，最后用回归测试证明问题已解决。$zh239$,
        'mattpocock/skills', 'diagnose', 0, FALSE),
    (170, 'full-output-enforcement', $zh239$完整输出强制器$zh239$,
        $zh239$要求模型提供完整、无删节的输出，禁止占位符，并妥善处理令牌上限下的分段续写。$zh239$,
        $zh239$用于必须穷尽输出的任务，覆盖默认的截断倾向，要求代码与内容完整生成，禁止省略号、占位实现和“其余类似”等替代文本；接近令牌上限时按清晰边界分段并可无损续写。$zh239$,
        'leonxlnx/taste-skill', 'full-output-enforcement', 0, FALSE),
    (171, 'impeccable', $zh239$Impeccable 前端体验精修$zh239$,
        $zh239$全面设计、审查和精修网站、应用与组件的视觉、交互、可访问性、性能和响应式体验。$zh239$,
        $zh239$用于设计、重设计、塑形、批评、审计、精修、澄清、简化、强化、优化、适配、动画、配色或提取前端界面。覆盖网站、落地页、仪表盘、产品界面、表单、设置、引导和空状态，以及信息架构、认知负担、可访问性、性能、响应式、主题、排版、动效、文案、错误与国际化；不用于纯后端任务。$zh239$,
        'pbakaus/impeccable', 'impeccable', 50, FALSE),
    (172, 'write-a-skill', $zh239$Agent Skill 编写指南$zh239$,
        $zh239$按正确目录结构、渐进式披露和资源打包规范创建新的 Agent Skill。$zh239$,
        $zh239$用于创建、编写或搭建新的 Agent Skill。指导定义清晰触发范围，组织 SKILL.md，采用渐进式披露控制上下文，并把脚本、参考资料和资源按需随 Skill 打包。$zh239$,
        'mattpocock/skills', 'write-a-skill', 0, TRUE),
    (173, 'ai-research-explore', $zh239$AI 研究候选探索$zh239$,
        $zh239$在研究问题、数据、基准、评估与 SOTA 已确定后，开展受治理且可审计的深度学习候选探索。$zh239$,
        $zh239$用于研究者已选定任务族、数据集、基准、评估方法并提供 SOTA 参考后的候选方案探索。以当前基线为基础形成可审计证据并输出 explore_outputs；不替代可信复现，也不用于无边界开放探索、仅运行实验或问题尚未定义的场景。$zh239$,
        'lllllllama/rigorpilot-skills', 'ai-research-explore', 0, FALSE),
    (174, 'analyze-project', $zh239$深度学习项目只读分析$zh239$,
        $zh239$只读审计深度学习仓库的结构、入口、配置、扩展点与可疑实现模式。$zh239$,
        $zh239$用于阅读和理解深度学习研究仓库，梳理模型结构、训练或推理入口、配置流、模块插入点及可疑实现模式。保持只读，不运行重型任务、不重构、不修复，也不把推测冒充验证结论。$zh239$,
        'lllllllama/rigorpilot-skills', 'analyze-project', 0, FALSE),
    (175, 'zoom-out', $zh239$拉远视角理解代码$zh239$,
        $zh239$从更广的上下文和更高层级解释陌生代码如何融入整体系统。$zh239$,
        $zh239$用于不熟悉某段代码或需要理解其系统位置时主动拉远视角，补充上游输入、下游影响、模块边界、核心抽象和设计动机，避免只在局部实现细节中打转。$zh239$,
        'mattpocock/skills', 'zoom-out', 0, FALSE),
    (176, 'ai-research-reproduction', $zh239$AI 研究可信复现$zh239$,
        $zh239$以 README 为起点，用最小可信流程复现深度学习仓库的推理、评估或训练证据。$zh239$,
        $zh239$用于端到端复现深度学习研究仓库。先阅读仓库并选择最小的文档化推理或评估目标，再协调环境、执行、训练、分析与论文差距，保守补丁并把证据写入 repro_outputs；不以未经验证的成功宣称替代真实运行。$zh239$,
        'lllllllama/rigorpilot-skills', 'ai-research-reproduction', 0, FALSE),
    (177, 'explore-code', $zh239$深度学习候选代码探索$zh239$,
        $zh239$在获授权的隔离分支或工作树中实现可回滚、可审计的深度学习候选改动。$zh239$,
        $zh239$用于研究者明确授权后的候选实现，包括移植模块、调整 backbone、加入 LoRA、adapter 或预测头。所有探索须在隔离分支或工作树中进行，记录变更与回滚路径；不用于未授权改写、正式基线修复或只需分析的任务。$zh239$,
        'lllllllama/rigorpilot-skills', 'explore-code', 0, FALSE),
    (178, 'safe-debug', $zh239$深度学习安全调试$zh239$,
        $zh239$保守诊断 traceback、CUDA OOM、检查点、形状、NaN 和训练故障，并区分调试修复与研究贡献。$zh239$,
        $zh239$用于深度学习研究中的 traceback、终端错误、CUDA OOM、检查点加载失败、张量形状不匹配、NaN 损失或训练失败。先收集证据并定位最小原因，再提出低风险修复；明确区分恢复可运行性的调试改动与可能影响研究结论的算法贡献。$zh239$,
        'lllllllama/rigorpilot-skills', 'safe-debug', 0, FALSE),
    (179, 'run-train', $zh239$深度学习训练执行$zh239$,
        $zh239$保守执行文档化训练的启动验证、短跑、完整启动或续训，并留存可审计证据。$zh239$,
        $zh239$用于运行已文档化或已选定的训练命令，支持启动检查、短时验证、完整训练启动和从检查点恢复。记录实际命令、配置、随机种子、日志、检查点、状态与指标到 train_outputs，不擅自改变研究目标或夸大未完成结果。$zh239$,
        'lllllllama/rigorpilot-skills', 'run-train', 0, FALSE),
    (180, 'explore-run', $zh239$深度学习探索实验$zh239$,
        $zh239$在明确授权和边界内运行小样本、短周期、批量扫描或快速迁移实验并审慎解读证据。$zh239$,
        $zh239$用于研究者授权的有限探索运行，例如小子集验证、短周期试错、参数批扫、空闲 GPU 搜索或快速迁移试验。保持对照公平，记录限制与失败，将产物写入 explore_outputs；不把初步信号表述为可靠结论。$zh239$,
        'lllllllama/rigorpilot-skills', 'explore-run', 0, FALSE),
    (181, 'industrial-brutalist-ui', $zh239$工业粗野主义界面设计$zh239$,
        $zh239$以瑞士印刷与军用终端美学打造刚硬、机械、数据密集的粗野主义界面。$zh239$,
        $zh239$用于需要“解密蓝图”气质的数据仪表盘、作品集或编辑型网站。采用严格网格、极端字号反差、功能性色彩、机械化信息层级和适度模拟退化效果，融合瑞士排版与军用终端风格。$zh239$,
        'leonxlnx/taste-skill', 'industrial-brutalist-ui', 0, FALSE),
    (182, 'stitch-design-taste', $zh239$Google Stitch 设计品味系统$zh239$,
        $zh239$为 Google Stitch 生成适合代理使用的 DESIGN.md，约束高级且非模板化的界面设计。$zh239$,
        $zh239$用于为 Google Stitch 建立语义化设计系统并生成代理友好的 DESIGN.md。规范严格排版、校准色彩、非对称布局、持续微动效和硬件加速性能，帮助生成统一、高级且避免通用模板感的界面。$zh239$,
        'leonxlnx/taste-skill', 'stitch-design-taste', 0, FALSE),
    (183, 'caveman-mattpocock-skills', $zh239$穴居人极简表达模式$zh239$,
        $zh239$删除铺垫、冠词和客套话，以约四分之一的篇幅保留完整技术信息。$zh239$,
        $zh239$用于用户要求 caveman mode、极简表达、减少令牌或更简短回复时。大幅压缩沟通，省略填充语、冠词、客套与重复表述，同时保留关键技术事实、约束、命令和风险。$zh239$,
        'mattpocock/skills', 'caveman', 0, FALSE),
    (184, 'systematic-debugging', $zh239$系统化调试流程$zh239$,
        $zh239$在提出修复前，以证据驱动流程调查所有缺陷、测试失败和异常行为。$zh239$,
        $zh239$用于遇到任何缺陷、测试失败或意外行为时，在提出修复之前执行系统化调试：复现问题、收集证据、定位原因、验证假设并以最小变更修复，避免凭直觉试改。$zh239$,
        'obra/superpowers', 'systematic-debugging', 0, FALSE),
    (185, 'gpt-taste', $zh239$GPT 高级动效设计品味$zh239$,
        $zh239$结合高级 UX/UI 与 GSAP 动效规范，生成富有变化且转化导向的网页体验。$zh239$,
        $zh239$用于高级 UX/UI 和 GSAP 动效工程。以 Python 驱动布局随机化，遵循 AIDA 页面结构、宽幅编辑排版和无缝 Bento 网格，使用 GSAP ScrollTrigger 的固定、堆叠与滚动同步，并通过微型图像和克制间距提升叙事与质感。$zh239$,
        'leonxlnx/taste-skill', 'gpt-taste', 0, FALSE),
    (186, 'remotion-to-hyperframes', $zh239$Remotion 转 HyperFrames$zh239$,
        $zh239$把现有 Remotion React 合成源代码单向移植为 HyperFrames HTML。$zh239$,
        $zh239$仅在用户明确要求将现有 Remotion 源代码移植、转换或迁移到 HyperFrames 时使用。保留构图和时间逻辑并完成单向转换；若只是提到 Remotion、把代码当参考，或希望制作相似的新视频，则不走此流程。$zh239$,
        'heygen-com/hyperframes', 'remotion-to-hyperframes', 0, FALSE),
    (187, 'git-guardrails-claude-code', $zh239$Claude Code Git 安全护栏$zh239$,
        $zh239$为 Claude Code 配置钩子，在危险 Git 命令执行前进行拦截。$zh239$,
        $zh239$用于防止 Claude Code 执行危险 Git 操作。安装并配置钩子，拦截 push、reset --hard、clean、branch -D 等可能破坏或发布状态的命令，让用户在实际执行前得到明确保护。$zh239$,
        'mattpocock/skills', 'git-guardrails-claude-code', 0, FALSE),
    (188, 'writing-plans', $zh239$多步骤实施计划编写$zh239$,
        $zh239$在触碰代码前，把已有规格或需求整理为可执行、可验证的多步骤实施计划。$zh239$,
        $zh239$用于已有规格或需求的多步骤任务。在开始编码前拆分目标、文件范围、依赖关系、实施顺序、验证方式和检查点，使后续执行可审查、可回滚且不遗漏约束。$zh239$,
        'obra/superpowers', 'writing-plans', 0, FALSE),
    (189, 'design-an-interface', $zh239$并行设计接口方案$zh239$,
        $zh239$通过并行子代理为模块生成差异显著的 API、选项与结构方案并进行比较。$zh239$,
        $zh239$用于设计 API、探索接口选项、比较模块形态或用户要求“设计两次”的场景。让多个子代理独立提出真正不同的接口方案，再从调用体验、扩展性、约束表达和维护成本等维度并列评估。$zh239$,
        'mattpocock/skills', 'design-an-interface', 0, TRUE),
    (190, 'using-superpowers', $zh239$Superpowers Skill 使用规范$zh239$,
        $zh239$在会话开始时建立 Skill 查找与调用纪律，要求回复或追问前先检查适用能力。$zh239$,
        $zh239$用于每次会话开始，先识别、读取并调用可能适用的 Skill，再进行任何回复，包括澄清问题。它建立一致的能力发现流程，避免绕过已有的专业指令。$zh239$,
        'obra/superpowers', 'using-superpowers', 0, FALSE),
    (191, 'supabase', $zh239$Supabase 全栈开发助手$zh239$,
        $zh239$覆盖 Supabase 数据库、认证、边缘函数、实时、存储、向量、定时任务与队列的开发和排障。$zh239$,
        $zh239$用于任何 Supabase 任务，涵盖 Database、Auth、Edge Functions、Realtime、Storage、Vectors、Cron 和 Queues，以及 supabase-js、服务端渲染集成、登录与会话、RLS、CLI、MCP、模式设计、安全和 PostgreSQL 扩展。$zh239$,
        'supabase/agent-skills', 'supabase', 0, FALSE),
    (192, 'setup-pre-commit', $zh239$Git 提交前检查配置$zh239$,
        $zh239$在当前仓库配置 Husky、lint-staged、Prettier、类型检查和测试等提交前护栏。$zh239$,
        $zh239$用于添加或修复提交前检查。配置 Husky pre-commit 钩子，以 lint-staged 对暂存文件执行 Prettier，并按项目需要运行类型检查与测试，让格式和基础质量问题在提交前暴露。$zh239$,
        'mattpocock/skills', 'setup-pre-commit', 0, FALSE),
    (193, 'brandkit', $zh239$高级品牌视觉套件生成$zh239$,
        $zh239$生成高端品牌规范板、标志系统、身份提案和视觉世界展示图。$zh239$,
        $zh239$用于创建高级品牌套件图像，支持极简、电影感、编辑型、暗黑科技、奢华、文化、安全、游戏、开发者工具和消费应用等方向。强调有意图的标志、稀疏排版、符号体系、网格、配色和真实应用 mockup，形成连贯的品牌世界。$zh239$,
        'leonxlnx/taste-skill', 'brandkit', 0, FALSE),
    (194, 'azure-cost-optimization', $zh239$Azure 成本优化分析$zh239$,
        $zh239$分析 Azure 用量与支出，识别闲置资源、规格过大、浪费、异常和预算机会。$zh239$,
        $zh239$用于降低 Azure 成本和生成优化报告。结合用量与支出发现孤立资源、虚拟机规格调整、Redis、存储、AKS 与命名空间浪费、费用尖峰和异常，并提出预算与节省建议；不负责资源部署、一般诊断或安全审计。$zh239$,
        'microsoft/azure-skills', 'azure-cost-optimization', 0, FALSE),
    (195, 'scaffold-exercises', $zh239$课程练习结构搭建$zh239$,
        $zh239$创建包含章节、题目、解答和讲解的课程练习目录，并确保通过项目 lint。$zh239$,
        $zh239$用于搭建练习、创建题目骨架或新增课程章节。按仓库约定生成章节、问题、解答与讲解文件，补齐必要元数据和引用，并运行 lint 确认结构有效。$zh239$,
        'mattpocock/skills', 'scaffold-exercises', 0, FALSE),
    (196, 'request-refactor-plan', $zh239$重构计划与 GitHub 提案$zh239$,
        $zh239$通过访谈形成由微小提交组成的安全重构计划，并提交为 GitHub Issue。$zh239$,
        $zh239$用于规划重构、编写重构 RFC 或把大型改造拆成安全增量。先向用户追问目标、约束和验收方式，再产出详细的小提交序列、风险与验证点，最后将计划创建为 GitHub Issue。$zh239$,
        'mattpocock/skills', 'request-refactor-plan', 0, TRUE),
    (197, 'writing-shape', $zh239$文章逐段塑形$zh239$,
        $zh239$把已有原始材料逐段塑造成结构清楚、论证连贯的文章。$zh239$,
        $zh239$用于进入写作收敛阶段，把素材按段落组织成文章。确定每段承担的功能，建立段落之间的推进关系，补足论据与转折并删除游离内容，而不是继续无结构地发散素材。$zh239$,
        'mattpocock/skills', 'writing-shape', 0, FALSE),
    (198, 'imagegen-frontend-web', $zh239$高端网站分区视觉生成$zh239$,
        $zh239$为转化导向的网站逐区生成独立的横向高端设计参考图。$zh239$,
        $zh239$用于生成高级、重视转化的网站视觉方向。每个页面区块必须单独生成一张横向图片，不把多个区块压成一张；通过多样构图、英雄区、行动号召、叙事、配色与可开发还原的细节，形成完整页面参考。$zh239$,
        'leonxlnx/taste-skill', 'imagegen-frontend-web', 0, FALSE),
    (199, 'writing-fragments', $zh239$写作素材碎片挖掘$zh239$,
        $zh239$从原始材料中挖掘有价值的写作碎片，暂不强加文章结构。$zh239$,
        $zh239$用于写作探索阶段，从访谈、笔记、想法和事实中提取可能有用的观点、例子、措辞、问题与矛盾。保持素材颗粒度，不急于排序、论证或编排成完整文章。$zh239$,
        'mattpocock/skills', 'writing-fragments', 0, FALSE),
    (200, 'image-to-code', $zh239$网站视觉图转代码$zh239$,
        $zh239$先生成并分析网站设计图，再以代码尽可能忠实地还原视觉和布局。$zh239$,
        $zh239$用于视觉重要的网站实现。先自行生成所需设计图并深入分析构图、排版、色彩、间距与素材，再编写代码匹配参考；优先使用大型、清晰、按区块划分的图像，避免过度嵌套卡片，并保证首屏在常见笔记本视口内可读。$zh239$,
        'leonxlnx/taste-skill', 'image-to-code', 0, FALSE),
    (201, 'writing-beats', $zh239$文章节拍与叙事编排$zh239$,
        $zh239$把原始材料组织成递进的叙事节拍，并在使用概念前先完成必要铺垫。$zh239$,
        $zh239$用于写作收敛阶段，将素材编成读者可跟随的旅程。明确每个节拍带来的新认识、情绪或证据，安排转折和递进，并确保术语在后续论证依赖它之前已被解释和落地。$zh239$,
        'mattpocock/skills', 'writing-beats', 0, FALSE),
    (202, 'migrate-to-shoehorn', $zh239$测试迁移到 Shoehorn$zh239$,
        $zh239$把测试中的 as 类型断言迁移为 @total-typescript/shoehorn 的安全测试数据构造。$zh239$,
        $zh239$用于测试代码提到 shoehorn、需要替换 as 断言或构造部分测试数据时。识别不安全类型断言，改用 @total-typescript/shoehorn 提供的工具，并保持测试意图、可读性和类型检查结果。$zh239$,
        'mattpocock/skills', 'migrate-to-shoehorn', 0, FALSE),
    (203, 'qa', $zh239$交互式 QA 与缺陷建单$zh239$,
        $zh239$通过对话收集缺陷，同时后台理解代码上下文并创建清晰的 GitHub Issue。$zh239$,
        $zh239$用于用户希望会话式报告缺陷、开展 QA 或创建 Issue。边问边澄清复现步骤、预期与实际结果，并在后台探索代码库以采用正确领域语言；把每个可操作问题整理为证据充分的 GitHub Issue。$zh239$,
        'mattpocock/skills', 'qa', 0, FALSE),
    (204, 'ubiquitous-language', $zh239$DDD 统一语言词汇表$zh239$,
        $zh239$从当前对话提取领域驱动设计词汇，标记歧义并提出规范术语。$zh239$,
        $zh239$用于定义领域术语、建立词汇表或统一命名。从当前对话提取概念、角色、动作与边界，指出一词多义和同义冲突，提出可执行的规范定义，并保存到 UBIQUITOUS_LANGUAGE.md。$zh239$,
        'mattpocock/skills', 'ubiquitous-language', 0, FALSE),
    (205, 'imagegen-frontend-mobile', $zh239$高端移动应用视觉生成$zh239$,
        $zh239$为 iOS、Android 和跨平台产品生成高级、原生感强且多屏一致的界面视觉。$zh239$,
        $zh239$用于创建移动应用屏幕概念和流程图像。强调清晰层级、舒适可读文字、多屏一致性、受控配色、适量纹理、图像和图标，并以高级手机 mockup 展示；只生成视觉参考，不输出实现代码。$zh239$,
        'leonxlnx/taste-skill', 'imagegen-frontend-mobile', 0, FALSE),
    (206, 'emil-design-eng', $zh239$Emil Kowalski 界面精修方法$zh239$,
        $zh239$以 Emil Kowalski 的设计工程理念指导界面精修、组件设计、动效取舍与隐性细节。$zh239$,
        $zh239$用于提升软件界面的完成度，依据 Emil Kowalski 的理念审视组件行为、动画必要性、时序、反馈、触感和像素级细节，让交互自然、克制且可靠，而非堆叠装饰效果。$zh239$,
        'emilkowalski/skills', 'emil-design-eng', 0, FALSE),
    (207, 'obsidian-vault', $zh239$Obsidian 知识库管理$zh239$,
        $zh239$在 Obsidian vault 中搜索、创建和整理使用双向链接与索引笔记的内容。$zh239$,
        $zh239$用于查找、创建或组织 Obsidian 笔记。遵循 vault 现有结构与命名，维护 wikilink、反向关联和索引笔记，帮助知识可发现且不产生孤立重复条目。$zh239$,
        'mattpocock/skills', 'obsidian-vault', 0, TRUE),
    (208, 'pptx', $zh239$PowerPoint 演示文稿处理$zh239$,
        $zh239$创建、读取、编辑、解析、合并或拆分 PowerPoint 演示文稿与模板。$zh239$,
        $zh239$用于任何涉及 .pptx 或 .potx 的输入或输出，包括创建演示、路演稿和汇报，读取或提取文本，编辑现有页面，套用模板与布局，合并、拆分或重排文件，以及处理讲者备注和评论。$zh239$,
        'anthropics/skills', 'pptx', 0, FALSE),
    (209, 'azure-reliability', $zh239$Azure PaaS 可靠性评估$zh239$,
        $zh239$评估并改进 Azure Functions 与 App Service 的区域冗余、健康检查和多区域故障转移能力。$zh239$,
        $zh239$用于评估 Azure Functions 和 Azure App Service 的可靠性。扫描已部署资源的可用区冗余、ZRS 存储、健康探针与多区域故障转移，给出按能力组织的检查清单，并在确认后分阶段执行 CLI 或 IaC 修复。$zh239$,
        'microsoft/azure-skills', 'azure-reliability', 0, FALSE),
    (210, 'requesting-code-review', $zh239$发起代码审查$zh239$,
        $zh239$在完成任务、重大功能或合并前发起代码审查，确认实现符合需求。$zh239$,
        $zh239$用于任务完成、重大功能实现或准备合并时请求代码审查。向审查者提供目标、变更范围和验证证据，重点确认实现是否满足需求、是否引入回归以及是否遗漏边界条件。$zh239$,
        'obra/superpowers', 'requesting-code-review', 0, FALSE),
    (211, 'edit-article', $zh239$文章结构与文字编辑$zh239$,
        $zh239$通过重组章节、提升清晰度和压缩冗余来编辑并改善文章草稿。$zh239$,
        $zh239$用于修改、修订或提升已有文章。重新安排章节与段落顺序，澄清论点和指代，收紧冗长表述，修复节奏与衔接，同时保留作者原意和声音。$zh239$,
        'mattpocock/skills', 'edit-article', 0, TRUE),
    (212, 'test-driven-development', $zh239$测试驱动开发流程$zh239$,
        $zh239$在实现功能或修复缺陷前先编写失败测试，再以最小代码使其通过并重构。$zh239$,
        $zh239$用于任何新功能或缺陷修复。先把预期行为写成可复现的失败测试，确认测试确实因目标问题失败，再实现最小修复、运行完整验证并在绿灯下重构，避免先写实现后补形式化测试。$zh239$,
        'obra/superpowers', 'test-driven-development', 0, FALSE),
    (213, 'vercel-react-native-skills', $zh239$Vercel React Native 最佳实践$zh239$,
        $zh239$提供 React Native 与 Expo 的组件、列表性能、动画和原生模块开发规范。$zh239$,
        $zh239$用于构建 React Native 或 Expo 应用，覆盖高性能组件、长列表优化、动画实现、原生模块与平台 API 集成，以及移动端性能问题的诊断和改进。$zh239$,
        'vercel-labs/agent-skills', 'vercel-react-native-skills', 0, TRUE),
    (214, 'seo-audit', $zh239$网站 SEO 全面审计$zh239$,
        $zh239$审计并诊断网站的技术 SEO、页面优化、抓取索引、排名与核心网页指标问题。$zh239$,
        $zh239$用于网站 SEO 审计、流量或排名下降诊断。检查抓取与索引、站点结构、元数据、页面内容、链接和 Core Web Vitals，并按影响给出修复优先级；程序化 SEO、结构化数据和 AI 搜索优化应使用对应专项能力。$zh239$,
        'coreyhaines31/marketingskills', 'seo-audit', 0, FALSE),
    (215, 'executing-plans', $zh239$按计划分阶段执行$zh239$,
        $zh239$在独立会话中执行书面实施计划，并在预设检查点暂停复核。$zh239$,
        $zh239$用于已有明确书面计划的实施任务。按顺序执行步骤，维护进度和证据，在计划指定的检查点汇报并接受审查；遇到前提不成立或结果偏离时停止确认，而不是擅自改写计划。$zh239$,
        'obra/superpowers', 'executing-plans', 0, FALSE),
    (216, 'lark-note-larksuite-cli', $zh239$飞书会议纪要直查$zh239$,
        $zh239$已知 note_id 时查询飞书会议纪要详情、展示类型、关联文档 token 和原始逐字记录。$zh239$,
        $zh239$用于用户已持有 note_id，或已从文档的 vc-node-id 明确获得 note_id 的场景。可查询纪要详情、展示类型、关联文档 token，并读取 unified 原始逐字记录；不负责定位会议、日程或妙记，不按标题搜索，也不读取 Docx 正文。$zh239$,
        'larksuite/cli', 'lark-note', 0, FALSE),
    (217, 'pdf', $zh239$PDF 文档全流程处理$zh239$,
        $zh239$读取、提取、创建、合并、拆分、旋转、加水印、填写、加密或 OCR 处理 PDF。$zh239$,
        $zh239$用于任何 PDF 任务，包括提取文本与表格、合并或拆分页、旋转页面、添加水印、创建新文档、填写表单、加密解密、提取图像以及对扫描件执行 OCR；需要布局质量时应进行渲染检查。$zh239$,
        'anthropics/skills', 'pdf', 0, FALSE),
    (218, 'general-video', $zh239$HyperFrames 通用视频制作$zh239$,
        $zh239$在没有更专用流程时创作或编辑多场景、品牌、蒙太奇和自由形式的 HyperFrames 视频。$zh239$,
        $zh239$用于较长或多场景作品、品牌与氛围短片、蒙太奇、静态循环、标题卡、素材重混和自由构建，或 BRIEF.md 指定 companion 流程时。短小且以运动设计为核心的内容优先使用 motion-graphics。$zh239$,
        'heygen-com/hyperframes', 'general-video', 0, FALSE),
    (219, 'copywriting', $zh239$营销页面文案写作$zh239$,
        $zh239$为首页、落地页、定价页、功能页、关于页和产品页撰写有说服力的营销文案。$zh239$,
        $zh239$用于新写、重写或改善营销页面文案，覆盖标题、副标题、价值主张、卖点、行动号召、英雄区和标语。电子邮件、弹窗、既有文案编辑和优惠设计应使用对应专项能力。$zh239$,
        'coreyhaines31/marketingskills', 'copywriting', 0, FALSE),
    (220, 'verification-before-completion', $zh239$完成声明前验证$zh239$,
        $zh239$在声称完成、修复或测试通过前运行验证命令，并以实际输出支撑结论。$zh239$,
        $zh239$用于准备宣称任务完成、问题修复、测试通过、提交或创建 PR 之前。必须运行与风险相称的验证命令，阅读结果并确认没有遗漏；始终先给证据再下结论，不依赖记忆或推测。$zh239$,
        'obra/superpowers', 'verification-before-completion', 0, FALSE),
    (221, 'subagent-driven-development', $zh239$子代理驱动开发$zh239$,
        $zh239$在当前会话中把实施计划拆给独立子代理执行，并逐项审查和整合。$zh239$,
        $zh239$用于执行包含多个独立任务的实施计划。为每项工作分配边界清晰的子代理，提供必要上下文，收集结果后分别检查规格符合性和代码质量，再由主代理整合、验证并维护整体进度。$zh239$,
        'obra/superpowers', 'subagent-driven-development', 0, FALSE),
    (222, 'hyperframes-keyframes', $zh239$HyperFrames 关键帧动画$zh239$,
        $zh239$为 HyperFrames 实现可安全跳转的二维、三维关键帧和多类网页动画。$zh239$,
        $zh239$用于 HyperFrames 合成中的 GSAP 时间线、CSS keyframes、Anime.js、WAAPI、FLIP、运动路径、遮罩、SVG 形变或描边、文字轨迹、三维景深及 keyframes 诊断。它负责具体动画实现，不负责整体场景策略、品牌、媒体、字幕或策划。$zh239$,
        'heygen-com/hyperframes', 'hyperframes-keyframes', 0, FALSE),
    (223, 'docx', $zh239$Word 文档创建与编辑$zh239$,
        $zh239$创建、读取、编辑和重组 .docx 文档或 .dotx 模板，并处理专业排版与审阅内容。$zh239$,
        $zh239$用于任何 Word 文档任务，包括目录、标题层级、页码、信头、文本提取与重组、图片、查找替换、修订和评论。适用于 .docx 与 .dotx，不用于 PDF、电子表格或仅需普通代码输出的任务。$zh239$,
        'anthropics/skills', 'docx', 0, FALSE),
    (224, 'faceless-explainer', $zh239$无真人出镜解说视频$zh239$,
        $zh239$把文章、笔记、主题或简报转成逐场景原创视觉的无真人出镜解说视频。$zh239$,
        $zh239$用于概念讲解、操作教程、清单或任意文本主题的视频化。没有网站或既有镜头可捕获时，为每个场景设计排版、抽象图形、图解和数据可视化；若输入是网站或需要呈现真实页面，应使用对应网站视频流程。$zh239$,
        'heygen-com/hyperframes', 'faceless-explainer', 0, FALSE),
    (225, 'product-launch-video', $zh239$产品发布与宣传视频$zh239$,
        $zh239$把商业网址、脚本或简报制作成 SaaS、功能、应用或公司的发布宣传视频。$zh239$,
        $zh239$用于营销、发布、推广或揭示产品，可从产品网址、粘贴脚本或简报制作 SaaS 宣传、功能发布、产品演示、应用和公司发布片。商业 URL 默认走此流程；仅展示网站本身的导览应使用 website-to-video。$zh239$,
        'heygen-com/hyperframes', 'product-launch-video', 0, FALSE),
    (226, 'motion-graphics', $zh239$短篇动态图形制作$zh239$,
        $zh239$制作以运动为核心的短篇动态图形，包括动效文字、数据、图表、标志、地图和社交叠层。$zh239$,
        $zh239$用于通常少于 10 秒、最长约 30 秒的设计主导型动效，如 kinetic typography、数字增长、图表冲击、logo sting、lower-third、地图、推文、新闻、文章或 UI 动画。通常不含旁白和真人镜头；较长多场景作品使用 general-video。$zh239$,
        'heygen-com/hyperframes', 'motion-graphics', 0, FALSE),
    (227, 'receiving-code-review', $zh239$严谨处理代码审查意见$zh239$,
        $zh239$在实施审查建议前先验证其技术正确性，尤其针对含糊或可疑反馈。$zh239$,
        $zh239$用于收到代码审查意见后、修改代码之前。准确复述建议，结合仓库事实和测试验证其适用性；对不明确或技术上存疑的意见提出具体问题，避免表演式认同或不经判断地照单全收。$zh239$,
        'obra/superpowers', 'receiving-code-review', 0, FALSE),
    (228, 'writing-skills', $zh239$Skill 编写与发布验证$zh239$,
        $zh239$创建、编辑并在部署前验证 Agent Skill 的触发范围、指令和资源。$zh239$,
        $zh239$用于新建 Skill、修改现有 Skill 或部署前检查其是否有效。确保说明聚焦、触发条件明确、结构符合规范、引用资源可访问，并通过实际场景验证行为而非只检查文档外观。$zh239$,
        'obra/superpowers', 'writing-skills', 0, FALSE),
    (229, 'dispatching-parallel-agents', $zh239$并行分派独立代理$zh239$,
        $zh239$在存在两个以上无共享状态、无顺序依赖的任务时并行分派代理。$zh239$,
        $zh239$用于两个或更多可独立推进的子任务。先确认它们不写同一状态且没有前后依赖，再提供边界清晰的任务说明并行执行，最后收集、核对和整合结果；有共享状态或必须顺序推进时不应强行并行。$zh239$,
        'obra/superpowers', 'dispatching-parallel-agents', 0, FALSE),
    (230, 'using-git-worktrees', $zh239$Git Worktree 隔离开发$zh239$,
        $zh239$在开始需要隔离的功能或实施计划前，通过原生工具或 Git worktree 创建安全工作区。$zh239$,
        $zh239$用于功能开发需要与当前目录隔离，或执行实施计划前准备独立环境。优先使用原生工作区工具，必要时创建 Git worktree，并核对分支、路径、忽略规则和基线测试，避免污染用户现有修改。$zh239$,
        'obra/superpowers', 'using-git-worktrees', 0, FALSE),
    (231, 'wizard', $zh239$人工操作 Bash 向导$zh239$,
        $zh239$为只能由人完成的基础设施、凭据、控制台或迁移步骤生成交互式 Bash 向导。$zh239$,
        $zh239$用于基础设施预配、凭据或 CI 密钥配置、陌生第三方控制台操作、一次性迁移和切换等必须人工完成的流程。向导逐步提示、验证输入并记录进度；能由代理直接完成的普通任务不应使用。$zh239$,
        'mattpocock/skills', 'wizard', 0, FALSE),
    (232, 'design-taste-frontend-v1', $zh239$前端设计品味 v1 兼容版$zh239$,
        $zh239$保留原始 v1 前端设计行为，仅供依赖精确旧版语义的项目兼容使用。$zh239$,
        $zh239$这是原始 v1 taste-skill 的保留版本。当前默认版本为大幅重写的 design-taste-frontend v2；只有项目确实依赖 v1 的精确行为、提示结构或输出特征时才使用此安装名。$zh239$,
        'leonxlnx/taste-skill', 'design-taste-frontend-v1', 0, FALSE),
    (233, 'finishing-a-development-branch', $zh239$开发分支收尾与集成$zh239$,
        $zh239$在实现完成且测试通过后，系统决定合并、提 PR、保留或清理开发分支。$zh239$,
        $zh239$用于实现已完成、验证已通过并需要决定如何集成时。确认工作树状态和测试证据，向用户呈现合并、创建 PR、保留分支或安全清理等明确选项，并执行选定的可追溯收尾流程。$zh239$,
        'obra/superpowers', 'finishing-a-development-branch', 0, FALSE),
    (234, 'prisma-database-setup', $zh239$Prisma 数据库连接配置$zh239$,
        $zh239$为 PostgreSQL、MySQL、SQLite、MongoDB 等数据库配置 Prisma，并排查连接问题。$zh239$,
        $zh239$用于新项目数据库接入、切换数据库提供商或修复连接配置。覆盖 PostgreSQL、MySQL、SQLite、MongoDB 等提供商的 schema、连接字符串、生成器和必要环境变量，并按具体数据库验证连接。$zh239$,
        'prisma/skills', 'prisma-database-setup', 0, FALSE),
    (235, 'prisma-client-api', $zh239$Prisma Client API 查询指南$zh239$,
        $zh239$提供 Prisma Client 模型查询、过滤器、运算符、CRUD 与事务方法参考。$zh239$,
        $zh239$用于编写 Prisma 数据库查询和配置 Client。覆盖 findMany 等模型方法、创建更新删除、关系查询、过滤与排序运算符、批量操作和 $transaction，并帮助选择类型安全且符合业务语义的调用方式。$zh239$,
        'prisma/skills', 'prisma-client-api', 0, FALSE),
    (236, 'loop-me', $zh239$工作流规格深度访谈$zh239$,
        $zh239$围绕当前工作区想要构建的工作流进行密集追问，把模糊想法收敛为规格。$zh239$,
        $zh239$用于用户希望通过访谈澄清要构建的工作流。持续追问参与者、触发条件、输入输出、状态、异常、权限、自动化边界和验收标准，识别矛盾与遗漏，直到得到足以实施的明确规格。$zh239$,
        'mattpocock/skills', 'loop-me', 0, FALSE),
    (237, 'prisma-cli', $zh239$Prisma ORM CLI 命令指南$zh239$,
        $zh239$参考 Prisma ORM 的 init、generate、migrate、db、studio、validate、format、debug 和 mcp 命令。$zh239$,
        $zh239$用于 Prisma ORM 和数据库命令行工作流，覆盖初始化、客户端生成、迁移、db 操作、开发服务、自动补全、Studio、校验、格式化、调试与 MCP。它不用于 Prisma Platform CLI。$zh239$,
        'prisma/skills', 'prisma-cli', 0, FALSE),
    (238, 'pr-to-video', $zh239$GitHub PR 变更解说视频$zh239$,
        $zh239$把 GitHub Pull Request 的差异、提交和文件制作成代码变更解说视频。$zh239$,
        $zh239$用于从 PR URL、owner/repo#N 或当前仓库中的指定 PR 制作 changelog、功能展示、修复或重构讲解。视频依据 diff、提交与文件呈现代码变化；输入是代码改动，不是网站，也不用于常规产品宣传。$zh239$,
        'heygen-com/hyperframes', 'pr-to-video', 0, FALSE),
    (239, 'prisma-postgres', $zh239$Prisma Postgres 运维指南$zh239$,
        $zh239$通过 Console、create-db CLI、Management API 或 SDK 创建并管理 Prisma Postgres。$zh239$,
        $zh239$用于创建和操作 Prisma Postgres 数据库，覆盖 Prisma Console、create-db、create-pg、create-postgres、Management API 与 SDK，以及使用令牌或 OAuth 的程序化预配。$zh239$,
        'prisma/skills', 'prisma-postgres', 0, FALSE),
    (240, 'xlsx', $zh239$Excel 与表格文件处理$zh239$,
        $zh239$读取、编辑、修复、创建和转换 Excel、CSV、TSV 表格，并处理公式、格式与图表。$zh239$,
        $zh239$用于电子表格作为主要输入或输出的任务，覆盖 .xlsx、.xlsm、.xltx、.csv 和 .tsv。可新增列、计算公式、格式化、制图、清洗脏数据和转换格式；不适用于 Word、HTML 报告、普通脚本、数据库管线或 Google Sheets API 集成。$zh239$,
        'anthropics/skills', 'xlsx', 0, FALSE),
    (241, 'embedded-captions', $zh239$真人视频内嵌字幕$zh239$,
        $zh239$为单人讲话视频添加普通、电影感、主体后方或特效字幕，不改动原始镜头。$zh239$,
        $zh239$用于现有单主体 talking-head 视频的逐字字幕、电影感主体后字幕、VFX 字幕或 35 种命名风格。支持本地转写与主体抠像，画面本身保持不剪辑；多镜头内容需先拆分，图形包装应使用 talking-head-recut。$zh239$,
        'heygen-com/hyperframes', 'embedded-captions', 45, FALSE),
    (242, 'hyperframes-media', $zh239$HyperFrames 音频与媒体引擎$zh239$,
        $zh239$为 HyperFrames 提供多供应商语音、音乐、音效、转写、抠像和多样字幕资源。$zh239$,
        $zh239$用于 HyperFrames 合成中的音频和媒体资产，通过共享 audio.mjs 引擎支持 HeyGen、ElevenLabs 等 TTS、背景音乐、音效、转写、背景移除，以及字幕、歌词、卡拉 OK、逐词样式、声音和音乐提示。$zh239$,
        'heygen-com/hyperframes', 'hyperframes-media', 19, FALSE),
    (243, 'prisma-driver-adapter-implementation', $zh239$Prisma 驱动适配器实现$zh239$,
        $zh239$按 Prisma ORM 7 规范实现 SQL Driver Adapter、事务、结果映射与错误保真。$zh239$,
        $zh239$用于实现 Prisma ORM 7 的 SQL 驱动适配器。覆盖 SqlDriverAdapter、Transaction、savepoint、结果集映射、DriverAdapterError、连接生命周期和错误语义保留，并提供必要验证以确保适配器行为符合参考契约。$zh239$,
        'prisma/skills', 'prisma-driver-adapter-implementation', 0, FALSE),
    (244, 'prisma-upgrade-v7', $zh239$Prisma ORM 7 升级迁移$zh239$,
        $zh239$处理 Prisma ORM 6 升级到 7 的破坏性变更、生成器、驱动适配器和常见错误。$zh239$,
        $zh239$用于把 Prisma ORM v6 项目完整迁移到 v7。盘点破坏性变化，更新依赖、schema、生成器和客户端初始化，配置所需 driver adapter，逐项解决升级错误并运行迁移与测试验证。$zh239$,
        'prisma/skills', 'prisma-upgrade-v7', 0, FALSE),
    (245, 'prisma-postgres-setup', $zh239$Prisma Postgres 项目初始化$zh239$,
        $zh239$通过 Management API 创建 Prisma Postgres 数据库，并接入本地 Prisma 项目。$zh239$,
        $zh239$用于从零建立 Prisma Postgres 数据库和本地项目连接。通过 Management API 完成预配，安全取得连接字符串，配置环境变量与 Prisma schema，生成客户端并验证首次连接。$zh239$,
        'prisma/skills', 'prisma-postgres-setup', 0, FALSE),
    (246, 'prisma-compute', $zh239$Prisma Compute 部署指南$zh239$,
        $zh239$指导应用部署到 Prisma Compute，覆盖配置、认证、日志、域名、端口和框架就绪检查。$zh239$,
        $zh239$用于 Prisma Compute 的部署与托管。涵盖项目配置、CLI deploy、认证、workspace 和 app 管理、日志、域名、端口约定，以及常见框架的生产就绪检查与故障排查。$zh239$,
        'prisma/skills', 'prisma-compute', 0, FALSE),
    (247, 'prisma-mongodb-upgrade', $zh239$Prisma MongoDB 升级决策$zh239$,
        $zh239$解释 Prisma MongoDB 从 v6 无法直接升级 v7 的限制，并规划迁移到 Prisma Next。$zh239$,
        $zh239$用于采用 MongoDB 的 Prisma v6 项目评估升级。明确当前不存在直接的 v7 迁移路径，帮助比较保持现状与迁移到 Prisma Next 的选择，并规划兼容性验证、数据风险和分阶段切换。$zh239$,
        'prisma/skills', 'prisma-mongodb-upgrade', 0, FALSE),
    (248, 'music-to-video', $zh239$音乐节拍同步视频$zh239$,
        $zh239$以音乐为节奏主轴制作歌词、幻灯片、动效或宣传视频。$zh239$,
        $zh239$用于从音频、视频或情绪参考制作 beat-synced 歌词视频、幻灯片、动效宣传片，也可在没有其他资产时创作。音乐决定剪辑节奏、场景长度和视觉冲击；以旁白为主的内容应使用其他视频流程。$zh239$,
        'heygen-com/hyperframes', 'music-to-video', 67, FALSE),
    (249, 'webapp-testing', $zh239$Playwright Web 应用测试$zh239$,
        $zh239$使用 Playwright 测试本地 Web 应用、调试交互、截图并检查浏览器日志。$zh239$,
        $zh239$用于对本地 Web 应用执行真实浏览器测试。导航页面、操作控件、验证功能与状态、捕获截图，读取控制台和网络相关线索，并用可重复步骤定位界面或交互问题。$zh239$,
        'anthropics/skills', 'webapp-testing', 0, FALSE),
    (250, 'claude-handoff', $zh239$Claude 会话即时交接$zh239$,
        $zh239$把当前对话上下文立即交接给新的后台 Claude 代理继续处理。$zh239$,
        $zh239$用于用户希望立即将当前工作交给一个全新的后台代理。整理目标、已完成事项、关键上下文、文件状态、验证结果和待办，并把足以无缝继续的交接信息发送给新代理。$zh239$,
        'mattpocock/skills', 'claude-handoff', 0, FALSE),
    (251, 'slideshow', $zh239$HyperFrames 交互式幻灯片$zh239$,
        $zh239$制作带页面、分步呈现、分支、热点和讲者备注的 HyperFrames 交互式演示。$zh239$,
        $zh239$用于构建离散幻灯片或 pitch deck，支持 fragments、条件分支、交互热点、讲者备注和逐页转换。输出是可交互演示而非 MP4；除非用户明确要求，否则应先确认采用幻灯片形态。$zh239$,
        'heygen-com/hyperframes', 'slideshow', 0, FALSE),
    (252, 'firebase-basics', $zh239$Firebase CLI 基础配置$zh239$,
        $zh239$完成 Firebase CLI 安装、版本检查、登录、项目创建切换和应用配置下载。$zh239$,
        $zh239$用于 Firebase CLI 的基础设置，包括安装 firebase-tools、检查最新版版本、常规或 --no-localhost 登录、创建与切换项目，以及下载 google-services.json 或 GoogleService-Info.plist。仅处理这些基础操作，不负责 Hosting 部署、Firestore、Auth、App Hosting、Data Connect、Crashlytics 或 Remote Config。$zh239$,
        'firebase/agent-skills', 'firebase-basics', 0, FALSE),
    (253, 'extract-design-system', $zh239$网站设计系统提取$zh239$,
        $zh239$从公开网站提取设计基础要素，并为项目生成可用的初始 token 文件。$zh239$,
        $zh239$用于分析公开网站的颜色、字体、字号、间距、圆角、阴影和其他设计原语，将重复视觉规律归纳为语义化 token，并生成适合当前项目继续扩展的初始设计系统文件。$zh239$,
        'arvindrk/extract-design-system', 'extract-design-system', 0, FALSE),
    (254, 'firebase-auth-basics', $zh239$Firebase Authentication 基础$zh239$,
        $zh239$设置并使用 Firebase Authentication，实现用户登录、账户管理和基于身份的安全访问。$zh239$,
        $zh239$用于应用需要用户登录、用户管理或通过认证规则保护数据的场景。指导启用合适的登录提供商、集成客户端认证流程、管理会话与用户，并让 Firestore 或 Storage 规则安全使用认证身份。$zh239$,
        'firebase/agent-skills', 'firebase-auth-basics', 0, FALSE),
    (255, 'marketing-psychology', $zh239$营销心理学与行为科学$zh239$,
        $zh239$把认知偏差、心理模型和行为科学原则用于营销决策与说服设计。$zh239$,
        $zh239$用于理解或运用消费者如何思考和决策，覆盖锚定、社会认同、稀缺、损失厌恶、框架效应、助推和其他心理模型。具体页面的转化应用、定价策略和文案框架应分别结合对应专项能力。$zh239$,
        'coreyhaines31/marketingskills', 'marketing-psychology', 0, FALSE),
    (256, 'sentry-cli', $zh239$Sentry CLI 操作指南$zh239$,
        $zh239$通过命令行认证 Sentry，并查看问题、事件、项目、组织或调用 API。$zh239$,
        $zh239$用于从命令行与 Sentry 交互，指导安装和认证 sentry-cli，定位组织与项目，查看 issues 和 events，并在需要时执行受控 API 请求，帮助自动化排障和发布相关操作。$zh239$,
        'sentry/dev', 'sentry-cli', 0, TRUE),
    (257, 'ui-radar', $zh239$UIZZE 界面案例雷达$zh239$,
        $zh239$从 UIZZE 超过五十万张 Web 与 iOS 界面中查找并比较真实产品案例。$zh239$,
        $zh239$用于设计或重设计前的界面灵感与产品研究。搜索真实 Web 和 iOS 屏幕，比较同类应用、用户流程、布局、导航、组件、交互状态与产品模式，以具体案例支撑设计决策。$zh239$,
        'uizze.com', 'ui-radar', 0, TRUE),
    (258, 'firebase-hosting-basics', $zh239$Firebase Hosting 部署$zh239$,
        $zh239$部署和配置静态网站、单页应用及微服务的经典 Firebase Hosting。$zh239$,
        $zh239$用于静态站点或 SPA 部署、自定义域名、firebase.json 中的重定向、重写、响应头、多站点配置和预览频道管理。它面向经典 Firebase Hosting，不用于 Next.js 或 SSR 的 App Hosting，也不处理 Auth、Firestore、Data Connect 或 Crashlytics。$zh239$,
        'firebase/agent-skills', 'firebase-hosting-basics', 0, FALSE),
    (259, 'firebase-app-hosting-basics', $zh239$Firebase App Hosting 全栈部署$zh239$,
        $zh239$使用 Firebase App Hosting 部署和管理带 SSR 的 Next.js 或 Angular 全栈应用。$zh239$,
        $zh239$用于 Next.js、Angular 等服务端渲染应用，覆盖 apphosting.yaml、firebase.json apphosting 配置、密钥管理、GitHub CI/CD 和 Blaze 计费要求。它不适用于经典静态 Hosting、Auth、Firestore、Crashlytics 或 Xcode。$zh239$,
        'firebase/agent-skills', 'firebase-app-hosting-basics', 0, FALSE),
    (260, 'higgsfield-generate', $zh239$Higgsfield 多模态内容生成$zh239$,
        $zh239$通过 Higgsfield AI 生成或编辑图像、视频、三维资产、音频和广告内容。$zh239$,
        $zh239$用于图像生成与编辑、文生视频、图生视频、视频重构、草图编辑、3D 模型或 GLB、音效、音乐、广告、UGC、开箱和商品导入等任务，并可使用 Marketing Studio 与 Virality Predictor。默认按媒介选择 GPT Image、Seedance、Nano Banana 或 Seed Audio；Soul 训练、品牌手册、商品摄影、缩略图、解说视频、游戏和 TTS 应走对应专项能力。$zh239$,
        'higgsfield-ai/skills', 'higgsfield-generate', 0, FALSE),
    (261, 'firebase-data-connect', $zh239$Firebase Data Connect 开发$zh239$,
        $zh239$使用 PostgreSQL 安全构建和部署 Firebase Data Connect 关系型后端。$zh239$,
        $zh239$用于需要 Firebase 关系型数据库或提到 SQL Connect、Data Connect 的场景。设计表与关系模式，编写带授权的查询和 mutation，配置实时更新，并生成类型安全 SDK，完成后端部署与客户端接入。$zh239$,
        'firebase/agent-skills', 'firebase-data-connect', 0, FALSE),
    (262, 'content-strategy', $zh239$内容策略规划$zh239$,
        $zh239$规划应生产什么内容、覆盖哪些主题，以及内容支柱、集群、日历和路线图。$zh239$,
        $zh239$用于内容创意、博客策略、主题集群、编辑日历和内容营销路线图。根据受众、业务目标、渠道和竞争差距决定内容优先级，而不是直接撰写单篇内容；具体文案、SEO 审计和社交内容使用相应专项能力。$zh239$,
        'coreyhaines31/marketingskills', 'content-strategy', 0, FALSE),
    (263, 'python-appservice-deploy', $zh239$Azure App Service Python 部署$zh239$,
        $zh239$把 Flask、Django 或 FastAPI 应用部署到 Azure App Service Linux。$zh239$,
        $zh239$用于将 Python Web 应用部署到 Azure App Service Linux，覆盖 Flask、Django 和 FastAPI 的运行命令、依赖与平台配置。不用于 Container Apps、Functions、非 Python 应用、Terraform、Bicep 或完整基础设施设计；这些场景应使用 azure-prepare。$zh239$,
        'microsoft/azure-skills', 'python-appservice-deploy', 0, FALSE),
    (264, 'orca-cli', $zh239$Orca CLI 工作区控制$zh239$,
        $zh239$使用 orca CLI 管理 Orca 工作树、目录上下文、终端、仓库、自动化、产物和内嵌浏览器。$zh239$,
        $zh239$用于 Orca 管理的 worktree、子工作树、终端收发与等待、仓库、自动化、产物、评论、完整交接和内嵌浏览器控制。涉及 Orca 状态时优先于原始 git worktree、临时 PTY 或 Playwright；Orca 外部浏览器和桌面界面使用 Computer Use。$zh239$,
        'stablyai/orca', 'orca-cli', 0, FALSE),
    (265, 'programmatic-seo', $zh239$程序化 SEO 页面生成$zh239$,
        $zh239$用模板和数据批量创建面向不同关键词、位置或比较维度的 SEO 页面。$zh239$,
        $zh239$用于目录页、地区页、关键词加城市页、比较页、集成页和其他数据驱动的规模化落地页。定义可复用模板、数据来源、唯一价值和质量护栏，避免制造薄内容；已有 SEO 问题审计和一般内容规划应使用对应能力。$zh239$,
        'coreyhaines31/marketingskills', 'programmatic-seo', 0, FALSE),
    (266, 'playwright-cli', $zh239$Playwright CLI 浏览器自动化$zh239$,
        $zh239$通过 Playwright CLI 自动操作浏览器、测试网页并处理 Playwright 测试。$zh239$,
        $zh239$用于导航网页、点击与输入、获取页面状态、验证交互、截图以及创建、运行或调试 Playwright 测试，为 Web 自动化和端到端测试提供可重复的命令行流程。$zh239$,
        'microsoft/playwright-cli', 'playwright-cli', 0, FALSE),
    (267, 'talking-head-recut', $zh239$真人视频图形包装$zh239$,
        $zh239$为讲话、访谈或播客视频同步添加设计化图形卡片，同时保留底层镜头不变。$zh239$,
        $zh239$用于在 16:9、9:16 或 4:5 画布上给 talking-head、访谈或播客添加 kinetic title、lower-third、数据提示、引语、侧栏和画中画，并与逐字稿时间同步。原视频在下层完整播放；纯字幕使用 embedded-captions，不明确时使用 hyperframes。$zh239$,
        'heygen-com/hyperframes', 'talking-head-recut', 6, FALSE),
    (268, 'marketing-ideas', $zh239$SaaS 营销创意库$zh239$,
        $zh239$为 SaaS 或软件产品提供增长灵感、营销策略和可尝试的推广战术。$zh239$,
        $zh239$用于用户不知道如何营销、需要增长点子、推广方式或策略脑暴时。结合产品阶段、受众和资源提出多渠道候选，并说明优先级与试验方式；具体广告、社交、邮件等执行交给相应专项能力。$zh239$,
        'coreyhaines31/marketingskills', 'marketing-ideas', 0, FALSE),
    (269, 'to-questionnaire', $zh239$决策问题问卷化$zh239$,
        $zh239$把当前无法独立回答的决策问题转换为由他人填写的结构化问卷。$zh239$,
        $zh239$用于决策所需信息掌握在其他人手中时。拆解未知项、选项、约束和取舍，生成措辞清晰、顺序合理、便于汇总的问卷，使答复能够直接支持后续判断。$zh239$,
        'mattpocock/skills', 'to-questionnaire', 0, FALSE),
    (270, 'copy-editing', $zh239$营销文案编辑$zh239$,
        $zh239$审阅、校对、精修和更新已有营销文案，使表达更清楚、精炼且有说服力。$zh239$,
        $zh239$用于用户已有文案并希望获得反馈、润色、压缩、信息锐化或过时内容更新。系统检查结构、价值主张、语气、证据、行动号召和冗余，并保留有效内容；从零写新文案应使用 copywriting。$zh239$,
        'coreyhaines31/marketingskills', 'copy-editing', 0, FALSE),
    (271, 'browser-act', $zh239$browser-act 浏览器自动化$zh239$,
        $zh239$通过 browser-act 管理真实浏览器会话，抓取、操作、验证和观察动态网页。$zh239$,
        $zh239$用于 JavaScript 页面、验证提示、登录会话、表单、点击流程、上传、截图、XHR 或 HAR 捕获、并行 URL、滚动加载和视觉检查。任何 browser-act 命令都应先调用此能力，不直接从 Bash 执行；需要渲染和认证状态时优先于简单抓取工具。$zh239$,
        'browser-act/skills', 'browser-act', 0, FALSE),
    (272, 'deploy-to-vercel', $zh239$Vercel 应用部署$zh239$,
        $zh239$把应用或网站部署到 Vercel，并返回正式或预览部署链接。$zh239$,
        $zh239$用于用户要求部署应用、上线网站、生成可访问链接或创建预览部署时。识别项目配置，执行 Vercel 部署，核对构建结果并向用户提供最终地址和必要状态。$zh239$,
        'vercel-labs/agent-skills', 'deploy-to-vercel', 1, TRUE),
    (273, 'ai-seo', $zh239$AI 搜索可见性优化$zh239$,
        $zh239$优化内容在 AI 搜索、LLM 回答和生成式答案中的引用率与可见性。$zh239$,
        $zh239$用于 AEO、GEO、LLMO、AI Overviews、ChatGPT 或 Perplexity 引用、零点击搜索、llms.txt、OKF 和机器可读知识包。提升内容的可理解性、可信来源、实体表达和可引用结构；传统技术 SEO 审计与 schema 实现使用对应能力。$zh239$,
        'coreyhaines31/marketingskills', 'ai-seo', 0, FALSE),
    (274, 'higgsfield-product-photoshoot', $zh239$Higgsfield 商品摄影$zh239$,
        $zh239$通过 Higgsfield 提示增强生成品牌级棚拍、生活方式和广告商品视觉。$zh239$,
        $zh239$用于专业商品照、棚拍、生活方式图、Pinterest、英雄横幅、轮播、广告素材、虚拟试穿、人物持物、近景、悬浮或 CGI 商品和季节化重塑。由后端组装最终提示，不手写替代；无商品图像、电商列表卡、视频或 Soul 训练走对应能力。$zh239$,
        'higgsfield-ai/skills', 'higgsfield-product-photoshoot', 0, FALSE),
    (275, 'higgsfield-soul-id', $zh239$Higgsfield Soul 身份模型$zh239$,
        $zh239$训练忠实保留人物面部身份的 Soul Character，供后续图像和视频生成复用。$zh239$,
        $zh239$用于训练个人面孔、数字分身或视频身份模型。一次性训练返回 reference_id，之后可作为 soul-id 传给 Higgsfield 生成模型以保持身份一致；单次换脸直接使用图像参考，非真人命名角色则使用普通生成提示。$zh239$,
        'higgsfield-ai/skills', 'higgsfield-soul-id', 0, FALSE),
    (276, 'website-to-video', $zh239$网站导览视频$zh239$,
        $zh239$抓取普通网站并用其截图与品牌资产制作网站本身的导览、展示或社交短片。$zh239$,
        $zh239$用于作品集、博客、文档或落地页的站点展示，从 URL 捕获真实页面和品牌素材并剪成视频。重点是呈现网站本身，不用于产品发布或营销宣传；商业推广需求使用 product-launch-video。$zh239$,
        'heygen-com/hyperframes', 'website-to-video', 19, FALSE),
    (277, 'higgsfield-marketplace-cards', $zh239$Higgsfield 电商商品图卡$zh239$,
        $zh239$生成符合平台要求的商品主图、辅图、信息图、生活方式图和 A+ 内容模块。$zh239$,
        $zh239$用于电商列表图片、商品详情卡、销售型图片集和 A+ 风格内容。后端负责平台合规参考与提示模板，此能力只把用户意图路由到 CLI；普通品牌商品摄影、视频或 UGC 广告、Soul 训练使用相应能力。$zh239$,
        'higgsfield-ai/skills', 'higgsfield-marketplace-cards', 0, FALSE),
    (278, 'orchestration', $zh239$Orca 多代理编排$zh239$,
        $zh239$用 Orca 构建线程消息、问答阻塞、任务 DAG、决策门和协调循环等结构化多代理流程。$zh239$,
        $zh239$用于需要监督和协调的多代理工作，包括线程消息、ask/reply、任务分派、worker_done 或 escalation 等待、任务 DAG、决策门与 coordinator loop。完整所有权交接、普通终端和 Orca 工作树管理使用 orca-cli；Orca 外桌面界面使用 Computer Use。$zh239$,
        'stablyai/orca', 'orchestration', 0, FALSE),
    (279, 'mcp-builder', $zh239$MCP 服务构建指南$zh239$,
        $zh239$设计并实现高质量 MCP 服务，让 LLM 通过清晰工具安全连接外部 API 与服务。$zh239$,
        $zh239$用于以 Python FastMCP 或 Node.js、TypeScript MCP SDK 构建 Model Context Protocol 服务。指导工具边界、参数与返回模式、错误处理、认证、资源设计和可用性，使模型能可靠地与外部系统交互。$zh239$,
        'anthropics/skills', 'mcp-builder', 0, FALSE),
    (280, 'convex-quickstart', $zh239$Convex 极简项目启动$zh239$,
        $zh239$根据一句话产品想法启动可运行的最小 Convex 与 Web 模板。$zh239$,
        $zh239$用于快速验证想法，从一句话需求生成最精简的 Convex 后端和 Web 前端骨架，完成必要配置、基本数据流和本地运行入口，避免过早加入非必要架构。$zh239$,
        'get-convex/agent-skills', 'convex-quickstart', 0, TRUE),
    (281, 'convex-create-component', $zh239$Convex 可复用组件开发$zh239$,
        $zh239$构建拥有隔离数据表和面向应用 API 的可复用 Convex 组件。$zh239$,
        $zh239$用于新建 Convex 组件、可复用后端模块、第三方集成或划分组件边界。把内部表与实现封装在组件内，仅暴露稳定的应用 API，并明确安装、配置和依赖契约。$zh239$,
        'get-convex/agent-skills', 'convex-create-component', 0, TRUE),
    (282, 'azure-observability', $zh239$Azure 可观测性服务$zh239$,
        $zh239$使用 Azure Monitor、Application Insights、Log Analytics、Alerts 和 Workbooks 建立监控。$zh239$,
        $zh239$用于 Azure 指标、APM、分布式追踪、KQL 查询、告警、监控仪表盘和交互式报告。覆盖 Azure Monitor、Application Insights、Log Analytics 与 Workbooks；应用 SDK 埋点、ADX 集群查询和成本分析分别使用对应专项能力。$zh239$,
        'microsoft/azure-skills', 'azure-observability', 0, FALSE),
    (283, 'firecrawl', $zh239$Firecrawl 网页搜索与采集$zh239$,
        $zh239$通过 Firecrawl CLI 实时搜索、抓取、爬取并交互操作网页。$zh239$,
        $zh239$用于在线搜索、文章研究、URL 内容提取、文档爬取、站点下载，以及需要点击或登录的页面交互。它可返回完整实时页面内容并处理动态站点；不用于本地文件、Git、部署或代码编辑任务。$zh239$,
        'firecrawl/cli', 'firecrawl', 0, TRUE),
    (284, 'canvas-design', $zh239$原创画布视觉设计$zh239$,
        $zh239$运用设计原则创作高质量的原创海报、艺术品和其他静态 PNG 或 PDF 视觉。$zh239$,
        $zh239$用于制作海报、艺术作品、平面设计和其他静态画面。根据主题建立原创视觉概念、构图、排版和色彩，并输出 .png 或 .pdf；不得复制在世或既有艺术家的具体作品，以避免版权侵害。$zh239$,
        'anthropics/skills', 'canvas-design', 54, FALSE),
    (285, 'vercel-react-view-transitions', $zh239$React View Transition 动画$zh239$,
        $zh239$使用 React View Transition API 实现原生感页面切换、共享元素和组件状态动画。$zh239$,
        $zh239$用于路由切换、共享元素、组件进出、列表重排和前进后退方向动画，覆盖 ViewTransition 组件、addTransitionType、startViewTransition 及 CSS 伪元素，并可集成 Next.js，无需第三方动画库。$zh239$,
        'vercel-labs/agent-skills', 'vercel-react-view-transitions', 0, TRUE),
    (286, 'ad-creative', $zh239$付费广告创意批量生成$zh239$,
        $zh239$为各类付费广告平台批量生成、迭代和扩展标题、正文、描述及完整创意变体。$zh239$,
        $zh239$用于 Google、Facebook、LinkedIn 等平台的广告文案、RSA 标题、静态广告概念、聊天或系统界面拟态广告、hook、创意测试、复盘和动效广告变体。适合规模化生产与迭代；投放策略和定向使用 ads，落地页文案使用 copywriting。$zh239$,
        'coreyhaines31/marketingskills', 'ad-creative', 0, FALSE),
    (287, 'convex-performance-audit', $zh239$Convex 性能审计$zh239$,
        $zh239$审计 Convex 的读取、订阅、写入竞争和函数限制，定位慢功能与放大问题。$zh239$,
        $zh239$用于 Convex 功能缓慢、Insights 异常、OCC 冲突或 read amplification。检查查询读取量、响应式订阅、写热点、冲突重试和函数资源限制，给出可验证的优化优先级。$zh239$,
        'get-convex/agent-skills', 'convex-performance-audit', 0, TRUE),
    (288, 'gsap', $zh239$HyperFrames GSAP 动画参考$zh239$,
        $zh239$提供 HyperFrames 中 GSAP 补间、缓动、交错、时间线和性能优化的实现参考。$zh239$,
        $zh239$用于编写 HyperFrames 的 GSAP 动画，覆盖 gsap.to、from、fromTo、easing、stagger、defaults，以及 timeline 的位置参数、标签、嵌套和播放控制；性能部分包括 transform、will-change 与 quickTo。$zh239$,
        'heygen-com/hyperframes', 'gsap', 0, FALSE),
    (289, 'setup-ts-deep-modules', $zh239$TypeScript 深层模块约束$zh239$,
        $zh239$把 dependency-cruiser 接入 TypeScript 仓库，使包内实现只能经入口文件访问。$zh239$,
        $zh239$仅在用户主动要求时使用。配置 dependency-cruiser，将每个包视为 deep module：实现隐藏在子目录中，外部代码不得绕过公开入口直接导入，从而强化封装边界并通过自动检查防止回退。$zh239$,
        'mattpocock/skills', 'setup-ts-deep-modules', 0, FALSE),
    (290, 'convex-setup-auth', $zh239$Convex 认证与权限配置$zh239$,
        $zh239$为 Convex 应用配置登录、身份映射、用户表、受保护函数和角色访问控制。$zh239$,
        $zh239$用于接入认证提供商、建立用户身份映射、设计 users 表、保护 query 与 mutation，以及实现角色和权限检查。确保服务端依据可信 identity 授权，而不是只依赖客户端状态。$zh239$,
        'get-convex/agent-skills', 'convex-setup-auth', 0, TRUE),
    (291, 'convex-migration-helper', $zh239$Convex 零停机迁移规划$zh239$,
        $zh239$以 widen-migrate-narrow 和 @convex-dev/migrations 规划 Convex 模式与数据迁移。$zh239$,
        $zh239$用于破坏性 schema 变更、数据回填、表结构重塑和零停机发布。先扩宽兼容模式，再分批迁移与验证数据，最后收窄并移除旧路径，同时规划回滚、并发写入和部署顺序。$zh239$,
        'get-convex/agent-skills', 'convex-migration-helper', 0, TRUE),
    (292, 'review', $zh239$代码标准与规格双轴审查$zh239$,
        $zh239$从仓库编码标准和原始规格两个维度并行审查指定基准之后的改动。$zh239$,
        $zh239$用于审查分支、PR、进行中改动或“自某点以来”的变化。以提交、分支、标签或 merge-base 为固定基准，并行检查代码是否遵循仓库文档化标准、是否满足来源 Issue 或规格，最后并列报告两类发现。$zh239$,
        'mattpocock/skills', 'review', 0, FALSE),
    (293, 'review-animations', $zh239$Emil Kowalski 动效审查$zh239$,
        $zh239$依据 Emil Kowalski 的设计工程理念，以高标准审查界面动画与动效代码。$zh239$,
        $zh239$用于评估动画实现的必要性、时序、缓动、连续性、响应反馈、性能和可访问性。默认主动标记问题，只有在动效克制、自然、服务于理解并达到高工艺标准时才予以认可。$zh239$,
        'emilkowalski/skills', 'review-animations', 0, FALSE),
    (294, 'cold-email', $zh239$B2B 冷邮件序列$zh239$,
        $zh239$撰写能获得回复的 B2B 冷启动邮件及多轮跟进序列。$zh239$,
        $zh239$用于冷外联、潜客开发、销售开发和 SDR 邮件。覆盖主题行、开场、正文、行动号召、个性化与多触点跟进，并诊断无人回复的问题；暖线索或生命周期邮件使用 emails，邮件以外的销售材料使用 sales-enablement。$zh239$,
        'coreyhaines31/marketingskills', 'cold-email', 0, FALSE),
    (295, 'website-to-hyperframes', $zh239$网站转 HyperFrames 视频$zh239$,
        $zh239$捕获网站内容，并基于真实页面制作 HyperFrames 宣传、导览或社交视频。$zh239$,
        $zh239$用于用户提供 URL 并希望制作任意网站相关视频，包括站点捕获、宣传片、社交广告和产品导览。即使只粘贴网址也可触发；从网站截图和资产建立 HyperFrames 合成，而不是凭空重画页面。$zh239$,
        'heygen-com/hyperframes', 'website-to-hyperframes', 19, FALSE),
    (296, 'web-artifacts-builder', $zh239$Claude.ai 复杂 Web 组件构建$zh239$,
        $zh239$用 React、Tailwind CSS 和 shadcn/ui 创建包含状态与路由的复杂 claude.ai HTML artifact。$zh239$,
        $zh239$用于需要多个组件、状态管理、路由或 shadcn/ui 的精致交互式 HTML artifact。提供现代前端工具链和结构化构建流程；简单的单文件 HTML 或 JSX 不应引入这套较重方案。$zh239$,
        'anthropics/skills', 'web-artifacts-builder', 1, FALSE),
    (297, 'browser-use', $zh239$CDP 浏览器直接控制$zh239$,
        $zh239$通过 Chrome DevTools Protocol 直接控制浏览器，完成交互、抓取、测试和截图。$zh239$,
        $zh239$用于真实网页和应用的浏览器自动化：导航、点击、输入、提取动态内容、执行测试、捕获截图并观察页面状态。通过 CDP 直接连接浏览器，适合需要实际渲染和交互上下文的任务。$zh239$,
        'browser-use/browser-use', 'browser-use', 0, FALSE),
    (298, 'site-architecture', $zh239$网站信息架构规划$zh239$,
        $zh239$规划或重构网站页面层级、导航、URL、面包屑和内部链接关系。$zh239$,
        $zh239$用于站点地图、页面层级、信息架构、导航设计、URL 结构和内部链接策略，帮助确定需要哪些页面以及它们如何连接。它不生成 XML sitemap；技术 SEO、结构化数据分别使用 seo-audit 和 schema。$zh239$,
        'coreyhaines31/marketingskills', 'site-architecture', 0, FALSE),
    (299, 'firebase-security-rules-auditor', $zh239$Firebase 安全规则审计$zh239$,
        $zh239$审计 Firestore 与 Cloud Storage 规则中的漏洞、越权、绕过、资源耗尽和类型安全问题。$zh239$,
        $zh239$用于审查或红队评估 Firebase 安全规则，并可按审计清单评分。检查权限提升、角色绕过、create 与 update 不一致、资源耗尽、类型与大小限制以及 hasOnly 所有权约束；不处理 CLI、Auth、Crashlytics、Remote Config 或数据库查询。$zh239$,
        'firebase/agent-skills', 'firebase-security-rules-auditor', 0, FALSE),
    (300, 'better-auth-best-practices', $zh239$Better Auth 配置最佳实践$zh239$,
        $zh239$配置 Better Auth 服务端与客户端、数据库适配器、会话、插件和环境变量。$zh239$,
        $zh239$用于 Better Auth、betterauth、auth.ts 或 TypeScript 认证设置。覆盖邮箱密码、OAuth、服务器与客户端初始化、数据库 adapter、session 管理、插件扩展和环境变量，并强调安全默认值和清晰的认证边界。$zh239$,
        'better-auth/skills', 'better-auth-best-practices', 0, TRUE),
    (301, 'wind-mcp-skill', $zh239$Wind 金融数据查询$zh239$,
        $zh239$查询股票、基金、指数、板块、债券、公告、新闻、宏观、汇率和行业金融数据。$zh239$,
        $zh239$用于 A 股、港股、美股的筛选、行情、K 线、财务、股东、事件、技术和风险；基金、ETF、LOF 的筛选、净值、规模、持仓和业绩；以及指数、板块、债券、公告、财经新闻、宏观、汇率和行业指标。不用于台股、日股、韩股、欧股、期货盘口、加密货币或非金融数据。$zh239$,
        'wind-information-co-ltd/wind-skills', 'wind-mcp-skill', 0, TRUE),
    (302, 'firebase-ai-logic-basics', $zh239$Firebase AI Logic 集成$zh239$,
        $zh239$在 Web 应用中集成 Firebase AI Logic 与 Gemini API，覆盖多模态、结构化输出和安全。$zh239$,
        $zh239$用于官方 Firebase AI Logic 接入。完成 Web 应用配置与 SDK 初始化，调用 Gemini API 进行文本或多模态推理，定义结构化输出，并配置保护客户端调用所需的安全与配额措施。$zh239$,
        'firebase/agent-skills', 'firebase-ai-logic-basics', 0, FALSE),
    (303, 'sales-enablement', $zh239$销售赋能材料制作$zh239$,
        $zh239$创建销售演示、单页资料、异议处理、ROI 分析、演示脚本和销售手册。$zh239$,
        $zh239$用于任何帮助销售团队推进和成交的文档或资产，包括 pitch deck、one-pager、leave-behind、异议话术、交易级 ROI、demo script、talk track、playbook、提案模板和买家画像卡。竞品战卡、网站文案、冷邮件和优惠设计使用对应能力。$zh239$,
        'coreyhaines31/marketingskills', 'sales-enablement', 0, FALSE),
    (304, 'churn-prevention', $zh239$订阅流失预防$zh239$,
        $zh239$设计取消流程、挽留优惠、失败支付追回和用户留存策略，降低主动与被动流失。$zh239$,
        $zh239$用于流失率过高、取消与 offboarding、save offer、dunning、失败支付恢复、win-back、暂停订阅和退出调查。建立识别风险、干预、衡量和迭代的留存系统；取消后的邮件召回和应用内升级付费墙使用相应能力。$zh239$,
        'coreyhaines31/marketingskills', 'churn-prevention', 0, FALSE),
    (305, 'firebase-firestore', $zh239$Cloud Firestore 开发$zh239$,
        $zh239$创建、管理、查询并配置 Firestore 数据库，包括建模、规则、索引和多平台 SDK。$zh239$,
        $zh239$用于 Standard 或 Enterprise 版 Cloud Firestore，覆盖数据库创建与列举、数据模型、索引、安全规则，以及 Web、Python、iOS、Android 和 Flutter SDK 查询集成。不用于 Hosting、Data Connect、Auth、Storage、Crashlytics、Functions 或 BigQuery。$zh239$,
        'firebase/agent-skills', 'firebase-firestore', 0, FALSE),
    (306, 'polish', $zh239$界面上线前精修$zh239$,
        $zh239$在发布前修正对齐、间距、一致性和微观细节，让界面从良好提升到完成态。$zh239$,
        $zh239$用于最后润色、上线前检查或用户感觉“哪里不对”时。系统检查像素级对齐、间距节奏、组件一致性、状态细节和视觉收口，修复小而累积的质量问题，不在收尾阶段无故改变核心设计。$zh239$,
        'pbakaus/impeccable', 'polish', 0, FALSE),
    (307, 'browser-act-skill-forge', $zh239$browser-act 可复用 Skill 锻造$zh239$,
        $zh239$通过 browser-act 探索网站内部接口，并固化为无需重复侦察的可复用 Skill 包。$zh239$,
        $zh239$用于为任意网站创建 SKILL.md 与脚本、理解内部 API、复现既有抓取工具或批量采集数十至数千条记录。一次探索后沉淀可重复、去重且可规模化的流程，适合长期自动化和监控；一次性浏览操作直接使用 browser-act。$zh239$,
        'browser-act/skills', 'browser-act-skill-forge', 0, FALSE),
    (308, 'revops', $zh239$营收运营流程设计$zh239$,
        $zh239$优化线索生命周期、评分路由、营销销售交接、CRM 自动化和收入管线管理。$zh239$,
        $zh239$用于 RevOps、MQL 与 SQL 定义、lead scoring、lead routing、pipeline stages、deal desk、数据卫生和营销到销售交接。设计连接营销活动与收入结果的系统和责任边界；冷邮件、滴灌邮件和定价分别使用对应能力。$zh239$,
        'coreyhaines31/marketingskills', 'revops', 0, FALSE),
    (309, 'firebase-crashlytics', $zh239$Firebase Crashlytics 集成$zh239$,
        $zh239$配置 Firebase Crashlytics，并在应用中接入 SDK、崩溃上报和诊断流程。$zh239$,
        $zh239$用于预配和使用 Firebase Crashlytics。指导平台侧启用、客户端 SDK 安装、符号与版本配置、测试崩溃、非致命错误记录和崩溃数据查看，帮助应用建立可靠的线上问题观测。$zh239$,
        'firebase/agent-skills', 'firebase-crashlytics', 0, FALSE),
    (310, 'critique', $zh239$UX 设计量化批评$zh239$,
        $zh239$从层级、架构、情感、认知负担和整体质量评估设计，并给出量化与可执行反馈。$zh239$,
        $zh239$用于审查、批评或评价界面与组件。结合视觉层级、信息架构、情感共鸣、认知负担、persona 测试和自动反模式检测进行评分，明确问题影响与改进建议，而非只表达主观喜好。$zh239$,
        'pbakaus/impeccable', 'critique', 0, FALSE),
    (311, 'xcode-project-setup', $zh239$Xcode 项目依赖配置$zh239$,
        $zh239$安全修改 Xcode .pbxproj，添加 Swift Package 并正确链接项目文件。$zh239$,
        $zh239$用于 iOS 项目需要安装 Firebase、Alamofire 等依赖或链接新文件时。以最小且可验证的方式修改 .pbxproj，维护 target、build phase 和 package reference 的一致性，避免手工编辑破坏工程。$zh239$,
        'firebase/agent-skills', 'xcode-project-setup', 0, FALSE),
    (312, 'audit', $zh239$前端技术质量审计$zh239$,
        $zh239$审计可访问性、性能、主题、响应式和反模式，生成 P0 至 P3 的评分报告与行动计划。$zh239$,
        $zh239$用于可访问性检查、性能审计或综合技术质量评估。系统检查键盘和语义、加载与渲染、主题兼容、断点和常见 UI 反模式，以 P0 至 P3 标注严重度、量化得分并给出可执行修复顺序。$zh239$,
        'pbakaus/impeccable', 'audit', 0, FALSE),
    (313, 'animate', $zh239$界面动效增强$zh239$,
        $zh239$为现有功能加入有目的的动画、微交互和过渡，提升可用性与愉悦感。$zh239$,
        $zh239$用于添加动画、transition、hover、micro-interaction 或让界面更有生命力。先理解用户任务和状态变化，再选择能解释因果、提供反馈和引导注意的动效，同时控制性能、可访问性和 reduced-motion。$zh239$,
        'pbakaus/impeccable', 'animate', 0, FALSE),
    (314, 'adapt', $zh239$跨设备响应式适配$zh239$,
        $zh239$让设计在不同屏幕、设备、情境和平台上可靠工作，并实现断点、流式布局与触控目标。$zh239$,
        $zh239$用于响应式、移动布局、断点、视口适配和跨设备兼容。分析内容优先级与交互约束，实施 fluid layout、合理 breakpoints、可触达 touch target 和平台差异处理，而非简单缩小桌面界面。$zh239$,
        'pbakaus/impeccable', 'adapt', 0, FALSE),
    (315, 'clarify', $zh239$UX 文案澄清$zh239$,
        $zh239$改写含糊的界面文案、错误信息、微文案、标签和说明，使操作更易理解。$zh239$,
        $zh239$用于令人困惑的文字、标签、错误消息或流程指引。以用户语言明确发生了什么、为何发生、可采取什么行动，统一术语并压缩认知成本，同时保持语气与产品情境一致。$zh239$,
        'pbakaus/impeccable', 'clarify', 0, FALSE),
    (316, 'neon-postgres', $zh239$Neon Lakebase Postgres 指南$zh239$,
        $zh239$提供 Neon 背后的 Lakebase Postgres 设置、连接、分支、伸缩、恢复和复制最佳实践。$zh239$,
        $zh239$用于 Lakebase Postgres、Neon 项目、DATABASE_URL、serverless Postgres、Neon CLI、MCP 或 Auth。覆盖 pooled 与 direct 连接、驱动、分支、schema 迁移、自动伸缩、scale-to-zero、即时恢复、只读副本、连接池、IP 白名单和逻辑复制。$zh239$,
        'neondatabase/agent-skills', 'neon-postgres', 0, FALSE),
    (317, 'optimize', $zh239$前端性能优化$zh239$,
        $zh239$诊断并修复界面在加载、渲染、动画、图像和包体积方面的性能问题。$zh239$,
        $zh239$用于页面缓慢、卡顿、掉帧、加载时间过长或 bundle 过大。测量真实瓶颈，优化资源与图片、渲染路径、组件更新、动画和代码拆分，并用前后对比验证体验确实更快更顺滑。$zh239$,
        'pbakaus/impeccable', 'optimize', 0, FALSE),
    (318, 'colorize', $zh239$界面战略配色$zh239$,
        $zh239$为过于单色、灰暗或缺乏视觉兴趣的界面加入有策略的色彩。$zh239$,
        $zh239$用于设计显得灰、乏味、缺少温度或需要更鲜明表达时。根据品牌、语义、层级和可访问性建立受控色彩角色，在关键区域增加吸引力与情绪，同时避免无目的的彩虹化。$zh239$,
        'pbakaus/impeccable', 'colorize', 0, FALSE),
    (319, 'google-agents-cli-adk-code', $zh239$Google ADK 代理代码参考$zh239$,
        $zh239$提供 Google ADK Python 的代理类型、工具、编排、回调、状态管理和代码示例。$zh239$,
        $zh239$用于编写 ADK 代理代码、添加工具、创建 callback、定义 agent 或使用状态管理。它是 Google ADK Skill 套件的 API 快速参考，包含常用模式与可研读配方；项目脚手架和部署分别使用对应专项能力。$zh239$,
        'google/agents-cli', 'google-agents-cli-adk-code', 0, FALSE),
    (320, 'bolder', $zh239$界面视觉强化$zh239$,
        $zh239$放大过于安全或平淡的设计影响力，在保持可用性的同时增加个性与刺激度。$zh239$,
        $zh239$用于界面看起来模板化、无聊、过于保守或缺乏角色时。通过更鲜明的层级、尺度、构图、色彩和节奏提升视觉冲击，但保留内容清晰、交互可预测与可访问性。$zh239$,
        'pbakaus/impeccable', 'bolder', 0, FALSE),
    (321, 'delight', $zh239$界面惊喜感设计$zh239$,
        $zh239$为功能界面加入愉悦、个性和意外细节，使产品更难忘且更好用。$zh239$,
        $zh239$用于增加 polish、personality、微交互、动画或趣味。寻找与用户目标和品牌一致的惊喜时刻，通过反馈、文案、动效和小彩蛋提升情感体验，避免妨碍任务或重复使用后变得烦扰。$zh239$,
        'pbakaus/impeccable', 'delight', 0, FALSE),
    (322, 'lead-magnets', $zh239$获客磁铁策划$zh239$,
        $zh239$规划、创建或优化用于邮件采集和线索生成的门控内容与可下载资源。$zh239$,
        $zh239$用于电子书、速查表、清单、模板、Notion 或表格资源、PDF 下载和资源库等 lead magnet。确定受众痛点、价值承诺、内容形式、分发和转化路径；互动工具、实际文案和获取后的邮件序列使用相应能力。$zh239$,
        'coreyhaines31/marketingskills', 'lead-magnets', 0, FALSE),
    (323, 'google-agents-cli-workflow', $zh239$Google ADK 全生命周期工作流$zh239$,
        $zh239$指导 ADK 代理从脚手架、开发、测试和评估到部署、发布、监控的完整生命周期。$zh239$,
        $zh239$用于开发、运行、调试、测试、部署、发布或监控 Google ADK 代理。作为套件入口提供 scaffold、build、evaluate、deploy、publish、observe 全流程、代码保护规则、模型选择和故障排查，并把具体操作路由到相应专项能力。$zh239$,
        'google/agents-cli', 'google-agents-cli-workflow', 0, FALSE),
    (324, 'google-agents-cli-eval', $zh239$Google ADK 评估方法$zh239$,
        $zh239$设计并运行 ADK 代理评估，分析失败、比较结果并使用 Quality Flywheel 持续优化。$zh239$,
        $zh239$用于运行评估、编写 eval dataset、分析失败、比较结果或优化代理。覆盖 Agent Platform 评估方法、指标、数据集 schema、LLM-as-judge 评分和常见失败原因；API 代码、部署和脚手架使用对应能力。$zh239$,
        'google/agents-cli', 'google-agents-cli-eval', 0, FALSE),
    (325, 'google-agents-cli-scaffold', $zh239$Google ADK 项目脚手架$zh239$,
        $zh239$创建、增强或升级 Google ADK 代理项目，并配置模板、CI/CD 与部署目标。$zh239$,
        $zh239$用于新建 ADK 项目、增加 CI/CD 或部署能力、增强与升级现有项目。覆盖 agents-cli scaffold create、enhance、upgrade、模板选项、部署目标和原型优先流程；代理业务代码和实际部署操作使用对应能力。$zh239$,
        'google/agents-cli', 'google-agents-cli-scaffold', 0, FALSE),
    (326, 'google-agents-cli-deploy', $zh239$Google ADK 部署运维$zh239$,
        $zh239$把 ADK 代理部署到 Agent Runtime、Cloud Run 或 GKE，并处理 CI/CD、密钥与回滚。$zh239$,
        $zh239$用于部署 ADK 代理、配置 CI/CD 和 secrets、排查部署问题，以及选择 Agent Runtime、Cloud Run、GKE 或了解 Agent Gateway。覆盖服务账号、生产基础设施、发布流程和回滚；API、评估和脚手架使用对应能力。$zh239$,
        'google/agents-cli', 'google-agents-cli-deploy', 0, FALSE),
    (327, 'google-agents-cli-observability', $zh239$Google ADK 可观测性$zh239$,
        $zh239$为已部署 ADK 代理配置追踪、日志、分析和第三方观测集成。$zh239$,
        $zh239$用于 Cloud Trace、prompt-response logging、BigQuery Agent Analytics、生产流量调试，以及 AgentOps、Phoenix、MLflow 等第三方集成。提供监控和排障指导；部署设置和 ADK API 代码使用对应专项能力。$zh239$,
        'google/agents-cli', 'google-agents-cli-observability', 0, FALSE),
    (328, 'google-agents-cli-publish', $zh239$Google ADK 发布与注册$zh239$,
        $zh239$把 ADK 代理发布到 Gemini Enterprise，并在 Agent Registry 中管理注册实例。$zh239$,
        $zh239$用于 agents-cli publish gemini-enterprise，以及列举、更新和删除 Agent Registry 中的代理。覆盖 ADK 与 A2A 注册模式、交互式和程序化用法、参数、部署元数据自动检测和故障排查；实际部署使用 deploy 专项能力。$zh239$,
        'google/agents-cli', 'google-agents-cli-publish', 0, FALSE),
    (329, 'distill', $zh239$界面极简提炼$zh239$,
        $zh239$删除不必要的复杂度和视觉噪声，把设计提炼为简单、清晰且有力量的核心。$zh239$,
        $zh239$用于简化、去杂、减少元素或让界面更聚焦。识别重复容器、装饰、层级和交互，保留支持用户目标的必要部分，通过更少但更强的结构提升清晰度，而不是机械追求空白。$zh239$,
        'pbakaus/impeccable', 'distill', 0, FALSE),
    (330, 'animation-vocabulary', $zh239$Web 动效术语反查$zh239$,
        $zh239$把对 Web 动画或运动效果的模糊描述反查为准确的专业术语。$zh239$,
        $zh239$用于用户描述某种动效却不知道名称，或询问“这种效果叫什么”。例如将弹层打开时的弹跳识别为 Pop in，将 iOS 橡皮筋滚动识别为 Rubber-banding，便于向 AI 或设计师准确表达；只负责命名，不负责设计或实现。$zh239$,
        'emilkowalski/skills', 'animation-vocabulary', 0, FALSE),
    (331, 'vercel-cli-with-tokens', $zh239$Vercel Token CLI 管理$zh239$,
        $zh239$使用访问令牌而非交互登录，通过 Vercel CLI 部署和管理项目。$zh239$,
        $zh239$用于自动化环境中的 Vercel 部署、项目设置和环境变量管理。配置并安全传递 access token，选择正确团队与项目，执行 CLI 命令并验证结果，避免依赖浏览器交互式登录。$zh239$,
        'vercel-labs/agent-skills', 'vercel-cli-with-tokens', 0, TRUE),
    (332, 'quieter', $zh239$界面视觉降噪$zh239$,
        $zh239$降低过于激进、嘈杂或刺激的设计强度，同时保留品质和表达。$zh239$,
        $zh239$用于界面太大胆、太响亮、压迫、花哨或希望更平静精致时。收敛色彩、对比、尺度、装饰与动效，恢复清晰层级和呼吸感，但不把设计削弱成无个性的默认样式。$zh239$,
        'pbakaus/impeccable', 'quieter', 0, FALSE),
    (333, 'firecrawl-search', $zh239$Firecrawl 全文网页搜索$zh239$,
        $zh239$执行实时 Web 搜索，并可返回搜索结果对应页面的完整 Markdown 内容。$zh239$,
        $zh239$用于搜索网页、查找文章、研究主题、查询近期新闻、发现来源或了解公众讨论。返回真实搜索结果，并可选择提取完整页面而非仅给摘要片段，适合需要引用和深入阅读的在线研究。$zh239$,
        'firecrawl/cli', 'firecrawl-search', 0, TRUE),
    (334, 'firecrawl-scrape', $zh239$Firecrawl 动态网页抓取$zh239$,
        $zh239$从任意 URL 提取干净 Markdown，包括 JavaScript 渲染的单页应用。$zh239$,
        $zh239$用于用户提供 URL 并要求抓取、读取或提取页面内容。支持 JavaScript 渲染、多个 URL 并发和面向 LLM 优化的 Markdown 输出；网页内容提取时优先于简单 WebFetch。$zh239$,
        'firecrawl/cli', 'firecrawl-scrape', 0, TRUE)
)
INSERT INTO skill_catalog_localizations (
    slug,
    locale,
    display_name,
    summary,
    description
)
SELECT
    slug,
    'zh-CN',
    display_name,
    summary,
    capability
        || E'\n\n'
        || format(
            $zh239$来源说明：本条目来自 skills.sh 历史总榜第 %s 名快照；原始来源：%s；原始 slug：%s；打包时排除了 %s 个上游文件。$zh239$,
            rank,
            source,
            original_slug,
            excluded_count
        )
        || CASE
            WHEN license_unverified THEN
                $zh239$许可证状态：此快照未包含许可证文件；版权归原作者所有，使用须遵循来源仓库的许可证。$zh239$
            ELSE
                $zh239$许可证状态：以随包附带或原始来源中的许可证为准；版权归原作者所有，使用与再分发须遵循该许可证。$zh239$
        END
FROM localized
ON CONFLICT (slug, locale) DO UPDATE
SET
    display_name = EXCLUDED.display_name,
    summary = EXCLUDED.summary,
    description = EXCLUDED.description,
    updated_at = NOW();
