// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/desktopdevice"
	"github.com/Wei-Shaw/sub2api/ent/desktopdevicesession"
)

// DesktopDeviceSession is the model entity for the DesktopDeviceSession schema.
type DesktopDeviceSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID int64 `json:"device_id,omitempty"`
	// FamilyID holds the value of the "family_id" field.
	FamilyID string `json:"family_id,omitempty"`
	// RefreshTokenHash holds the value of the "refresh_token_hash" field.
	RefreshTokenHash string `json:"refresh_token_hash,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt *time.Time `json:"consumed_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DesktopDeviceSessionQuery when eager-loading is set.
	Edges        DesktopDeviceSessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DesktopDeviceSessionEdges holds the relations/edges for other nodes in the graph.
type DesktopDeviceSessionEdges struct {
	// Device holds the value of the device edge.
	Device *DesktopDevice `json:"device,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DesktopDeviceSessionEdges) DeviceOrErr() (*DesktopDevice, error) {
	if e.Device != nil {
		return e.Device, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: desktopdevice.Label}
	}
	return nil, &NotLoadedError{edge: "device"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DesktopDeviceSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case desktopdevicesession.FieldID, desktopdevicesession.FieldDeviceID:
			values[i] = new(sql.NullInt64)
		case desktopdevicesession.FieldFamilyID, desktopdevicesession.FieldRefreshTokenHash, desktopdevicesession.FieldStatus:
			values[i] = new(sql.NullString)
		case desktopdevicesession.FieldCreatedAt, desktopdevicesession.FieldUpdatedAt, desktopdevicesession.FieldExpiresAt, desktopdevicesession.FieldConsumedAt, desktopdevicesession.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DesktopDeviceSession fields.
func (_m *DesktopDeviceSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case desktopdevicesession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case desktopdevicesession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case desktopdevicesession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case desktopdevicesession.FieldDeviceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.Int64
			}
		case desktopdevicesession.FieldFamilyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field family_id", values[i])
			} else if value.Valid {
				_m.FamilyID = value.String
			}
		case desktopdevicesession.FieldRefreshTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token_hash", values[i])
			} else if value.Valid {
				_m.RefreshTokenHash = value.String
			}
		case desktopdevicesession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case desktopdevicesession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case desktopdevicesession.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		case desktopdevicesession.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DesktopDeviceSession.
// This includes values selected through modifiers, order, etc.
func (_m *DesktopDeviceSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDevice queries the "device" edge of the DesktopDeviceSession entity.
func (_m *DesktopDeviceSession) QueryDevice() *DesktopDeviceQuery {
	return NewDesktopDeviceSessionClient(_m.config).QueryDevice(_m)
}

// Update returns a builder for updating this DesktopDeviceSession.
// Note that you need to call DesktopDeviceSession.Unwrap() before calling this method if this DesktopDeviceSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DesktopDeviceSession) Update() *DesktopDeviceSessionUpdateOne {
	return NewDesktopDeviceSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DesktopDeviceSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DesktopDeviceSession) Unwrap() *DesktopDeviceSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DesktopDeviceSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DesktopDeviceSession) String() string {
	var builder strings.Builder
	builder.WriteString("DesktopDeviceSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeviceID))
	builder.WriteString(", ")
	builder.WriteString("family_id=")
	builder.WriteString(_m.FamilyID)
	builder.WriteString(", ")
	builder.WriteString("refresh_token_hash=")
	builder.WriteString(_m.RefreshTokenHash)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// DesktopDeviceSessions is a parsable slice of DesktopDeviceSession.
type DesktopDeviceSessions []*DesktopDeviceSession
