// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopdevice"
	"github.com/Wei-Shaw/sub2api/ent/desktopdevicesession"
)

// DesktopDeviceSessionCreate is the builder for creating a DesktopDeviceSession entity.
type DesktopDeviceSessionCreate struct {
	config
	mutation *DesktopDeviceSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DesktopDeviceSessionCreate) SetCreatedAt(v time.Time) *DesktopDeviceSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DesktopDeviceSessionCreate) SetNillableCreatedAt(v *time.Time) *DesktopDeviceSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DesktopDeviceSessionCreate) SetUpdatedAt(v time.Time) *DesktopDeviceSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DesktopDeviceSessionCreate) SetNillableUpdatedAt(v *time.Time) *DesktopDeviceSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *DesktopDeviceSessionCreate) SetDeviceID(v int64) *DesktopDeviceSessionCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetFamilyID sets the "family_id" field.
func (_c *DesktopDeviceSessionCreate) SetFamilyID(v string) *DesktopDeviceSessionCreate {
	_c.mutation.SetFamilyID(v)
	return _c
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (_c *DesktopDeviceSessionCreate) SetRefreshTokenHash(v string) *DesktopDeviceSessionCreate {
	_c.mutation.SetRefreshTokenHash(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DesktopDeviceSessionCreate) SetStatus(v string) *DesktopDeviceSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DesktopDeviceSessionCreate) SetNillableStatus(v *string) *DesktopDeviceSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *DesktopDeviceSessionCreate) SetExpiresAt(v time.Time) *DesktopDeviceSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *DesktopDeviceSessionCreate) SetConsumedAt(v time.Time) *DesktopDeviceSessionCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *DesktopDeviceSessionCreate) SetNillableConsumedAt(v *time.Time) *DesktopDeviceSessionCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *DesktopDeviceSessionCreate) SetRevokedAt(v time.Time) *DesktopDeviceSessionCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *DesktopDeviceSessionCreate) SetNillableRevokedAt(v *time.Time) *DesktopDeviceSessionCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetDevice sets the "device" edge to the DesktopDevice entity.
func (_c *DesktopDeviceSessionCreate) SetDevice(v *DesktopDevice) *DesktopDeviceSessionCreate {
	return _c.SetDeviceID(v.ID)
}

// Mutation returns the DesktopDeviceSessionMutation object of the builder.
func (_c *DesktopDeviceSessionCreate) Mutation() *DesktopDeviceSessionMutation {
	return _c.mutation
}

// Save creates the DesktopDeviceSession in the database.
func (_c *DesktopDeviceSessionCreate) Save(ctx context.Context) (*DesktopDeviceSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DesktopDeviceSessionCreate) SaveX(ctx context.Context) *DesktopDeviceSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopDeviceSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopDeviceSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DesktopDeviceSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := desktopdevicesession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := desktopdevicesession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := desktopdevicesession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DesktopDeviceSessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DesktopDeviceSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DesktopDeviceSession.updated_at"`)}
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "DesktopDeviceSession.device_id"`)}
	}
	if _, ok := _c.mutation.FamilyID(); !ok {
		return &ValidationError{Name: "family_id", err: errors.New(`ent: missing required field "DesktopDeviceSession.family_id"`)}
	}
	if _, ok := _c.mutation.RefreshTokenHash(); !ok {
		return &ValidationError{Name: "refresh_token_hash", err: errors.New(`ent: missing required field "DesktopDeviceSession.refresh_token_hash"`)}
	}
	if v, ok := _c.mutation.RefreshTokenHash(); ok {
		if err := desktopdevicesession.RefreshTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token_hash", err: fmt.Errorf(`ent: validator failed for field "DesktopDeviceSession.refresh_token_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DesktopDeviceSession.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := desktopdevicesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopDeviceSession.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "DesktopDeviceSession.expires_at"`)}
	}
	if len(_c.mutation.DeviceIDs()) == 0 {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required edge "DesktopDeviceSession.device"`)}
	}
	return nil
}

func (_c *DesktopDeviceSessionCreate) sqlSave(ctx context.Context) (*DesktopDeviceSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DesktopDeviceSessionCreate) createSpec() (*DesktopDeviceSession, *sqlgraph.CreateSpec) {
	var (
		_node = &DesktopDeviceSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(desktopdevicesession.Table, sqlgraph.NewFieldSpec(desktopdevicesession.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(desktopdevicesession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopdevicesession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.FamilyID(); ok {
		_spec.SetField(desktopdevicesession.FieldFamilyID, field.TypeString, value)
		_node.FamilyID = value
	}
	if value, ok := _c.mutation.RefreshTokenHash(); ok {
		_spec.SetField(desktopdevicesession.FieldRefreshTokenHash, field.TypeString, value)
		_node.RefreshTokenHash = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(desktopdevicesession.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(desktopdevicesession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(desktopdevicesession.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(desktopdevicesession.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if nodes := _c.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdevicesession.DeviceTable,
			Columns: []string{desktopdevicesession.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeviceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopDeviceSession.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopDeviceSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopDeviceSessionCreate) OnConflict(opts ...sql.ConflictOption) *DesktopDeviceSessionUpsertOne {
	_c.conflict = opts
	return &DesktopDeviceSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopDeviceSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopDeviceSessionCreate) OnConflictColumns(columns ...string) *DesktopDeviceSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopDeviceSessionUpsertOne{
		create: _c,
	}
}

type (
	// DesktopDeviceSessionUpsertOne is the builder for "upsert"-ing
	//  one DesktopDeviceSession node.
	DesktopDeviceSessionUpsertOne struct {
		create *DesktopDeviceSessionCreate
	}

	// DesktopDeviceSessionUpsert is the "OnConflict" setter.
	DesktopDeviceSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopDeviceSessionUpsert) SetUpdatedAt(v time.Time) *DesktopDeviceSessionUpsert {
	u.Set(desktopdevicesession.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsert) UpdateUpdatedAt() *DesktopDeviceSessionUpsert {
	u.SetExcluded(desktopdevicesession.FieldUpdatedAt)
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *DesktopDeviceSessionUpsert) SetDeviceID(v int64) *DesktopDeviceSessionUpsert {
	u.Set(desktopdevicesession.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsert) UpdateDeviceID() *DesktopDeviceSessionUpsert {
	u.SetExcluded(desktopdevicesession.FieldDeviceID)
	return u
}

// SetFamilyID sets the "family_id" field.
func (u *DesktopDeviceSessionUpsert) SetFamilyID(v string) *DesktopDeviceSessionUpsert {
	u.Set(desktopdevicesession.FieldFamilyID, v)
	return u
}

// UpdateFamilyID sets the "family_id" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsert) UpdateFamilyID() *DesktopDeviceSessionUpsert {
	u.SetExcluded(desktopdevicesession.FieldFamilyID)
	return u
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (u *DesktopDeviceSessionUpsert) SetRefreshTokenHash(v string) *DesktopDeviceSessionUpsert {
	u.Set(desktopdevicesession.FieldRefreshTokenHash, v)
	return u
}

// UpdateRefreshTokenHash sets the "refresh_token_hash" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsert) UpdateRefreshTokenHash() *DesktopDeviceSessionUpsert {
	u.SetExcluded(desktopdevicesession.FieldRefreshTokenHash)
	return u
}

// SetStatus sets the "status" field.
func (u *DesktopDeviceSessionUpsert) SetStatus(v string) *DesktopDeviceSessionUpsert {
	u.Set(desktopdevicesession.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsert) UpdateStatus() *DesktopDeviceSessionUpsert {
	u.SetExcluded(desktopdevicesession.FieldStatus)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *DesktopDeviceSessionUpsert) SetExpiresAt(v time.Time) *DesktopDeviceSessionUpsert {
	u.Set(desktopdevicesession.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsert) UpdateExpiresAt() *DesktopDeviceSessionUpsert {
	u.SetExcluded(desktopdevicesession.FieldExpiresAt)
	return u
}

// SetConsumedAt sets the "consumed_at" field.
func (u *DesktopDeviceSessionUpsert) SetConsumedAt(v time.Time) *DesktopDeviceSessionUpsert {
	u.Set(desktopdevicesession.FieldConsumedAt, v)
	return u
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsert) UpdateConsumedAt() *DesktopDeviceSessionUpsert {
	u.SetExcluded(desktopdevicesession.FieldConsumedAt)
	return u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *DesktopDeviceSessionUpsert) ClearConsumedAt() *DesktopDeviceSessionUpsert {
	u.SetNull(desktopdevicesession.FieldConsumedAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *DesktopDeviceSessionUpsert) SetRevokedAt(v time.Time) *DesktopDeviceSessionUpsert {
	u.Set(desktopdevicesession.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsert) UpdateRevokedAt() *DesktopDeviceSessionUpsert {
	u.SetExcluded(desktopdevicesession.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *DesktopDeviceSessionUpsert) ClearRevokedAt() *DesktopDeviceSessionUpsert {
	u.SetNull(desktopdevicesession.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DesktopDeviceSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopDeviceSessionUpsertOne) UpdateNewValues() *DesktopDeviceSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(desktopdevicesession.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopDeviceSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DesktopDeviceSessionUpsertOne) Ignore() *DesktopDeviceSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopDeviceSessionUpsertOne) DoNothing() *DesktopDeviceSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopDeviceSessionCreate.OnConflict
// documentation for more info.
func (u *DesktopDeviceSessionUpsertOne) Update(set func(*DesktopDeviceSessionUpsert)) *DesktopDeviceSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopDeviceSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopDeviceSessionUpsertOne) SetUpdatedAt(v time.Time) *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertOne) UpdateUpdatedAt() *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *DesktopDeviceSessionUpsertOne) SetDeviceID(v int64) *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertOne) UpdateDeviceID() *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateDeviceID()
	})
}

// SetFamilyID sets the "family_id" field.
func (u *DesktopDeviceSessionUpsertOne) SetFamilyID(v string) *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetFamilyID(v)
	})
}

// UpdateFamilyID sets the "family_id" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertOne) UpdateFamilyID() *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateFamilyID()
	})
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (u *DesktopDeviceSessionUpsertOne) SetRefreshTokenHash(v string) *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetRefreshTokenHash(v)
	})
}

// UpdateRefreshTokenHash sets the "refresh_token_hash" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertOne) UpdateRefreshTokenHash() *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateRefreshTokenHash()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopDeviceSessionUpsertOne) SetStatus(v string) *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertOne) UpdateStatus() *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DesktopDeviceSessionUpsertOne) SetExpiresAt(v time.Time) *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertOne) UpdateExpiresAt() *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *DesktopDeviceSessionUpsertOne) SetConsumedAt(v time.Time) *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertOne) UpdateConsumedAt() *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *DesktopDeviceSessionUpsertOne) ClearConsumedAt() *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.ClearConsumedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *DesktopDeviceSessionUpsertOne) SetRevokedAt(v time.Time) *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertOne) UpdateRevokedAt() *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *DesktopDeviceSessionUpsertOne) ClearRevokedAt() *DesktopDeviceSessionUpsertOne {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *DesktopDeviceSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopDeviceSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopDeviceSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DesktopDeviceSessionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DesktopDeviceSessionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DesktopDeviceSessionCreateBulk is the builder for creating many DesktopDeviceSession entities in bulk.
type DesktopDeviceSessionCreateBulk struct {
	config
	err      error
	builders []*DesktopDeviceSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the DesktopDeviceSession entities in the database.
func (_c *DesktopDeviceSessionCreateBulk) Save(ctx context.Context) ([]*DesktopDeviceSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DesktopDeviceSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DesktopDeviceSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DesktopDeviceSessionCreateBulk) SaveX(ctx context.Context) []*DesktopDeviceSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopDeviceSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopDeviceSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopDeviceSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopDeviceSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopDeviceSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *DesktopDeviceSessionUpsertBulk {
	_c.conflict = opts
	return &DesktopDeviceSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopDeviceSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopDeviceSessionCreateBulk) OnConflictColumns(columns ...string) *DesktopDeviceSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopDeviceSessionUpsertBulk{
		create: _c,
	}
}

// DesktopDeviceSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of DesktopDeviceSession nodes.
type DesktopDeviceSessionUpsertBulk struct {
	create *DesktopDeviceSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DesktopDeviceSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopDeviceSessionUpsertBulk) UpdateNewValues() *DesktopDeviceSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(desktopdevicesession.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopDeviceSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DesktopDeviceSessionUpsertBulk) Ignore() *DesktopDeviceSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopDeviceSessionUpsertBulk) DoNothing() *DesktopDeviceSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopDeviceSessionCreateBulk.OnConflict
// documentation for more info.
func (u *DesktopDeviceSessionUpsertBulk) Update(set func(*DesktopDeviceSessionUpsert)) *DesktopDeviceSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopDeviceSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopDeviceSessionUpsertBulk) SetUpdatedAt(v time.Time) *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertBulk) UpdateUpdatedAt() *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *DesktopDeviceSessionUpsertBulk) SetDeviceID(v int64) *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertBulk) UpdateDeviceID() *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateDeviceID()
	})
}

// SetFamilyID sets the "family_id" field.
func (u *DesktopDeviceSessionUpsertBulk) SetFamilyID(v string) *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetFamilyID(v)
	})
}

// UpdateFamilyID sets the "family_id" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertBulk) UpdateFamilyID() *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateFamilyID()
	})
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (u *DesktopDeviceSessionUpsertBulk) SetRefreshTokenHash(v string) *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetRefreshTokenHash(v)
	})
}

// UpdateRefreshTokenHash sets the "refresh_token_hash" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertBulk) UpdateRefreshTokenHash() *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateRefreshTokenHash()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopDeviceSessionUpsertBulk) SetStatus(v string) *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertBulk) UpdateStatus() *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DesktopDeviceSessionUpsertBulk) SetExpiresAt(v time.Time) *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertBulk) UpdateExpiresAt() *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetConsumedAt sets the "consumed_at" field.
func (u *DesktopDeviceSessionUpsertBulk) SetConsumedAt(v time.Time) *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetConsumedAt(v)
	})
}

// UpdateConsumedAt sets the "consumed_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertBulk) UpdateConsumedAt() *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateConsumedAt()
	})
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (u *DesktopDeviceSessionUpsertBulk) ClearConsumedAt() *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.ClearConsumedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *DesktopDeviceSessionUpsertBulk) SetRevokedAt(v time.Time) *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *DesktopDeviceSessionUpsertBulk) UpdateRevokedAt() *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *DesktopDeviceSessionUpsertBulk) ClearRevokedAt() *DesktopDeviceSessionUpsertBulk {
	return u.Update(func(s *DesktopDeviceSessionUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *DesktopDeviceSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DesktopDeviceSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopDeviceSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopDeviceSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
