// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopdiagnostic"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DesktopDiagnosticDelete is the builder for deleting a DesktopDiagnostic entity.
type DesktopDiagnosticDelete struct {
	config
	hooks    []Hook
	mutation *DesktopDiagnosticMutation
}

// Where appends a list predicates to the DesktopDiagnosticDelete builder.
func (_d *DesktopDiagnosticDelete) Where(ps ...predicate.DesktopDiagnostic) *DesktopDiagnosticDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DesktopDiagnosticDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DesktopDiagnosticDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DesktopDiagnosticDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(desktopdiagnostic.Table, sqlgraph.NewFieldSpec(desktopdiagnostic.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DesktopDiagnosticDeleteOne is the builder for deleting a single DesktopDiagnostic entity.
type DesktopDiagnosticDeleteOne struct {
	_d *DesktopDiagnosticDelete
}

// Where appends a list predicates to the DesktopDiagnosticDelete builder.
func (_d *DesktopDiagnosticDeleteOne) Where(ps ...predicate.DesktopDiagnostic) *DesktopDiagnosticDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DesktopDiagnosticDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{desktopdiagnostic.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DesktopDiagnosticDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
