// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopdevice"
	"github.com/Wei-Shaw/sub2api/ent/desktopdevicesession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DesktopDeviceSessionUpdate is the builder for updating DesktopDeviceSession entities.
type DesktopDeviceSessionUpdate struct {
	config
	hooks    []Hook
	mutation *DesktopDeviceSessionMutation
}

// Where appends a list predicates to the DesktopDeviceSessionUpdate builder.
func (_u *DesktopDeviceSessionUpdate) Where(ps ...predicate.DesktopDeviceSession) *DesktopDeviceSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopDeviceSessionUpdate) SetUpdatedAt(v time.Time) *DesktopDeviceSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DesktopDeviceSessionUpdate) SetDeviceID(v int64) *DesktopDeviceSessionUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdate) SetNillableDeviceID(v *int64) *DesktopDeviceSessionUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetFamilyID sets the "family_id" field.
func (_u *DesktopDeviceSessionUpdate) SetFamilyID(v string) *DesktopDeviceSessionUpdate {
	_u.mutation.SetFamilyID(v)
	return _u
}

// SetNillableFamilyID sets the "family_id" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdate) SetNillableFamilyID(v *string) *DesktopDeviceSessionUpdate {
	if v != nil {
		_u.SetFamilyID(*v)
	}
	return _u
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (_u *DesktopDeviceSessionUpdate) SetRefreshTokenHash(v string) *DesktopDeviceSessionUpdate {
	_u.mutation.SetRefreshTokenHash(v)
	return _u
}

// SetNillableRefreshTokenHash sets the "refresh_token_hash" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdate) SetNillableRefreshTokenHash(v *string) *DesktopDeviceSessionUpdate {
	if v != nil {
		_u.SetRefreshTokenHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopDeviceSessionUpdate) SetStatus(v string) *DesktopDeviceSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdate) SetNillableStatus(v *string) *DesktopDeviceSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DesktopDeviceSessionUpdate) SetExpiresAt(v time.Time) *DesktopDeviceSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdate) SetNillableExpiresAt(v *time.Time) *DesktopDeviceSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *DesktopDeviceSessionUpdate) SetConsumedAt(v time.Time) *DesktopDeviceSessionUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdate) SetNillableConsumedAt(v *time.Time) *DesktopDeviceSessionUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *DesktopDeviceSessionUpdate) ClearConsumedAt() *DesktopDeviceSessionUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DesktopDeviceSessionUpdate) SetRevokedAt(v time.Time) *DesktopDeviceSessionUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdate) SetNillableRevokedAt(v *time.Time) *DesktopDeviceSessionUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DesktopDeviceSessionUpdate) ClearRevokedAt() *DesktopDeviceSessionUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetDevice sets the "device" edge to the DesktopDevice entity.
func (_u *DesktopDeviceSessionUpdate) SetDevice(v *DesktopDevice) *DesktopDeviceSessionUpdate {
	return _u.SetDeviceID(v.ID)
}

// Mutation returns the DesktopDeviceSessionMutation object of the builder.
func (_u *DesktopDeviceSessionUpdate) Mutation() *DesktopDeviceSessionMutation {
	return _u.mutation
}

// ClearDevice clears the "device" edge to the DesktopDevice entity.
func (_u *DesktopDeviceSessionUpdate) ClearDevice() *DesktopDeviceSessionUpdate {
	_u.mutation.ClearDevice()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DesktopDeviceSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopDeviceSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DesktopDeviceSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopDeviceSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopDeviceSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktopdevicesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopDeviceSessionUpdate) check() error {
	if v, ok := _u.mutation.RefreshTokenHash(); ok {
		if err := desktopdevicesession.RefreshTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token_hash", err: fmt.Errorf(`ent: validator failed for field "DesktopDeviceSession.refresh_token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := desktopdevicesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopDeviceSession.status": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopDeviceSession.device"`)
	}
	return nil
}

func (_u *DesktopDeviceSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopdevicesession.Table, desktopdevicesession.Columns, sqlgraph.NewFieldSpec(desktopdevicesession.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopdevicesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FamilyID(); ok {
		_spec.SetField(desktopdevicesession.FieldFamilyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshTokenHash(); ok {
		_spec.SetField(desktopdevicesession.FieldRefreshTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktopdevicesession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(desktopdevicesession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(desktopdevicesession.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(desktopdevicesession.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(desktopdevicesession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(desktopdevicesession.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdevicesession.DeviceTable,
			Columns: []string{desktopdevicesession.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdevicesession.DeviceTable,
			Columns: []string{desktopdevicesession.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopdevicesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DesktopDeviceSessionUpdateOne is the builder for updating a single DesktopDeviceSession entity.
type DesktopDeviceSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DesktopDeviceSessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopDeviceSessionUpdateOne) SetUpdatedAt(v time.Time) *DesktopDeviceSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DesktopDeviceSessionUpdateOne) SetDeviceID(v int64) *DesktopDeviceSessionUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdateOne) SetNillableDeviceID(v *int64) *DesktopDeviceSessionUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetFamilyID sets the "family_id" field.
func (_u *DesktopDeviceSessionUpdateOne) SetFamilyID(v string) *DesktopDeviceSessionUpdateOne {
	_u.mutation.SetFamilyID(v)
	return _u
}

// SetNillableFamilyID sets the "family_id" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdateOne) SetNillableFamilyID(v *string) *DesktopDeviceSessionUpdateOne {
	if v != nil {
		_u.SetFamilyID(*v)
	}
	return _u
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (_u *DesktopDeviceSessionUpdateOne) SetRefreshTokenHash(v string) *DesktopDeviceSessionUpdateOne {
	_u.mutation.SetRefreshTokenHash(v)
	return _u
}

// SetNillableRefreshTokenHash sets the "refresh_token_hash" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdateOne) SetNillableRefreshTokenHash(v *string) *DesktopDeviceSessionUpdateOne {
	if v != nil {
		_u.SetRefreshTokenHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopDeviceSessionUpdateOne) SetStatus(v string) *DesktopDeviceSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdateOne) SetNillableStatus(v *string) *DesktopDeviceSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DesktopDeviceSessionUpdateOne) SetExpiresAt(v time.Time) *DesktopDeviceSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *DesktopDeviceSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *DesktopDeviceSessionUpdateOne) SetConsumedAt(v time.Time) *DesktopDeviceSessionUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdateOne) SetNillableConsumedAt(v *time.Time) *DesktopDeviceSessionUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *DesktopDeviceSessionUpdateOne) ClearConsumedAt() *DesktopDeviceSessionUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DesktopDeviceSessionUpdateOne) SetRevokedAt(v time.Time) *DesktopDeviceSessionUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DesktopDeviceSessionUpdateOne) SetNillableRevokedAt(v *time.Time) *DesktopDeviceSessionUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DesktopDeviceSessionUpdateOne) ClearRevokedAt() *DesktopDeviceSessionUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetDevice sets the "device" edge to the DesktopDevice entity.
func (_u *DesktopDeviceSessionUpdateOne) SetDevice(v *DesktopDevice) *DesktopDeviceSessionUpdateOne {
	return _u.SetDeviceID(v.ID)
}

// Mutation returns the DesktopDeviceSessionMutation object of the builder.
func (_u *DesktopDeviceSessionUpdateOne) Mutation() *DesktopDeviceSessionMutation {
	return _u.mutation
}

// ClearDevice clears the "device" edge to the DesktopDevice entity.
func (_u *DesktopDeviceSessionUpdateOne) ClearDevice() *DesktopDeviceSessionUpdateOne {
	_u.mutation.ClearDevice()
	return _u
}

// Where appends a list predicates to the DesktopDeviceSessionUpdate builder.
func (_u *DesktopDeviceSessionUpdateOne) Where(ps ...predicate.DesktopDeviceSession) *DesktopDeviceSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DesktopDeviceSessionUpdateOne) Select(field string, fields ...string) *DesktopDeviceSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DesktopDeviceSession entity.
func (_u *DesktopDeviceSessionUpdateOne) Save(ctx context.Context) (*DesktopDeviceSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopDeviceSessionUpdateOne) SaveX(ctx context.Context) *DesktopDeviceSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DesktopDeviceSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopDeviceSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopDeviceSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktopdevicesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopDeviceSessionUpdateOne) check() error {
	if v, ok := _u.mutation.RefreshTokenHash(); ok {
		if err := desktopdevicesession.RefreshTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token_hash", err: fmt.Errorf(`ent: validator failed for field "DesktopDeviceSession.refresh_token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := desktopdevicesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopDeviceSession.status": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopDeviceSession.device"`)
	}
	return nil
}

func (_u *DesktopDeviceSessionUpdateOne) sqlSave(ctx context.Context) (_node *DesktopDeviceSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopdevicesession.Table, desktopdevicesession.Columns, sqlgraph.NewFieldSpec(desktopdevicesession.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DesktopDeviceSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktopdevicesession.FieldID)
		for _, f := range fields {
			if !desktopdevicesession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != desktopdevicesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopdevicesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FamilyID(); ok {
		_spec.SetField(desktopdevicesession.FieldFamilyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshTokenHash(); ok {
		_spec.SetField(desktopdevicesession.FieldRefreshTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktopdevicesession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(desktopdevicesession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(desktopdevicesession.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(desktopdevicesession.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(desktopdevicesession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(desktopdevicesession.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdevicesession.DeviceTable,
			Columns: []string{desktopdevicesession.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdevicesession.DeviceTable,
			Columns: []string{desktopdevicesession.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DesktopDeviceSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopdevicesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
