// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopdevice"
	"github.com/Wei-Shaw/sub2api/ent/desktopdiagnostic"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DesktopDiagnosticUpdate is the builder for updating DesktopDiagnostic entities.
type DesktopDiagnosticUpdate struct {
	config
	hooks    []Hook
	mutation *DesktopDiagnosticMutation
}

// Where appends a list predicates to the DesktopDiagnosticUpdate builder.
func (_u *DesktopDiagnosticUpdate) Where(ps ...predicate.DesktopDiagnostic) *DesktopDiagnosticUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopDiagnosticUpdate) SetUpdatedAt(v time.Time) *DesktopDiagnosticUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DesktopDiagnosticUpdate) SetDeviceID(v int64) *DesktopDiagnosticUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillableDeviceID(v *int64) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DesktopDiagnosticUpdate) SetUserID(v int64) *DesktopDiagnosticUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillableUserID(v *int64) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *DesktopDiagnosticUpdate) SetPublicID(v string) *DesktopDiagnosticUpdate {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillablePublicID(v *string) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *DesktopDiagnosticUpdate) SetAppVersion(v string) *DesktopDiagnosticUpdate {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillableAppVersion(v *string) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *DesktopDiagnosticUpdate) SetPlatform(v string) *DesktopDiagnosticUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillablePlatform(v *string) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetArchitecture sets the "architecture" field.
func (_u *DesktopDiagnosticUpdate) SetArchitecture(v string) *DesktopDiagnosticUpdate {
	_u.mutation.SetArchitecture(v)
	return _u
}

// SetNillableArchitecture sets the "architecture" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillableArchitecture(v *string) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetArchitecture(*v)
	}
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *DesktopDiagnosticUpdate) SetOsVersion(v string) *DesktopDiagnosticUpdate {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillableOsVersion(v *string) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// SetGatewayStatus sets the "gateway_status" field.
func (_u *DesktopDiagnosticUpdate) SetGatewayStatus(v string) *DesktopDiagnosticUpdate {
	_u.mutation.SetGatewayStatus(v)
	return _u
}

// SetNillableGatewayStatus sets the "gateway_status" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillableGatewayStatus(v *string) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetGatewayStatus(*v)
	}
	return _u
}

// SetCodexConfigStatus sets the "codex_config_status" field.
func (_u *DesktopDiagnosticUpdate) SetCodexConfigStatus(v string) *DesktopDiagnosticUpdate {
	_u.mutation.SetCodexConfigStatus(v)
	return _u
}

// SetNillableCodexConfigStatus sets the "codex_config_status" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillableCodexConfigStatus(v *string) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetCodexConfigStatus(*v)
	}
	return _u
}

// SetRequestSampleCount sets the "request_sample_count" field.
func (_u *DesktopDiagnosticUpdate) SetRequestSampleCount(v int) *DesktopDiagnosticUpdate {
	_u.mutation.ResetRequestSampleCount()
	_u.mutation.SetRequestSampleCount(v)
	return _u
}

// SetNillableRequestSampleCount sets the "request_sample_count" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillableRequestSampleCount(v *int) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetRequestSampleCount(*v)
	}
	return _u
}

// AddRequestSampleCount adds value to the "request_sample_count" field.
func (_u *DesktopDiagnosticUpdate) AddRequestSampleCount(v int) *DesktopDiagnosticUpdate {
	_u.mutation.AddRequestSampleCount(v)
	return _u
}

// SetRequestErrorCount sets the "request_error_count" field.
func (_u *DesktopDiagnosticUpdate) SetRequestErrorCount(v int) *DesktopDiagnosticUpdate {
	_u.mutation.ResetRequestErrorCount()
	_u.mutation.SetRequestErrorCount(v)
	return _u
}

// SetNillableRequestErrorCount sets the "request_error_count" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillableRequestErrorCount(v *int) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetRequestErrorCount(*v)
	}
	return _u
}

// AddRequestErrorCount adds value to the "request_error_count" field.
func (_u *DesktopDiagnosticUpdate) AddRequestErrorCount(v int) *DesktopDiagnosticUpdate {
	_u.mutation.AddRequestErrorCount(v)
	return _u
}

// SetEncryptedPayload sets the "encrypted_payload" field.
func (_u *DesktopDiagnosticUpdate) SetEncryptedPayload(v string) *DesktopDiagnosticUpdate {
	_u.mutation.SetEncryptedPayload(v)
	return _u
}

// SetNillableEncryptedPayload sets the "encrypted_payload" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillableEncryptedPayload(v *string) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetEncryptedPayload(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DesktopDiagnosticUpdate) SetExpiresAt(v time.Time) *DesktopDiagnosticUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdate) SetNillableExpiresAt(v *time.Time) *DesktopDiagnosticUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetDevice sets the "device" edge to the DesktopDevice entity.
func (_u *DesktopDiagnosticUpdate) SetDevice(v *DesktopDevice) *DesktopDiagnosticUpdate {
	return _u.SetDeviceID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *DesktopDiagnosticUpdate) SetUser(v *User) *DesktopDiagnosticUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the DesktopDiagnosticMutation object of the builder.
func (_u *DesktopDiagnosticUpdate) Mutation() *DesktopDiagnosticMutation {
	return _u.mutation
}

// ClearDevice clears the "device" edge to the DesktopDevice entity.
func (_u *DesktopDiagnosticUpdate) ClearDevice() *DesktopDiagnosticUpdate {
	_u.mutation.ClearDevice()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DesktopDiagnosticUpdate) ClearUser() *DesktopDiagnosticUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DesktopDiagnosticUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopDiagnosticUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DesktopDiagnosticUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopDiagnosticUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopDiagnosticUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktopdiagnostic.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopDiagnosticUpdate) check() error {
	if v, ok := _u.mutation.AppVersion(); ok {
		if err := desktopdiagnostic.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.app_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := desktopdiagnostic.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Architecture(); ok {
		if err := desktopdiagnostic.ArchitectureValidator(v); err != nil {
			return &ValidationError{Name: "architecture", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.architecture": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OsVersion(); ok {
		if err := desktopdiagnostic.OsVersionValidator(v); err != nil {
			return &ValidationError{Name: "os_version", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.os_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GatewayStatus(); ok {
		if err := desktopdiagnostic.GatewayStatusValidator(v); err != nil {
			return &ValidationError{Name: "gateway_status", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.gateway_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodexConfigStatus(); ok {
		if err := desktopdiagnostic.CodexConfigStatusValidator(v); err != nil {
			return &ValidationError{Name: "codex_config_status", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.codex_config_status": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopDiagnostic.device"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopDiagnostic.user"`)
	}
	return nil
}

func (_u *DesktopDiagnosticUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopdiagnostic.Table, desktopdiagnostic.Columns, sqlgraph.NewFieldSpec(desktopdiagnostic.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopdiagnostic.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(desktopdiagnostic.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(desktopdiagnostic.FieldAppVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(desktopdiagnostic.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Architecture(); ok {
		_spec.SetField(desktopdiagnostic.FieldArchitecture, field.TypeString, value)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(desktopdiagnostic.FieldOsVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayStatus(); ok {
		_spec.SetField(desktopdiagnostic.FieldGatewayStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodexConfigStatus(); ok {
		_spec.SetField(desktopdiagnostic.FieldCodexConfigStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestSampleCount(); ok {
		_spec.SetField(desktopdiagnostic.FieldRequestSampleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestSampleCount(); ok {
		_spec.AddField(desktopdiagnostic.FieldRequestSampleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestErrorCount(); ok {
		_spec.SetField(desktopdiagnostic.FieldRequestErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestErrorCount(); ok {
		_spec.AddField(desktopdiagnostic.FieldRequestErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EncryptedPayload(); ok {
		_spec.SetField(desktopdiagnostic.FieldEncryptedPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(desktopdiagnostic.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdiagnostic.DeviceTable,
			Columns: []string{desktopdiagnostic.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdiagnostic.DeviceTable,
			Columns: []string{desktopdiagnostic.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdiagnostic.UserTable,
			Columns: []string{desktopdiagnostic.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdiagnostic.UserTable,
			Columns: []string{desktopdiagnostic.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopdiagnostic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DesktopDiagnosticUpdateOne is the builder for updating a single DesktopDiagnostic entity.
type DesktopDiagnosticUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DesktopDiagnosticMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopDiagnosticUpdateOne) SetUpdatedAt(v time.Time) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DesktopDiagnosticUpdateOne) SetDeviceID(v int64) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillableDeviceID(v *int64) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DesktopDiagnosticUpdateOne) SetUserID(v int64) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillableUserID(v *int64) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *DesktopDiagnosticUpdateOne) SetPublicID(v string) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillablePublicID(v *string) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *DesktopDiagnosticUpdateOne) SetAppVersion(v string) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillableAppVersion(v *string) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *DesktopDiagnosticUpdateOne) SetPlatform(v string) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillablePlatform(v *string) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetArchitecture sets the "architecture" field.
func (_u *DesktopDiagnosticUpdateOne) SetArchitecture(v string) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetArchitecture(v)
	return _u
}

// SetNillableArchitecture sets the "architecture" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillableArchitecture(v *string) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetArchitecture(*v)
	}
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *DesktopDiagnosticUpdateOne) SetOsVersion(v string) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillableOsVersion(v *string) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// SetGatewayStatus sets the "gateway_status" field.
func (_u *DesktopDiagnosticUpdateOne) SetGatewayStatus(v string) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetGatewayStatus(v)
	return _u
}

// SetNillableGatewayStatus sets the "gateway_status" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillableGatewayStatus(v *string) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetGatewayStatus(*v)
	}
	return _u
}

// SetCodexConfigStatus sets the "codex_config_status" field.
func (_u *DesktopDiagnosticUpdateOne) SetCodexConfigStatus(v string) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetCodexConfigStatus(v)
	return _u
}

// SetNillableCodexConfigStatus sets the "codex_config_status" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillableCodexConfigStatus(v *string) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetCodexConfigStatus(*v)
	}
	return _u
}

// SetRequestSampleCount sets the "request_sample_count" field.
func (_u *DesktopDiagnosticUpdateOne) SetRequestSampleCount(v int) *DesktopDiagnosticUpdateOne {
	_u.mutation.ResetRequestSampleCount()
	_u.mutation.SetRequestSampleCount(v)
	return _u
}

// SetNillableRequestSampleCount sets the "request_sample_count" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillableRequestSampleCount(v *int) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetRequestSampleCount(*v)
	}
	return _u
}

// AddRequestSampleCount adds value to the "request_sample_count" field.
func (_u *DesktopDiagnosticUpdateOne) AddRequestSampleCount(v int) *DesktopDiagnosticUpdateOne {
	_u.mutation.AddRequestSampleCount(v)
	return _u
}

// SetRequestErrorCount sets the "request_error_count" field.
func (_u *DesktopDiagnosticUpdateOne) SetRequestErrorCount(v int) *DesktopDiagnosticUpdateOne {
	_u.mutation.ResetRequestErrorCount()
	_u.mutation.SetRequestErrorCount(v)
	return _u
}

// SetNillableRequestErrorCount sets the "request_error_count" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillableRequestErrorCount(v *int) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetRequestErrorCount(*v)
	}
	return _u
}

// AddRequestErrorCount adds value to the "request_error_count" field.
func (_u *DesktopDiagnosticUpdateOne) AddRequestErrorCount(v int) *DesktopDiagnosticUpdateOne {
	_u.mutation.AddRequestErrorCount(v)
	return _u
}

// SetEncryptedPayload sets the "encrypted_payload" field.
func (_u *DesktopDiagnosticUpdateOne) SetEncryptedPayload(v string) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetEncryptedPayload(v)
	return _u
}

// SetNillableEncryptedPayload sets the "encrypted_payload" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillableEncryptedPayload(v *string) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetEncryptedPayload(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DesktopDiagnosticUpdateOne) SetExpiresAt(v time.Time) *DesktopDiagnosticUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DesktopDiagnosticUpdateOne) SetNillableExpiresAt(v *time.Time) *DesktopDiagnosticUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetDevice sets the "device" edge to the DesktopDevice entity.
func (_u *DesktopDiagnosticUpdateOne) SetDevice(v *DesktopDevice) *DesktopDiagnosticUpdateOne {
	return _u.SetDeviceID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *DesktopDiagnosticUpdateOne) SetUser(v *User) *DesktopDiagnosticUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the DesktopDiagnosticMutation object of the builder.
func (_u *DesktopDiagnosticUpdateOne) Mutation() *DesktopDiagnosticMutation {
	return _u.mutation
}

// ClearDevice clears the "device" edge to the DesktopDevice entity.
func (_u *DesktopDiagnosticUpdateOne) ClearDevice() *DesktopDiagnosticUpdateOne {
	_u.mutation.ClearDevice()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DesktopDiagnosticUpdateOne) ClearUser() *DesktopDiagnosticUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the DesktopDiagnosticUpdate builder.
func (_u *DesktopDiagnosticUpdateOne) Where(ps ...predicate.DesktopDiagnostic) *DesktopDiagnosticUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DesktopDiagnosticUpdateOne) Select(field string, fields ...string) *DesktopDiagnosticUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DesktopDiagnostic entity.
func (_u *DesktopDiagnosticUpdateOne) Save(ctx context.Context) (*DesktopDiagnostic, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopDiagnosticUpdateOne) SaveX(ctx context.Context) *DesktopDiagnostic {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DesktopDiagnosticUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopDiagnosticUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopDiagnosticUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktopdiagnostic.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopDiagnosticUpdateOne) check() error {
	if v, ok := _u.mutation.AppVersion(); ok {
		if err := desktopdiagnostic.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.app_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := desktopdiagnostic.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Architecture(); ok {
		if err := desktopdiagnostic.ArchitectureValidator(v); err != nil {
			return &ValidationError{Name: "architecture", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.architecture": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OsVersion(); ok {
		if err := desktopdiagnostic.OsVersionValidator(v); err != nil {
			return &ValidationError{Name: "os_version", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.os_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GatewayStatus(); ok {
		if err := desktopdiagnostic.GatewayStatusValidator(v); err != nil {
			return &ValidationError{Name: "gateway_status", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.gateway_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodexConfigStatus(); ok {
		if err := desktopdiagnostic.CodexConfigStatusValidator(v); err != nil {
			return &ValidationError{Name: "codex_config_status", err: fmt.Errorf(`ent: validator failed for field "DesktopDiagnostic.codex_config_status": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopDiagnostic.device"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopDiagnostic.user"`)
	}
	return nil
}

func (_u *DesktopDiagnosticUpdateOne) sqlSave(ctx context.Context) (_node *DesktopDiagnostic, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopdiagnostic.Table, desktopdiagnostic.Columns, sqlgraph.NewFieldSpec(desktopdiagnostic.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DesktopDiagnostic.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktopdiagnostic.FieldID)
		for _, f := range fields {
			if !desktopdiagnostic.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != desktopdiagnostic.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopdiagnostic.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(desktopdiagnostic.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(desktopdiagnostic.FieldAppVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(desktopdiagnostic.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Architecture(); ok {
		_spec.SetField(desktopdiagnostic.FieldArchitecture, field.TypeString, value)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(desktopdiagnostic.FieldOsVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.GatewayStatus(); ok {
		_spec.SetField(desktopdiagnostic.FieldGatewayStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodexConfigStatus(); ok {
		_spec.SetField(desktopdiagnostic.FieldCodexConfigStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestSampleCount(); ok {
		_spec.SetField(desktopdiagnostic.FieldRequestSampleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestSampleCount(); ok {
		_spec.AddField(desktopdiagnostic.FieldRequestSampleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestErrorCount(); ok {
		_spec.SetField(desktopdiagnostic.FieldRequestErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestErrorCount(); ok {
		_spec.AddField(desktopdiagnostic.FieldRequestErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EncryptedPayload(); ok {
		_spec.SetField(desktopdiagnostic.FieldEncryptedPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(desktopdiagnostic.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdiagnostic.DeviceTable,
			Columns: []string{desktopdiagnostic.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdiagnostic.DeviceTable,
			Columns: []string{desktopdiagnostic.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdiagnostic.UserTable,
			Columns: []string{desktopdiagnostic.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdiagnostic.UserTable,
			Columns: []string{desktopdiagnostic.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DesktopDiagnostic{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopdiagnostic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
