// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/desktopdevice"
	"github.com/Wei-Shaw/sub2api/ent/desktopdevicesession"
	"github.com/Wei-Shaw/sub2api/ent/desktopdiagnostic"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DesktopDeviceUpdate is the builder for updating DesktopDevice entities.
type DesktopDeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DesktopDeviceMutation
}

// Where appends a list predicates to the DesktopDeviceUpdate builder.
func (_u *DesktopDeviceUpdate) Where(ps ...predicate.DesktopDevice) *DesktopDeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopDeviceUpdate) SetUpdatedAt(v time.Time) *DesktopDeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DesktopDeviceUpdate) SetUserID(v int64) *DesktopDeviceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableUserID(v *int64) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *DesktopDeviceUpdate) SetPublicID(v string) *DesktopDeviceUpdate {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillablePublicID(v *string) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (_u *DesktopDeviceUpdate) SetInstallationIDHash(v string) *DesktopDeviceUpdate {
	_u.mutation.SetInstallationIDHash(v)
	return _u
}

// SetNillableInstallationIDHash sets the "installation_id_hash" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableInstallationIDHash(v *string) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetInstallationIDHash(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DesktopDeviceUpdate) SetName(v string) *DesktopDeviceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableName(v *string) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *DesktopDeviceUpdate) SetPlatform(v string) *DesktopDeviceUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillablePlatform(v *string) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetArchitecture sets the "architecture" field.
func (_u *DesktopDeviceUpdate) SetArchitecture(v string) *DesktopDeviceUpdate {
	_u.mutation.SetArchitecture(v)
	return _u
}

// SetNillableArchitecture sets the "architecture" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableArchitecture(v *string) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetArchitecture(*v)
	}
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *DesktopDeviceUpdate) SetOsVersion(v string) *DesktopDeviceUpdate {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableOsVersion(v *string) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *DesktopDeviceUpdate) SetAppVersion(v string) *DesktopDeviceUpdate {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableAppVersion(v *string) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopDeviceUpdate) SetStatus(v string) *DesktopDeviceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableStatus(v *string) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTokenVersion sets the "token_version" field.
func (_u *DesktopDeviceUpdate) SetTokenVersion(v int64) *DesktopDeviceUpdate {
	_u.mutation.ResetTokenVersion()
	_u.mutation.SetTokenVersion(v)
	return _u
}

// SetNillableTokenVersion sets the "token_version" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableTokenVersion(v *int64) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetTokenVersion(*v)
	}
	return _u
}

// AddTokenVersion adds value to the "token_version" field.
func (_u *DesktopDeviceUpdate) AddTokenVersion(v int64) *DesktopDeviceUpdate {
	_u.mutation.AddTokenVersion(v)
	return _u
}

// SetReleaseChannel sets the "release_channel" field.
func (_u *DesktopDeviceUpdate) SetReleaseChannel(v string) *DesktopDeviceUpdate {
	_u.mutation.SetReleaseChannel(v)
	return _u
}

// SetNillableReleaseChannel sets the "release_channel" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableReleaseChannel(v *string) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetReleaseChannel(*v)
	}
	return _u
}

// SetPairingExpiresAt sets the "pairing_expires_at" field.
func (_u *DesktopDeviceUpdate) SetPairingExpiresAt(v time.Time) *DesktopDeviceUpdate {
	_u.mutation.SetPairingExpiresAt(v)
	return _u
}

// SetNillablePairingExpiresAt sets the "pairing_expires_at" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillablePairingExpiresAt(v *time.Time) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetPairingExpiresAt(*v)
	}
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *DesktopDeviceUpdate) SetApprovedAt(v time.Time) *DesktopDeviceUpdate {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableApprovedAt(v *time.Time) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *DesktopDeviceUpdate) ClearApprovedAt() *DesktopDeviceUpdate {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *DesktopDeviceUpdate) SetActivatedAt(v time.Time) *DesktopDeviceUpdate {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableActivatedAt(v *time.Time) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *DesktopDeviceUpdate) ClearActivatedAt() *DesktopDeviceUpdate {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *DesktopDeviceUpdate) SetLastSeenAt(v time.Time) *DesktopDeviceUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableLastSeenAt(v *time.Time) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *DesktopDeviceUpdate) ClearLastSeenAt() *DesktopDeviceUpdate {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DesktopDeviceUpdate) SetRevokedAt(v time.Time) *DesktopDeviceUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DesktopDeviceUpdate) SetNillableRevokedAt(v *time.Time) *DesktopDeviceUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DesktopDeviceUpdate) ClearRevokedAt() *DesktopDeviceUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DesktopDeviceUpdate) SetUser(v *User) *DesktopDeviceUpdate {
	return _u.SetUserID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the DesktopDeviceSession entity by IDs.
func (_u *DesktopDeviceUpdate) AddSessionIDs(ids ...int64) *DesktopDeviceUpdate {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the DesktopDeviceSession entity.
func (_u *DesktopDeviceUpdate) AddSessions(v ...*DesktopDeviceSession) *DesktopDeviceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// AddManagedKeyIDs adds the "managed_keys" edge to the APIKey entity by IDs.
func (_u *DesktopDeviceUpdate) AddManagedKeyIDs(ids ...int64) *DesktopDeviceUpdate {
	_u.mutation.AddManagedKeyIDs(ids...)
	return _u
}

// AddManagedKeys adds the "managed_keys" edges to the APIKey entity.
func (_u *DesktopDeviceUpdate) AddManagedKeys(v ...*APIKey) *DesktopDeviceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedKeyIDs(ids...)
}

// AddDiagnosticIDs adds the "diagnostics" edge to the DesktopDiagnostic entity by IDs.
func (_u *DesktopDeviceUpdate) AddDiagnosticIDs(ids ...int64) *DesktopDeviceUpdate {
	_u.mutation.AddDiagnosticIDs(ids...)
	return _u
}

// AddDiagnostics adds the "diagnostics" edges to the DesktopDiagnostic entity.
func (_u *DesktopDeviceUpdate) AddDiagnostics(v ...*DesktopDiagnostic) *DesktopDeviceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDiagnosticIDs(ids...)
}

// Mutation returns the DesktopDeviceMutation object of the builder.
func (_u *DesktopDeviceUpdate) Mutation() *DesktopDeviceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DesktopDeviceUpdate) ClearUser() *DesktopDeviceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearSessions clears all "sessions" edges to the DesktopDeviceSession entity.
func (_u *DesktopDeviceUpdate) ClearSessions() *DesktopDeviceUpdate {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to DesktopDeviceSession entities by IDs.
func (_u *DesktopDeviceUpdate) RemoveSessionIDs(ids ...int64) *DesktopDeviceUpdate {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to DesktopDeviceSession entities.
func (_u *DesktopDeviceUpdate) RemoveSessions(v ...*DesktopDeviceSession) *DesktopDeviceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// ClearManagedKeys clears all "managed_keys" edges to the APIKey entity.
func (_u *DesktopDeviceUpdate) ClearManagedKeys() *DesktopDeviceUpdate {
	_u.mutation.ClearManagedKeys()
	return _u
}

// RemoveManagedKeyIDs removes the "managed_keys" edge to APIKey entities by IDs.
func (_u *DesktopDeviceUpdate) RemoveManagedKeyIDs(ids ...int64) *DesktopDeviceUpdate {
	_u.mutation.RemoveManagedKeyIDs(ids...)
	return _u
}

// RemoveManagedKeys removes "managed_keys" edges to APIKey entities.
func (_u *DesktopDeviceUpdate) RemoveManagedKeys(v ...*APIKey) *DesktopDeviceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedKeyIDs(ids...)
}

// ClearDiagnostics clears all "diagnostics" edges to the DesktopDiagnostic entity.
func (_u *DesktopDeviceUpdate) ClearDiagnostics() *DesktopDeviceUpdate {
	_u.mutation.ClearDiagnostics()
	return _u
}

// RemoveDiagnosticIDs removes the "diagnostics" edge to DesktopDiagnostic entities by IDs.
func (_u *DesktopDeviceUpdate) RemoveDiagnosticIDs(ids ...int64) *DesktopDeviceUpdate {
	_u.mutation.RemoveDiagnosticIDs(ids...)
	return _u
}

// RemoveDiagnostics removes "diagnostics" edges to DesktopDiagnostic entities.
func (_u *DesktopDeviceUpdate) RemoveDiagnostics(v ...*DesktopDiagnostic) *DesktopDeviceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDiagnosticIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DesktopDeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopDeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DesktopDeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopDeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopDeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktopdevice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopDeviceUpdate) check() error {
	if v, ok := _u.mutation.InstallationIDHash(); ok {
		if err := desktopdevice.InstallationIDHashValidator(v); err != nil {
			return &ValidationError{Name: "installation_id_hash", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.installation_id_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := desktopdevice.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := desktopdevice.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Architecture(); ok {
		if err := desktopdevice.ArchitectureValidator(v); err != nil {
			return &ValidationError{Name: "architecture", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.architecture": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OsVersion(); ok {
		if err := desktopdevice.OsVersionValidator(v); err != nil {
			return &ValidationError{Name: "os_version", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.os_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppVersion(); ok {
		if err := desktopdevice.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.app_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := desktopdevice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReleaseChannel(); ok {
		if err := desktopdevice.ReleaseChannelValidator(v); err != nil {
			return &ValidationError{Name: "release_channel", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.release_channel": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopDevice.user"`)
	}
	return nil
}

func (_u *DesktopDeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopdevice.Table, desktopdevice.Columns, sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopdevice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(desktopdevice.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstallationIDHash(); ok {
		_spec.SetField(desktopdevice.FieldInstallationIDHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(desktopdevice.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(desktopdevice.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Architecture(); ok {
		_spec.SetField(desktopdevice.FieldArchitecture, field.TypeString, value)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(desktopdevice.FieldOsVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(desktopdevice.FieldAppVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktopdevice.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenVersion(); ok {
		_spec.SetField(desktopdevice.FieldTokenVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokenVersion(); ok {
		_spec.AddField(desktopdevice.FieldTokenVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReleaseChannel(); ok {
		_spec.SetField(desktopdevice.FieldReleaseChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PairingExpiresAt(); ok {
		_spec.SetField(desktopdevice.FieldPairingExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(desktopdevice.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(desktopdevice.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(desktopdevice.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(desktopdevice.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(desktopdevice.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(desktopdevice.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(desktopdevice.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(desktopdevice.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdevice.UserTable,
			Columns: []string{desktopdevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdevice.UserTable,
			Columns: []string{desktopdevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.SessionsTable,
			Columns: []string{desktopdevice.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevicesession.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.SessionsTable,
			Columns: []string{desktopdevice.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevicesession.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.SessionsTable,
			Columns: []string{desktopdevice.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevicesession.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagedKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.ManagedKeysTable,
			Columns: []string{desktopdevice.ManagedKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedKeysIDs(); len(nodes) > 0 && !_u.mutation.ManagedKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.ManagedKeysTable,
			Columns: []string{desktopdevice.ManagedKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.ManagedKeysTable,
			Columns: []string{desktopdevice.ManagedKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DiagnosticsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.DiagnosticsTable,
			Columns: []string{desktopdevice.DiagnosticsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdiagnostic.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDiagnosticsIDs(); len(nodes) > 0 && !_u.mutation.DiagnosticsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.DiagnosticsTable,
			Columns: []string{desktopdevice.DiagnosticsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdiagnostic.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiagnosticsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.DiagnosticsTable,
			Columns: []string{desktopdevice.DiagnosticsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdiagnostic.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopdevice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DesktopDeviceUpdateOne is the builder for updating a single DesktopDevice entity.
type DesktopDeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DesktopDeviceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopDeviceUpdateOne) SetUpdatedAt(v time.Time) *DesktopDeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DesktopDeviceUpdateOne) SetUserID(v int64) *DesktopDeviceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableUserID(v *int64) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *DesktopDeviceUpdateOne) SetPublicID(v string) *DesktopDeviceUpdateOne {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillablePublicID(v *string) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetInstallationIDHash sets the "installation_id_hash" field.
func (_u *DesktopDeviceUpdateOne) SetInstallationIDHash(v string) *DesktopDeviceUpdateOne {
	_u.mutation.SetInstallationIDHash(v)
	return _u
}

// SetNillableInstallationIDHash sets the "installation_id_hash" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableInstallationIDHash(v *string) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetInstallationIDHash(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DesktopDeviceUpdateOne) SetName(v string) *DesktopDeviceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableName(v *string) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *DesktopDeviceUpdateOne) SetPlatform(v string) *DesktopDeviceUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillablePlatform(v *string) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetArchitecture sets the "architecture" field.
func (_u *DesktopDeviceUpdateOne) SetArchitecture(v string) *DesktopDeviceUpdateOne {
	_u.mutation.SetArchitecture(v)
	return _u
}

// SetNillableArchitecture sets the "architecture" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableArchitecture(v *string) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetArchitecture(*v)
	}
	return _u
}

// SetOsVersion sets the "os_version" field.
func (_u *DesktopDeviceUpdateOne) SetOsVersion(v string) *DesktopDeviceUpdateOne {
	_u.mutation.SetOsVersion(v)
	return _u
}

// SetNillableOsVersion sets the "os_version" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableOsVersion(v *string) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetOsVersion(*v)
	}
	return _u
}

// SetAppVersion sets the "app_version" field.
func (_u *DesktopDeviceUpdateOne) SetAppVersion(v string) *DesktopDeviceUpdateOne {
	_u.mutation.SetAppVersion(v)
	return _u
}

// SetNillableAppVersion sets the "app_version" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableAppVersion(v *string) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetAppVersion(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopDeviceUpdateOne) SetStatus(v string) *DesktopDeviceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableStatus(v *string) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTokenVersion sets the "token_version" field.
func (_u *DesktopDeviceUpdateOne) SetTokenVersion(v int64) *DesktopDeviceUpdateOne {
	_u.mutation.ResetTokenVersion()
	_u.mutation.SetTokenVersion(v)
	return _u
}

// SetNillableTokenVersion sets the "token_version" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableTokenVersion(v *int64) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetTokenVersion(*v)
	}
	return _u
}

// AddTokenVersion adds value to the "token_version" field.
func (_u *DesktopDeviceUpdateOne) AddTokenVersion(v int64) *DesktopDeviceUpdateOne {
	_u.mutation.AddTokenVersion(v)
	return _u
}

// SetReleaseChannel sets the "release_channel" field.
func (_u *DesktopDeviceUpdateOne) SetReleaseChannel(v string) *DesktopDeviceUpdateOne {
	_u.mutation.SetReleaseChannel(v)
	return _u
}

// SetNillableReleaseChannel sets the "release_channel" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableReleaseChannel(v *string) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetReleaseChannel(*v)
	}
	return _u
}

// SetPairingExpiresAt sets the "pairing_expires_at" field.
func (_u *DesktopDeviceUpdateOne) SetPairingExpiresAt(v time.Time) *DesktopDeviceUpdateOne {
	_u.mutation.SetPairingExpiresAt(v)
	return _u
}

// SetNillablePairingExpiresAt sets the "pairing_expires_at" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillablePairingExpiresAt(v *time.Time) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetPairingExpiresAt(*v)
	}
	return _u
}

// SetApprovedAt sets the "approved_at" field.
func (_u *DesktopDeviceUpdateOne) SetApprovedAt(v time.Time) *DesktopDeviceUpdateOne {
	_u.mutation.SetApprovedAt(v)
	return _u
}

// SetNillableApprovedAt sets the "approved_at" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableApprovedAt(v *time.Time) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetApprovedAt(*v)
	}
	return _u
}

// ClearApprovedAt clears the value of the "approved_at" field.
func (_u *DesktopDeviceUpdateOne) ClearApprovedAt() *DesktopDeviceUpdateOne {
	_u.mutation.ClearApprovedAt()
	return _u
}

// SetActivatedAt sets the "activated_at" field.
func (_u *DesktopDeviceUpdateOne) SetActivatedAt(v time.Time) *DesktopDeviceUpdateOne {
	_u.mutation.SetActivatedAt(v)
	return _u
}

// SetNillableActivatedAt sets the "activated_at" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableActivatedAt(v *time.Time) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetActivatedAt(*v)
	}
	return _u
}

// ClearActivatedAt clears the value of the "activated_at" field.
func (_u *DesktopDeviceUpdateOne) ClearActivatedAt() *DesktopDeviceUpdateOne {
	_u.mutation.ClearActivatedAt()
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *DesktopDeviceUpdateOne) SetLastSeenAt(v time.Time) *DesktopDeviceUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableLastSeenAt(v *time.Time) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// ClearLastSeenAt clears the value of the "last_seen_at" field.
func (_u *DesktopDeviceUpdateOne) ClearLastSeenAt() *DesktopDeviceUpdateOne {
	_u.mutation.ClearLastSeenAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DesktopDeviceUpdateOne) SetRevokedAt(v time.Time) *DesktopDeviceUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DesktopDeviceUpdateOne) SetNillableRevokedAt(v *time.Time) *DesktopDeviceUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DesktopDeviceUpdateOne) ClearRevokedAt() *DesktopDeviceUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *DesktopDeviceUpdateOne) SetUser(v *User) *DesktopDeviceUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddSessionIDs adds the "sessions" edge to the DesktopDeviceSession entity by IDs.
func (_u *DesktopDeviceUpdateOne) AddSessionIDs(ids ...int64) *DesktopDeviceUpdateOne {
	_u.mutation.AddSessionIDs(ids...)
	return _u
}

// AddSessions adds the "sessions" edges to the DesktopDeviceSession entity.
func (_u *DesktopDeviceUpdateOne) AddSessions(v ...*DesktopDeviceSession) *DesktopDeviceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSessionIDs(ids...)
}

// AddManagedKeyIDs adds the "managed_keys" edge to the APIKey entity by IDs.
func (_u *DesktopDeviceUpdateOne) AddManagedKeyIDs(ids ...int64) *DesktopDeviceUpdateOne {
	_u.mutation.AddManagedKeyIDs(ids...)
	return _u
}

// AddManagedKeys adds the "managed_keys" edges to the APIKey entity.
func (_u *DesktopDeviceUpdateOne) AddManagedKeys(v ...*APIKey) *DesktopDeviceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedKeyIDs(ids...)
}

// AddDiagnosticIDs adds the "diagnostics" edge to the DesktopDiagnostic entity by IDs.
func (_u *DesktopDeviceUpdateOne) AddDiagnosticIDs(ids ...int64) *DesktopDeviceUpdateOne {
	_u.mutation.AddDiagnosticIDs(ids...)
	return _u
}

// AddDiagnostics adds the "diagnostics" edges to the DesktopDiagnostic entity.
func (_u *DesktopDeviceUpdateOne) AddDiagnostics(v ...*DesktopDiagnostic) *DesktopDeviceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDiagnosticIDs(ids...)
}

// Mutation returns the DesktopDeviceMutation object of the builder.
func (_u *DesktopDeviceUpdateOne) Mutation() *DesktopDeviceMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *DesktopDeviceUpdateOne) ClearUser() *DesktopDeviceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearSessions clears all "sessions" edges to the DesktopDeviceSession entity.
func (_u *DesktopDeviceUpdateOne) ClearSessions() *DesktopDeviceUpdateOne {
	_u.mutation.ClearSessions()
	return _u
}

// RemoveSessionIDs removes the "sessions" edge to DesktopDeviceSession entities by IDs.
func (_u *DesktopDeviceUpdateOne) RemoveSessionIDs(ids ...int64) *DesktopDeviceUpdateOne {
	_u.mutation.RemoveSessionIDs(ids...)
	return _u
}

// RemoveSessions removes "sessions" edges to DesktopDeviceSession entities.
func (_u *DesktopDeviceUpdateOne) RemoveSessions(v ...*DesktopDeviceSession) *DesktopDeviceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSessionIDs(ids...)
}

// ClearManagedKeys clears all "managed_keys" edges to the APIKey entity.
func (_u *DesktopDeviceUpdateOne) ClearManagedKeys() *DesktopDeviceUpdateOne {
	_u.mutation.ClearManagedKeys()
	return _u
}

// RemoveManagedKeyIDs removes the "managed_keys" edge to APIKey entities by IDs.
func (_u *DesktopDeviceUpdateOne) RemoveManagedKeyIDs(ids ...int64) *DesktopDeviceUpdateOne {
	_u.mutation.RemoveManagedKeyIDs(ids...)
	return _u
}

// RemoveManagedKeys removes "managed_keys" edges to APIKey entities.
func (_u *DesktopDeviceUpdateOne) RemoveManagedKeys(v ...*APIKey) *DesktopDeviceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedKeyIDs(ids...)
}

// ClearDiagnostics clears all "diagnostics" edges to the DesktopDiagnostic entity.
func (_u *DesktopDeviceUpdateOne) ClearDiagnostics() *DesktopDeviceUpdateOne {
	_u.mutation.ClearDiagnostics()
	return _u
}

// RemoveDiagnosticIDs removes the "diagnostics" edge to DesktopDiagnostic entities by IDs.
func (_u *DesktopDeviceUpdateOne) RemoveDiagnosticIDs(ids ...int64) *DesktopDeviceUpdateOne {
	_u.mutation.RemoveDiagnosticIDs(ids...)
	return _u
}

// RemoveDiagnostics removes "diagnostics" edges to DesktopDiagnostic entities.
func (_u *DesktopDeviceUpdateOne) RemoveDiagnostics(v ...*DesktopDiagnostic) *DesktopDeviceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDiagnosticIDs(ids...)
}

// Where appends a list predicates to the DesktopDeviceUpdate builder.
func (_u *DesktopDeviceUpdateOne) Where(ps ...predicate.DesktopDevice) *DesktopDeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DesktopDeviceUpdateOne) Select(field string, fields ...string) *DesktopDeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DesktopDevice entity.
func (_u *DesktopDeviceUpdateOne) Save(ctx context.Context) (*DesktopDevice, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopDeviceUpdateOne) SaveX(ctx context.Context) *DesktopDevice {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DesktopDeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopDeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopDeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktopdevice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DesktopDeviceUpdateOne) check() error {
	if v, ok := _u.mutation.InstallationIDHash(); ok {
		if err := desktopdevice.InstallationIDHashValidator(v); err != nil {
			return &ValidationError{Name: "installation_id_hash", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.installation_id_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := desktopdevice.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := desktopdevice.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Architecture(); ok {
		if err := desktopdevice.ArchitectureValidator(v); err != nil {
			return &ValidationError{Name: "architecture", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.architecture": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OsVersion(); ok {
		if err := desktopdevice.OsVersionValidator(v); err != nil {
			return &ValidationError{Name: "os_version", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.os_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppVersion(); ok {
		if err := desktopdevice.AppVersionValidator(v); err != nil {
			return &ValidationError{Name: "app_version", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.app_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := desktopdevice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReleaseChannel(); ok {
		if err := desktopdevice.ReleaseChannelValidator(v); err != nil {
			return &ValidationError{Name: "release_channel", err: fmt.Errorf(`ent: validator failed for field "DesktopDevice.release_channel": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "DesktopDevice.user"`)
	}
	return nil
}

func (_u *DesktopDeviceUpdateOne) sqlSave(ctx context.Context) (_node *DesktopDevice, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(desktopdevice.Table, desktopdevice.Columns, sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DesktopDevice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktopdevice.FieldID)
		for _, f := range fields {
			if !desktopdevice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != desktopdevice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopdevice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(desktopdevice.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InstallationIDHash(); ok {
		_spec.SetField(desktopdevice.FieldInstallationIDHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(desktopdevice.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(desktopdevice.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Architecture(); ok {
		_spec.SetField(desktopdevice.FieldArchitecture, field.TypeString, value)
	}
	if value, ok := _u.mutation.OsVersion(); ok {
		_spec.SetField(desktopdevice.FieldOsVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppVersion(); ok {
		_spec.SetField(desktopdevice.FieldAppVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktopdevice.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TokenVersion(); ok {
		_spec.SetField(desktopdevice.FieldTokenVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokenVersion(); ok {
		_spec.AddField(desktopdevice.FieldTokenVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReleaseChannel(); ok {
		_spec.SetField(desktopdevice.FieldReleaseChannel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PairingExpiresAt(); ok {
		_spec.SetField(desktopdevice.FieldPairingExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ApprovedAt(); ok {
		_spec.SetField(desktopdevice.FieldApprovedAt, field.TypeTime, value)
	}
	if _u.mutation.ApprovedAtCleared() {
		_spec.ClearField(desktopdevice.FieldApprovedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ActivatedAt(); ok {
		_spec.SetField(desktopdevice.FieldActivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ActivatedAtCleared() {
		_spec.ClearField(desktopdevice.FieldActivatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(desktopdevice.FieldLastSeenAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenAtCleared() {
		_spec.ClearField(desktopdevice.FieldLastSeenAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(desktopdevice.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(desktopdevice.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdevice.UserTable,
			Columns: []string{desktopdevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   desktopdevice.UserTable,
			Columns: []string{desktopdevice.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.SessionsTable,
			Columns: []string{desktopdevice.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevicesession.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSessionsIDs(); len(nodes) > 0 && !_u.mutation.SessionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.SessionsTable,
			Columns: []string{desktopdevice.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevicesession.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.SessionsTable,
			Columns: []string{desktopdevice.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdevicesession.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagedKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.ManagedKeysTable,
			Columns: []string{desktopdevice.ManagedKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedKeysIDs(); len(nodes) > 0 && !_u.mutation.ManagedKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.ManagedKeysTable,
			Columns: []string{desktopdevice.ManagedKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.ManagedKeysTable,
			Columns: []string{desktopdevice.ManagedKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DiagnosticsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.DiagnosticsTable,
			Columns: []string{desktopdevice.DiagnosticsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdiagnostic.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDiagnosticsIDs(); len(nodes) > 0 && !_u.mutation.DiagnosticsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.DiagnosticsTable,
			Columns: []string{desktopdevice.DiagnosticsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdiagnostic.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DiagnosticsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   desktopdevice.DiagnosticsTable,
			Columns: []string{desktopdevice.DiagnosticsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(desktopdiagnostic.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DesktopDevice{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopdevice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
