// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/desktopdevice"
	"github.com/Wei-Shaw/sub2api/ent/desktopdevicesession"
	"github.com/Wei-Shaw/sub2api/ent/desktopdiagnostic"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DesktopDeviceQuery is the builder for querying DesktopDevice entities.
type DesktopDeviceQuery struct {
	config
	ctx             *QueryContext
	order           []desktopdevice.OrderOption
	inters          []Interceptor
	predicates      []predicate.DesktopDevice
	withUser        *UserQuery
	withSessions    *DesktopDeviceSessionQuery
	withManagedKeys *APIKeyQuery
	withDiagnostics *DesktopDiagnosticQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DesktopDeviceQuery builder.
func (_q *DesktopDeviceQuery) Where(ps ...predicate.DesktopDevice) *DesktopDeviceQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DesktopDeviceQuery) Limit(limit int) *DesktopDeviceQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DesktopDeviceQuery) Offset(offset int) *DesktopDeviceQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DesktopDeviceQuery) Unique(unique bool) *DesktopDeviceQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DesktopDeviceQuery) Order(o ...desktopdevice.OrderOption) *DesktopDeviceQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *DesktopDeviceQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(desktopdevice.Table, desktopdevice.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, desktopdevice.UserTable, desktopdevice.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySessions chains the current query on the "sessions" edge.
func (_q *DesktopDeviceQuery) QuerySessions() *DesktopDeviceSessionQuery {
	query := (&DesktopDeviceSessionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(desktopdevice.Table, desktopdevice.FieldID, selector),
			sqlgraph.To(desktopdevicesession.Table, desktopdevicesession.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, desktopdevice.SessionsTable, desktopdevice.SessionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryManagedKeys chains the current query on the "managed_keys" edge.
func (_q *DesktopDeviceQuery) QueryManagedKeys() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(desktopdevice.Table, desktopdevice.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, desktopdevice.ManagedKeysTable, desktopdevice.ManagedKeysColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDiagnostics chains the current query on the "diagnostics" edge.
func (_q *DesktopDeviceQuery) QueryDiagnostics() *DesktopDiagnosticQuery {
	query := (&DesktopDiagnosticClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(desktopdevice.Table, desktopdevice.FieldID, selector),
			sqlgraph.To(desktopdiagnostic.Table, desktopdiagnostic.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, desktopdevice.DiagnosticsTable, desktopdevice.DiagnosticsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DesktopDevice entity from the query.
// Returns a *NotFoundError when no DesktopDevice was found.
func (_q *DesktopDeviceQuery) First(ctx context.Context) (*DesktopDevice, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{desktopdevice.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DesktopDeviceQuery) FirstX(ctx context.Context) *DesktopDevice {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DesktopDevice ID from the query.
// Returns a *NotFoundError when no DesktopDevice ID was found.
func (_q *DesktopDeviceQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{desktopdevice.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DesktopDeviceQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DesktopDevice entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DesktopDevice entity is found.
// Returns a *NotFoundError when no DesktopDevice entities are found.
func (_q *DesktopDeviceQuery) Only(ctx context.Context) (*DesktopDevice, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{desktopdevice.Label}
	default:
		return nil, &NotSingularError{desktopdevice.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DesktopDeviceQuery) OnlyX(ctx context.Context) *DesktopDevice {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DesktopDevice ID in the query.
// Returns a *NotSingularError when more than one DesktopDevice ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DesktopDeviceQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{desktopdevice.Label}
	default:
		err = &NotSingularError{desktopdevice.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DesktopDeviceQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DesktopDevices.
func (_q *DesktopDeviceQuery) All(ctx context.Context) ([]*DesktopDevice, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DesktopDevice, *DesktopDeviceQuery]()
	return withInterceptors[[]*DesktopDevice](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DesktopDeviceQuery) AllX(ctx context.Context) []*DesktopDevice {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DesktopDevice IDs.
func (_q *DesktopDeviceQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(desktopdevice.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DesktopDeviceQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DesktopDeviceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DesktopDeviceQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DesktopDeviceQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DesktopDeviceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DesktopDeviceQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DesktopDeviceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DesktopDeviceQuery) Clone() *DesktopDeviceQuery {
	if _q == nil {
		return nil
	}
	return &DesktopDeviceQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]desktopdevice.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.DesktopDevice{}, _q.predicates...),
		withUser:        _q.withUser.Clone(),
		withSessions:    _q.withSessions.Clone(),
		withManagedKeys: _q.withManagedKeys.Clone(),
		withDiagnostics: _q.withDiagnostics.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DesktopDeviceQuery) WithUser(opts ...func(*UserQuery)) *DesktopDeviceQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithSessions tells the query-builder to eager-load the nodes that are connected to
// the "sessions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DesktopDeviceQuery) WithSessions(opts ...func(*DesktopDeviceSessionQuery)) *DesktopDeviceQuery {
	query := (&DesktopDeviceSessionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSessions = query
	return _q
}

// WithManagedKeys tells the query-builder to eager-load the nodes that are connected to
// the "managed_keys" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DesktopDeviceQuery) WithManagedKeys(opts ...func(*APIKeyQuery)) *DesktopDeviceQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withManagedKeys = query
	return _q
}

// WithDiagnostics tells the query-builder to eager-load the nodes that are connected to
// the "diagnostics" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DesktopDeviceQuery) WithDiagnostics(opts ...func(*DesktopDiagnosticQuery)) *DesktopDeviceQuery {
	query := (&DesktopDiagnosticClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDiagnostics = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DesktopDevice.Query().
//		GroupBy(desktopdevice.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DesktopDeviceQuery) GroupBy(field string, fields ...string) *DesktopDeviceGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DesktopDeviceGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = desktopdevice.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.DesktopDevice.Query().
//		Select(desktopdevice.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *DesktopDeviceQuery) Select(fields ...string) *DesktopDeviceSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DesktopDeviceSelect{DesktopDeviceQuery: _q}
	sbuild.label = desktopdevice.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DesktopDeviceSelect configured with the given aggregations.
func (_q *DesktopDeviceQuery) Aggregate(fns ...AggregateFunc) *DesktopDeviceSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DesktopDeviceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !desktopdevice.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DesktopDeviceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DesktopDevice, error) {
	var (
		nodes       = []*DesktopDevice{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withUser != nil,
			_q.withSessions != nil,
			_q.withManagedKeys != nil,
			_q.withDiagnostics != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DesktopDevice).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DesktopDevice{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *DesktopDevice, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSessions; query != nil {
		if err := _q.loadSessions(ctx, query, nodes,
			func(n *DesktopDevice) { n.Edges.Sessions = []*DesktopDeviceSession{} },
			func(n *DesktopDevice, e *DesktopDeviceSession) { n.Edges.Sessions = append(n.Edges.Sessions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withManagedKeys; query != nil {
		if err := _q.loadManagedKeys(ctx, query, nodes,
			func(n *DesktopDevice) { n.Edges.ManagedKeys = []*APIKey{} },
			func(n *DesktopDevice, e *APIKey) { n.Edges.ManagedKeys = append(n.Edges.ManagedKeys, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDiagnostics; query != nil {
		if err := _q.loadDiagnostics(ctx, query, nodes,
			func(n *DesktopDevice) { n.Edges.Diagnostics = []*DesktopDiagnostic{} },
			func(n *DesktopDevice, e *DesktopDiagnostic) { n.Edges.Diagnostics = append(n.Edges.Diagnostics, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DesktopDeviceQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*DesktopDevice, init func(*DesktopDevice), assign func(*DesktopDevice, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*DesktopDevice)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DesktopDeviceQuery) loadSessions(ctx context.Context, query *DesktopDeviceSessionQuery, nodes []*DesktopDevice, init func(*DesktopDevice), assign func(*DesktopDevice, *DesktopDeviceSession)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*DesktopDevice)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(desktopdevicesession.FieldDeviceID)
	}
	query.Where(predicate.DesktopDeviceSession(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(desktopdevice.SessionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DeviceID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "device_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *DesktopDeviceQuery) loadManagedKeys(ctx context.Context, query *APIKeyQuery, nodes []*DesktopDevice, init func(*DesktopDevice), assign func(*DesktopDevice, *APIKey)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*DesktopDevice)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(apikey.FieldManagedDeviceID)
	}
	query.Where(predicate.APIKey(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(desktopdevice.ManagedKeysColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ManagedDeviceID
		if fk == nil {
			return fmt.Errorf(`foreign-key "managed_device_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "managed_device_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *DesktopDeviceQuery) loadDiagnostics(ctx context.Context, query *DesktopDiagnosticQuery, nodes []*DesktopDevice, init func(*DesktopDevice), assign func(*DesktopDevice, *DesktopDiagnostic)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*DesktopDevice)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(desktopdiagnostic.FieldDeviceID)
	}
	query.Where(predicate.DesktopDiagnostic(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(desktopdevice.DiagnosticsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DeviceID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "device_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DesktopDeviceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DesktopDeviceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(desktopdevice.Table, desktopdevice.Columns, sqlgraph.NewFieldSpec(desktopdevice.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktopdevice.FieldID)
		for i := range fields {
			if fields[i] != desktopdevice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(desktopdevice.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DesktopDeviceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(desktopdevice.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = desktopdevice.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *DesktopDeviceQuery) ForUpdate(opts ...sql.LockOption) *DesktopDeviceQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *DesktopDeviceQuery) ForShare(opts ...sql.LockOption) *DesktopDeviceQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// DesktopDeviceGroupBy is the group-by builder for DesktopDevice entities.
type DesktopDeviceGroupBy struct {
	selector
	build *DesktopDeviceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DesktopDeviceGroupBy) Aggregate(fns ...AggregateFunc) *DesktopDeviceGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DesktopDeviceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DesktopDeviceQuery, *DesktopDeviceGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DesktopDeviceGroupBy) sqlScan(ctx context.Context, root *DesktopDeviceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DesktopDeviceSelect is the builder for selecting fields of DesktopDevice entities.
type DesktopDeviceSelect struct {
	*DesktopDeviceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DesktopDeviceSelect) Aggregate(fns ...AggregateFunc) *DesktopDeviceSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DesktopDeviceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DesktopDeviceQuery, *DesktopDeviceSelect](ctx, _s.DesktopDeviceQuery, _s, _s.inters, v)
}

func (_s *DesktopDeviceSelect) sqlScan(ctx context.Context, root *DesktopDeviceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
