// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalogmodel"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelCatalogModelUpdate is the builder for updating ModelCatalogModel entities.
type ModelCatalogModelUpdate struct {
	config
	hooks    []Hook
	mutation *ModelCatalogModelMutation
}

// Where appends a list predicates to the ModelCatalogModelUpdate builder.
func (_u *ModelCatalogModelUpdate) Where(ps ...predicate.ModelCatalogModel) *ModelCatalogModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSlug sets the "slug" field.
func (_u *ModelCatalogModelUpdate) SetSlug(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableSlug(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ModelCatalogModelUpdate) SetModel(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableModel(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ModelCatalogModelUpdate) SetPlatform(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillablePlatform(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetMetadataModelID sets the "metadata_model_id" field.
func (_u *ModelCatalogModelUpdate) SetMetadataModelID(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetMetadataModelID(v)
	return _u
}

// SetNillableMetadataModelID sets the "metadata_model_id" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableMetadataModelID(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetMetadataModelID(*v)
	}
	return _u
}

// SetDisplayNameZh sets the "display_name_zh" field.
func (_u *ModelCatalogModelUpdate) SetDisplayNameZh(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetDisplayNameZh(v)
	return _u
}

// SetNillableDisplayNameZh sets the "display_name_zh" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableDisplayNameZh(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetDisplayNameZh(*v)
	}
	return _u
}

// SetDisplayNameEn sets the "display_name_en" field.
func (_u *ModelCatalogModelUpdate) SetDisplayNameEn(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetDisplayNameEn(v)
	return _u
}

// SetNillableDisplayNameEn sets the "display_name_en" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableDisplayNameEn(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetDisplayNameEn(*v)
	}
	return _u
}

// SetSummaryZh sets the "summary_zh" field.
func (_u *ModelCatalogModelUpdate) SetSummaryZh(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetSummaryZh(v)
	return _u
}

// SetNillableSummaryZh sets the "summary_zh" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableSummaryZh(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetSummaryZh(*v)
	}
	return _u
}

// SetSummaryEn sets the "summary_en" field.
func (_u *ModelCatalogModelUpdate) SetSummaryEn(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetSummaryEn(v)
	return _u
}

// SetNillableSummaryEn sets the "summary_en" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableSummaryEn(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetSummaryEn(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ModelCatalogModelUpdate) SetProvider(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableProvider(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetLogoKey sets the "logo_key" field.
func (_u *ModelCatalogModelUpdate) SetLogoKey(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetLogoKey(v)
	return _u
}

// SetNillableLogoKey sets the "logo_key" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableLogoKey(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetLogoKey(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ModelCatalogModelUpdate) SetCategory(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableCategory(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *ModelCatalogModelUpdate) SetTags(v []string) *ModelCatalogModelUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ModelCatalogModelUpdate) AppendTags(v []string) *ModelCatalogModelUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *ModelCatalogModelUpdate) SetCapabilities(v []string) *ModelCatalogModelUpdate {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *ModelCatalogModelUpdate) AppendCapabilities(v []string) *ModelCatalogModelUpdate {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// SetContextWindow sets the "context_window" field.
func (_u *ModelCatalogModelUpdate) SetContextWindow(v int64) *ModelCatalogModelUpdate {
	_u.mutation.ResetContextWindow()
	_u.mutation.SetContextWindow(v)
	return _u
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableContextWindow(v *int64) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetContextWindow(*v)
	}
	return _u
}

// AddContextWindow adds value to the "context_window" field.
func (_u *ModelCatalogModelUpdate) AddContextWindow(v int64) *ModelCatalogModelUpdate {
	_u.mutation.AddContextWindow(v)
	return _u
}

// ClearContextWindow clears the value of the "context_window" field.
func (_u *ModelCatalogModelUpdate) ClearContextWindow() *ModelCatalogModelUpdate {
	_u.mutation.ClearContextWindow()
	return _u
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (_u *ModelCatalogModelUpdate) SetMaxOutputTokens(v int64) *ModelCatalogModelUpdate {
	_u.mutation.ResetMaxOutputTokens()
	_u.mutation.SetMaxOutputTokens(v)
	return _u
}

// SetNillableMaxOutputTokens sets the "max_output_tokens" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableMaxOutputTokens(v *int64) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetMaxOutputTokens(*v)
	}
	return _u
}

// AddMaxOutputTokens adds value to the "max_output_tokens" field.
func (_u *ModelCatalogModelUpdate) AddMaxOutputTokens(v int64) *ModelCatalogModelUpdate {
	_u.mutation.AddMaxOutputTokens(v)
	return _u
}

// ClearMaxOutputTokens clears the value of the "max_output_tokens" field.
func (_u *ModelCatalogModelUpdate) ClearMaxOutputTokens() *ModelCatalogModelUpdate {
	_u.mutation.ClearMaxOutputTokens()
	return _u
}

// SetPublicGroupID sets the "public_group_id" field.
func (_u *ModelCatalogModelUpdate) SetPublicGroupID(v int64) *ModelCatalogModelUpdate {
	_u.mutation.ResetPublicGroupID()
	_u.mutation.SetPublicGroupID(v)
	return _u
}

// SetNillablePublicGroupID sets the "public_group_id" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillablePublicGroupID(v *int64) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetPublicGroupID(*v)
	}
	return _u
}

// AddPublicGroupID adds value to the "public_group_id" field.
func (_u *ModelCatalogModelUpdate) AddPublicGroupID(v int64) *ModelCatalogModelUpdate {
	_u.mutation.AddPublicGroupID(v)
	return _u
}

// ClearPublicGroupID clears the value of the "public_group_id" field.
func (_u *ModelCatalogModelUpdate) ClearPublicGroupID() *ModelCatalogModelUpdate {
	_u.mutation.ClearPublicGroupID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelCatalogModelUpdate) SetStatus(v string) *ModelCatalogModelUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableStatus(v *string) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *ModelCatalogModelUpdate) SetFeatured(v bool) *ModelCatalogModelUpdate {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableFeatured(v *bool) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ModelCatalogModelUpdate) SetSortOrder(v int) *ModelCatalogModelUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillableSortOrder(v *int) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ModelCatalogModelUpdate) AddSortOrder(v int) *ModelCatalogModelUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ModelCatalogModelUpdate) SetPublishedAt(v time.Time) *ModelCatalogModelUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ModelCatalogModelUpdate) SetNillablePublishedAt(v *time.Time) *ModelCatalogModelUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *ModelCatalogModelUpdate) ClearPublishedAt() *ModelCatalogModelUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogModelUpdate) SetUpdatedAt(v time.Time) *ModelCatalogModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelCatalogModelMutation object of the builder.
func (_u *ModelCatalogModelUpdate) Mutation() *ModelCatalogModelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelCatalogModelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelCatalogModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogModelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalogmodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogModelUpdate) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := modelcatalogmodel.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := modelcatalogmodel.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := modelcatalogmodel.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetadataModelID(); ok {
		if err := modelcatalogmodel.MetadataModelIDValidator(v); err != nil {
			return &ValidationError{Name: "metadata_model_id", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.metadata_model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayNameZh(); ok {
		if err := modelcatalogmodel.DisplayNameZhValidator(v); err != nil {
			return &ValidationError{Name: "display_name_zh", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.display_name_zh": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayNameEn(); ok {
		if err := modelcatalogmodel.DisplayNameEnValidator(v); err != nil {
			return &ValidationError{Name: "display_name_en", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.display_name_en": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := modelcatalogmodel.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LogoKey(); ok {
		if err := modelcatalogmodel.LogoKeyValidator(v); err != nil {
			return &ValidationError{Name: "logo_key", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.logo_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := modelcatalogmodel.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelcatalogmodel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalogmodel.Table, modelcatalogmodel.Columns, sqlgraph.NewFieldSpec(modelcatalogmodel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(modelcatalogmodel.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(modelcatalogmodel.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(modelcatalogmodel.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataModelID(); ok {
		_spec.SetField(modelcatalogmodel.FieldMetadataModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayNameZh(); ok {
		_spec.SetField(modelcatalogmodel.FieldDisplayNameZh, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayNameEn(); ok {
		_spec.SetField(modelcatalogmodel.FieldDisplayNameEn, field.TypeString, value)
	}
	if value, ok := _u.mutation.SummaryZh(); ok {
		_spec.SetField(modelcatalogmodel.FieldSummaryZh, field.TypeString, value)
	}
	if value, ok := _u.mutation.SummaryEn(); ok {
		_spec.SetField(modelcatalogmodel.FieldSummaryEn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(modelcatalogmodel.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogoKey(); ok {
		_spec.SetField(modelcatalogmodel.FieldLogoKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(modelcatalogmodel.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(modelcatalogmodel.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalogmodel.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(modelcatalogmodel.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalogmodel.FieldCapabilities, value)
		})
	}
	if value, ok := _u.mutation.ContextWindow(); ok {
		_spec.SetField(modelcatalogmodel.FieldContextWindow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedContextWindow(); ok {
		_spec.AddField(modelcatalogmodel.FieldContextWindow, field.TypeInt64, value)
	}
	if _u.mutation.ContextWindowCleared() {
		_spec.ClearField(modelcatalogmodel.FieldContextWindow, field.TypeInt64)
	}
	if value, ok := _u.mutation.MaxOutputTokens(); ok {
		_spec.SetField(modelcatalogmodel.FieldMaxOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaxOutputTokens(); ok {
		_spec.AddField(modelcatalogmodel.FieldMaxOutputTokens, field.TypeInt64, value)
	}
	if _u.mutation.MaxOutputTokensCleared() {
		_spec.ClearField(modelcatalogmodel.FieldMaxOutputTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.PublicGroupID(); ok {
		_spec.SetField(modelcatalogmodel.FieldPublicGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPublicGroupID(); ok {
		_spec.AddField(modelcatalogmodel.FieldPublicGroupID, field.TypeInt64, value)
	}
	if _u.mutation.PublicGroupIDCleared() {
		_spec.ClearField(modelcatalogmodel.FieldPublicGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelcatalogmodel.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(modelcatalogmodel.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(modelcatalogmodel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(modelcatalogmodel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(modelcatalogmodel.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(modelcatalogmodel.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalogmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelCatalogModelUpdateOne is the builder for updating a single ModelCatalogModel entity.
type ModelCatalogModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelCatalogModelMutation
}

// SetSlug sets the "slug" field.
func (_u *ModelCatalogModelUpdateOne) SetSlug(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableSlug(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *ModelCatalogModelUpdateOne) SetModel(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableModel(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ModelCatalogModelUpdateOne) SetPlatform(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillablePlatform(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetMetadataModelID sets the "metadata_model_id" field.
func (_u *ModelCatalogModelUpdateOne) SetMetadataModelID(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetMetadataModelID(v)
	return _u
}

// SetNillableMetadataModelID sets the "metadata_model_id" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableMetadataModelID(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetMetadataModelID(*v)
	}
	return _u
}

// SetDisplayNameZh sets the "display_name_zh" field.
func (_u *ModelCatalogModelUpdateOne) SetDisplayNameZh(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetDisplayNameZh(v)
	return _u
}

// SetNillableDisplayNameZh sets the "display_name_zh" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableDisplayNameZh(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetDisplayNameZh(*v)
	}
	return _u
}

// SetDisplayNameEn sets the "display_name_en" field.
func (_u *ModelCatalogModelUpdateOne) SetDisplayNameEn(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetDisplayNameEn(v)
	return _u
}

// SetNillableDisplayNameEn sets the "display_name_en" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableDisplayNameEn(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetDisplayNameEn(*v)
	}
	return _u
}

// SetSummaryZh sets the "summary_zh" field.
func (_u *ModelCatalogModelUpdateOne) SetSummaryZh(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetSummaryZh(v)
	return _u
}

// SetNillableSummaryZh sets the "summary_zh" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableSummaryZh(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetSummaryZh(*v)
	}
	return _u
}

// SetSummaryEn sets the "summary_en" field.
func (_u *ModelCatalogModelUpdateOne) SetSummaryEn(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetSummaryEn(v)
	return _u
}

// SetNillableSummaryEn sets the "summary_en" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableSummaryEn(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetSummaryEn(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *ModelCatalogModelUpdateOne) SetProvider(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableProvider(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetLogoKey sets the "logo_key" field.
func (_u *ModelCatalogModelUpdateOne) SetLogoKey(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetLogoKey(v)
	return _u
}

// SetNillableLogoKey sets the "logo_key" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableLogoKey(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetLogoKey(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ModelCatalogModelUpdateOne) SetCategory(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableCategory(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *ModelCatalogModelUpdateOne) SetTags(v []string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ModelCatalogModelUpdateOne) AppendTags(v []string) *ModelCatalogModelUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetCapabilities sets the "capabilities" field.
func (_u *ModelCatalogModelUpdateOne) SetCapabilities(v []string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetCapabilities(v)
	return _u
}

// AppendCapabilities appends value to the "capabilities" field.
func (_u *ModelCatalogModelUpdateOne) AppendCapabilities(v []string) *ModelCatalogModelUpdateOne {
	_u.mutation.AppendCapabilities(v)
	return _u
}

// SetContextWindow sets the "context_window" field.
func (_u *ModelCatalogModelUpdateOne) SetContextWindow(v int64) *ModelCatalogModelUpdateOne {
	_u.mutation.ResetContextWindow()
	_u.mutation.SetContextWindow(v)
	return _u
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableContextWindow(v *int64) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetContextWindow(*v)
	}
	return _u
}

// AddContextWindow adds value to the "context_window" field.
func (_u *ModelCatalogModelUpdateOne) AddContextWindow(v int64) *ModelCatalogModelUpdateOne {
	_u.mutation.AddContextWindow(v)
	return _u
}

// ClearContextWindow clears the value of the "context_window" field.
func (_u *ModelCatalogModelUpdateOne) ClearContextWindow() *ModelCatalogModelUpdateOne {
	_u.mutation.ClearContextWindow()
	return _u
}

// SetMaxOutputTokens sets the "max_output_tokens" field.
func (_u *ModelCatalogModelUpdateOne) SetMaxOutputTokens(v int64) *ModelCatalogModelUpdateOne {
	_u.mutation.ResetMaxOutputTokens()
	_u.mutation.SetMaxOutputTokens(v)
	return _u
}

// SetNillableMaxOutputTokens sets the "max_output_tokens" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableMaxOutputTokens(v *int64) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetMaxOutputTokens(*v)
	}
	return _u
}

// AddMaxOutputTokens adds value to the "max_output_tokens" field.
func (_u *ModelCatalogModelUpdateOne) AddMaxOutputTokens(v int64) *ModelCatalogModelUpdateOne {
	_u.mutation.AddMaxOutputTokens(v)
	return _u
}

// ClearMaxOutputTokens clears the value of the "max_output_tokens" field.
func (_u *ModelCatalogModelUpdateOne) ClearMaxOutputTokens() *ModelCatalogModelUpdateOne {
	_u.mutation.ClearMaxOutputTokens()
	return _u
}

// SetPublicGroupID sets the "public_group_id" field.
func (_u *ModelCatalogModelUpdateOne) SetPublicGroupID(v int64) *ModelCatalogModelUpdateOne {
	_u.mutation.ResetPublicGroupID()
	_u.mutation.SetPublicGroupID(v)
	return _u
}

// SetNillablePublicGroupID sets the "public_group_id" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillablePublicGroupID(v *int64) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetPublicGroupID(*v)
	}
	return _u
}

// AddPublicGroupID adds value to the "public_group_id" field.
func (_u *ModelCatalogModelUpdateOne) AddPublicGroupID(v int64) *ModelCatalogModelUpdateOne {
	_u.mutation.AddPublicGroupID(v)
	return _u
}

// ClearPublicGroupID clears the value of the "public_group_id" field.
func (_u *ModelCatalogModelUpdateOne) ClearPublicGroupID() *ModelCatalogModelUpdateOne {
	_u.mutation.ClearPublicGroupID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelCatalogModelUpdateOne) SetStatus(v string) *ModelCatalogModelUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableStatus(v *string) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFeatured sets the "featured" field.
func (_u *ModelCatalogModelUpdateOne) SetFeatured(v bool) *ModelCatalogModelUpdateOne {
	_u.mutation.SetFeatured(v)
	return _u
}

// SetNillableFeatured sets the "featured" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableFeatured(v *bool) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetFeatured(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *ModelCatalogModelUpdateOne) SetSortOrder(v int) *ModelCatalogModelUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillableSortOrder(v *int) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *ModelCatalogModelUpdateOne) AddSortOrder(v int) *ModelCatalogModelUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ModelCatalogModelUpdateOne) SetPublishedAt(v time.Time) *ModelCatalogModelUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ModelCatalogModelUpdateOne) SetNillablePublishedAt(v *time.Time) *ModelCatalogModelUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *ModelCatalogModelUpdateOne) ClearPublishedAt() *ModelCatalogModelUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogModelUpdateOne) SetUpdatedAt(v time.Time) *ModelCatalogModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ModelCatalogModelMutation object of the builder.
func (_u *ModelCatalogModelUpdateOne) Mutation() *ModelCatalogModelMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelCatalogModelUpdate builder.
func (_u *ModelCatalogModelUpdateOne) Where(ps ...predicate.ModelCatalogModel) *ModelCatalogModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelCatalogModelUpdateOne) Select(field string, fields ...string) *ModelCatalogModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelCatalogModel entity.
func (_u *ModelCatalogModelUpdateOne) Save(ctx context.Context) (*ModelCatalogModel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogModelUpdateOne) SaveX(ctx context.Context) *ModelCatalogModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelCatalogModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogModelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalogmodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogModelUpdateOne) check() error {
	if v, ok := _u.mutation.Slug(); ok {
		if err := modelcatalogmodel.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := modelcatalogmodel.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := modelcatalogmodel.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MetadataModelID(); ok {
		if err := modelcatalogmodel.MetadataModelIDValidator(v); err != nil {
			return &ValidationError{Name: "metadata_model_id", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.metadata_model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayNameZh(); ok {
		if err := modelcatalogmodel.DisplayNameZhValidator(v); err != nil {
			return &ValidationError{Name: "display_name_zh", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.display_name_zh": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DisplayNameEn(); ok {
		if err := modelcatalogmodel.DisplayNameEnValidator(v); err != nil {
			return &ValidationError{Name: "display_name_en", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.display_name_en": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := modelcatalogmodel.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LogoKey(); ok {
		if err := modelcatalogmodel.LogoKeyValidator(v); err != nil {
			return &ValidationError{Name: "logo_key", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.logo_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := modelcatalogmodel.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.category": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelcatalogmodel.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelCatalogModel.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogModelUpdateOne) sqlSave(ctx context.Context) (_node *ModelCatalogModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalogmodel.Table, modelcatalogmodel.Columns, sqlgraph.NewFieldSpec(modelcatalogmodel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelCatalogModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelcatalogmodel.FieldID)
		for _, f := range fields {
			if !modelcatalogmodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelcatalogmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(modelcatalogmodel.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(modelcatalogmodel.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(modelcatalogmodel.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.MetadataModelID(); ok {
		_spec.SetField(modelcatalogmodel.FieldMetadataModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayNameZh(); ok {
		_spec.SetField(modelcatalogmodel.FieldDisplayNameZh, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayNameEn(); ok {
		_spec.SetField(modelcatalogmodel.FieldDisplayNameEn, field.TypeString, value)
	}
	if value, ok := _u.mutation.SummaryZh(); ok {
		_spec.SetField(modelcatalogmodel.FieldSummaryZh, field.TypeString, value)
	}
	if value, ok := _u.mutation.SummaryEn(); ok {
		_spec.SetField(modelcatalogmodel.FieldSummaryEn, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(modelcatalogmodel.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.LogoKey(); ok {
		_spec.SetField(modelcatalogmodel.FieldLogoKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(modelcatalogmodel.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(modelcatalogmodel.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalogmodel.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Capabilities(); ok {
		_spec.SetField(modelcatalogmodel.FieldCapabilities, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCapabilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalogmodel.FieldCapabilities, value)
		})
	}
	if value, ok := _u.mutation.ContextWindow(); ok {
		_spec.SetField(modelcatalogmodel.FieldContextWindow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedContextWindow(); ok {
		_spec.AddField(modelcatalogmodel.FieldContextWindow, field.TypeInt64, value)
	}
	if _u.mutation.ContextWindowCleared() {
		_spec.ClearField(modelcatalogmodel.FieldContextWindow, field.TypeInt64)
	}
	if value, ok := _u.mutation.MaxOutputTokens(); ok {
		_spec.SetField(modelcatalogmodel.FieldMaxOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedMaxOutputTokens(); ok {
		_spec.AddField(modelcatalogmodel.FieldMaxOutputTokens, field.TypeInt64, value)
	}
	if _u.mutation.MaxOutputTokensCleared() {
		_spec.ClearField(modelcatalogmodel.FieldMaxOutputTokens, field.TypeInt64)
	}
	if value, ok := _u.mutation.PublicGroupID(); ok {
		_spec.SetField(modelcatalogmodel.FieldPublicGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPublicGroupID(); ok {
		_spec.AddField(modelcatalogmodel.FieldPublicGroupID, field.TypeInt64, value)
	}
	if _u.mutation.PublicGroupIDCleared() {
		_spec.ClearField(modelcatalogmodel.FieldPublicGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelcatalogmodel.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Featured(); ok {
		_spec.SetField(modelcatalogmodel.FieldFeatured, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(modelcatalogmodel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(modelcatalogmodel.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(modelcatalogmodel.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(modelcatalogmodel.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalogmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ModelCatalogModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalogmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
