// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/quotaviewerdevice"
	"github.com/Wei-Shaw/sub2api/ent/quotaviewerdevicesession"
)

// QuotaViewerDeviceSession is the model entity for the QuotaViewerDeviceSession schema.
type QuotaViewerDeviceSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID int64 `json:"device_id,omitempty"`
	// FamilyID holds the value of the "family_id" field.
	FamilyID string `json:"family_id,omitempty"`
	// RefreshTokenHash holds the value of the "refresh_token_hash" field.
	RefreshTokenHash string `json:"refresh_token_hash,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt *time.Time `json:"consumed_at,omitempty"`
	// RotationID holds the value of the "rotation_id" field.
	RotationID *string `json:"rotation_id,omitempty"`
	// ReplacementTokenHash holds the value of the "replacement_token_hash" field.
	ReplacementTokenHash *string `json:"replacement_token_hash,omitempty"`
	// RecoveryExpiresAt holds the value of the "recovery_expires_at" field.
	RecoveryExpiresAt *time.Time `json:"recovery_expires_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QuotaViewerDeviceSessionQuery when eager-loading is set.
	Edges        QuotaViewerDeviceSessionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// QuotaViewerDeviceSessionEdges holds the relations/edges for other nodes in the graph.
type QuotaViewerDeviceSessionEdges struct {
	// Device holds the value of the device edge.
	Device *QuotaViewerDevice `json:"device,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DeviceOrErr returns the Device value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QuotaViewerDeviceSessionEdges) DeviceOrErr() (*QuotaViewerDevice, error) {
	if e.Device != nil {
		return e.Device, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: quotaviewerdevice.Label}
	}
	return nil, &NotLoadedError{edge: "device"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QuotaViewerDeviceSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quotaviewerdevicesession.FieldID, quotaviewerdevicesession.FieldDeviceID:
			values[i] = new(sql.NullInt64)
		case quotaviewerdevicesession.FieldFamilyID, quotaviewerdevicesession.FieldRefreshTokenHash, quotaviewerdevicesession.FieldStatus, quotaviewerdevicesession.FieldRotationID, quotaviewerdevicesession.FieldReplacementTokenHash:
			values[i] = new(sql.NullString)
		case quotaviewerdevicesession.FieldCreatedAt, quotaviewerdevicesession.FieldUpdatedAt, quotaviewerdevicesession.FieldExpiresAt, quotaviewerdevicesession.FieldConsumedAt, quotaviewerdevicesession.FieldRecoveryExpiresAt, quotaviewerdevicesession.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QuotaViewerDeviceSession fields.
func (_m *QuotaViewerDeviceSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quotaviewerdevicesession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case quotaviewerdevicesession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case quotaviewerdevicesession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case quotaviewerdevicesession.FieldDeviceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = value.Int64
			}
		case quotaviewerdevicesession.FieldFamilyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field family_id", values[i])
			} else if value.Valid {
				_m.FamilyID = value.String
			}
		case quotaviewerdevicesession.FieldRefreshTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token_hash", values[i])
			} else if value.Valid {
				_m.RefreshTokenHash = value.String
			}
		case quotaviewerdevicesession.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case quotaviewerdevicesession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case quotaviewerdevicesession.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		case quotaviewerdevicesession.FieldRotationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rotation_id", values[i])
			} else if value.Valid {
				_m.RotationID = new(string)
				*_m.RotationID = value.String
			}
		case quotaviewerdevicesession.FieldReplacementTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field replacement_token_hash", values[i])
			} else if value.Valid {
				_m.ReplacementTokenHash = new(string)
				*_m.ReplacementTokenHash = value.String
			}
		case quotaviewerdevicesession.FieldRecoveryExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recovery_expires_at", values[i])
			} else if value.Valid {
				_m.RecoveryExpiresAt = new(time.Time)
				*_m.RecoveryExpiresAt = value.Time
			}
		case quotaviewerdevicesession.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QuotaViewerDeviceSession.
// This includes values selected through modifiers, order, etc.
func (_m *QuotaViewerDeviceSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDevice queries the "device" edge of the QuotaViewerDeviceSession entity.
func (_m *QuotaViewerDeviceSession) QueryDevice() *QuotaViewerDeviceQuery {
	return NewQuotaViewerDeviceSessionClient(_m.config).QueryDevice(_m)
}

// Update returns a builder for updating this QuotaViewerDeviceSession.
// Note that you need to call QuotaViewerDeviceSession.Unwrap() before calling this method if this QuotaViewerDeviceSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *QuotaViewerDeviceSession) Update() *QuotaViewerDeviceSessionUpdateOne {
	return NewQuotaViewerDeviceSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the QuotaViewerDeviceSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *QuotaViewerDeviceSession) Unwrap() *QuotaViewerDeviceSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: QuotaViewerDeviceSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *QuotaViewerDeviceSession) String() string {
	var builder strings.Builder
	builder.WriteString("QuotaViewerDeviceSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("device_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeviceID))
	builder.WriteString(", ")
	builder.WriteString("family_id=")
	builder.WriteString(_m.FamilyID)
	builder.WriteString(", ")
	builder.WriteString("refresh_token_hash=")
	builder.WriteString(_m.RefreshTokenHash)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RotationID; v != nil {
		builder.WriteString("rotation_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReplacementTokenHash; v != nil {
		builder.WriteString("replacement_token_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RecoveryExpiresAt; v != nil {
		builder.WriteString("recovery_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// QuotaViewerDeviceSessions is a parsable slice of QuotaViewerDeviceSession.
type QuotaViewerDeviceSessions []*QuotaViewerDeviceSession
