// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/quotaviewerdevice"
	"github.com/Wei-Shaw/sub2api/ent/quotaviewerdevicesession"
)

// QuotaViewerDeviceSessionUpdate is the builder for updating QuotaViewerDeviceSession entities.
type QuotaViewerDeviceSessionUpdate struct {
	config
	hooks    []Hook
	mutation *QuotaViewerDeviceSessionMutation
}

// Where appends a list predicates to the QuotaViewerDeviceSessionUpdate builder.
func (_u *QuotaViewerDeviceSessionUpdate) Where(ps ...predicate.QuotaViewerDeviceSession) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaViewerDeviceSessionUpdate) SetUpdatedAt(v time.Time) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *QuotaViewerDeviceSessionUpdate) SetDeviceID(v int64) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdate) SetNillableDeviceID(v *int64) *QuotaViewerDeviceSessionUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetFamilyID sets the "family_id" field.
func (_u *QuotaViewerDeviceSessionUpdate) SetFamilyID(v string) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.SetFamilyID(v)
	return _u
}

// SetNillableFamilyID sets the "family_id" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdate) SetNillableFamilyID(v *string) *QuotaViewerDeviceSessionUpdate {
	if v != nil {
		_u.SetFamilyID(*v)
	}
	return _u
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (_u *QuotaViewerDeviceSessionUpdate) SetRefreshTokenHash(v string) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.SetRefreshTokenHash(v)
	return _u
}

// SetNillableRefreshTokenHash sets the "refresh_token_hash" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdate) SetNillableRefreshTokenHash(v *string) *QuotaViewerDeviceSessionUpdate {
	if v != nil {
		_u.SetRefreshTokenHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaViewerDeviceSessionUpdate) SetStatus(v string) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdate) SetNillableStatus(v *string) *QuotaViewerDeviceSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *QuotaViewerDeviceSessionUpdate) SetExpiresAt(v time.Time) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdate) SetNillableExpiresAt(v *time.Time) *QuotaViewerDeviceSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *QuotaViewerDeviceSessionUpdate) SetConsumedAt(v time.Time) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdate) SetNillableConsumedAt(v *time.Time) *QuotaViewerDeviceSessionUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *QuotaViewerDeviceSessionUpdate) ClearConsumedAt() *QuotaViewerDeviceSessionUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetRotationID sets the "rotation_id" field.
func (_u *QuotaViewerDeviceSessionUpdate) SetRotationID(v string) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.SetRotationID(v)
	return _u
}

// SetNillableRotationID sets the "rotation_id" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdate) SetNillableRotationID(v *string) *QuotaViewerDeviceSessionUpdate {
	if v != nil {
		_u.SetRotationID(*v)
	}
	return _u
}

// ClearRotationID clears the value of the "rotation_id" field.
func (_u *QuotaViewerDeviceSessionUpdate) ClearRotationID() *QuotaViewerDeviceSessionUpdate {
	_u.mutation.ClearRotationID()
	return _u
}

// SetReplacementTokenHash sets the "replacement_token_hash" field.
func (_u *QuotaViewerDeviceSessionUpdate) SetReplacementTokenHash(v string) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.SetReplacementTokenHash(v)
	return _u
}

// SetNillableReplacementTokenHash sets the "replacement_token_hash" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdate) SetNillableReplacementTokenHash(v *string) *QuotaViewerDeviceSessionUpdate {
	if v != nil {
		_u.SetReplacementTokenHash(*v)
	}
	return _u
}

// ClearReplacementTokenHash clears the value of the "replacement_token_hash" field.
func (_u *QuotaViewerDeviceSessionUpdate) ClearReplacementTokenHash() *QuotaViewerDeviceSessionUpdate {
	_u.mutation.ClearReplacementTokenHash()
	return _u
}

// SetRecoveryExpiresAt sets the "recovery_expires_at" field.
func (_u *QuotaViewerDeviceSessionUpdate) SetRecoveryExpiresAt(v time.Time) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.SetRecoveryExpiresAt(v)
	return _u
}

// SetNillableRecoveryExpiresAt sets the "recovery_expires_at" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdate) SetNillableRecoveryExpiresAt(v *time.Time) *QuotaViewerDeviceSessionUpdate {
	if v != nil {
		_u.SetRecoveryExpiresAt(*v)
	}
	return _u
}

// ClearRecoveryExpiresAt clears the value of the "recovery_expires_at" field.
func (_u *QuotaViewerDeviceSessionUpdate) ClearRecoveryExpiresAt() *QuotaViewerDeviceSessionUpdate {
	_u.mutation.ClearRecoveryExpiresAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *QuotaViewerDeviceSessionUpdate) SetRevokedAt(v time.Time) *QuotaViewerDeviceSessionUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdate) SetNillableRevokedAt(v *time.Time) *QuotaViewerDeviceSessionUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *QuotaViewerDeviceSessionUpdate) ClearRevokedAt() *QuotaViewerDeviceSessionUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetDevice sets the "device" edge to the QuotaViewerDevice entity.
func (_u *QuotaViewerDeviceSessionUpdate) SetDevice(v *QuotaViewerDevice) *QuotaViewerDeviceSessionUpdate {
	return _u.SetDeviceID(v.ID)
}

// Mutation returns the QuotaViewerDeviceSessionMutation object of the builder.
func (_u *QuotaViewerDeviceSessionUpdate) Mutation() *QuotaViewerDeviceSessionMutation {
	return _u.mutation
}

// ClearDevice clears the "device" edge to the QuotaViewerDevice entity.
func (_u *QuotaViewerDeviceSessionUpdate) ClearDevice() *QuotaViewerDeviceSessionUpdate {
	_u.mutation.ClearDevice()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuotaViewerDeviceSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaViewerDeviceSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuotaViewerDeviceSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaViewerDeviceSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaViewerDeviceSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotaviewerdevicesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaViewerDeviceSessionUpdate) check() error {
	if v, ok := _u.mutation.RefreshTokenHash(); ok {
		if err := quotaviewerdevicesession.RefreshTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token_hash", err: fmt.Errorf(`ent: validator failed for field "QuotaViewerDeviceSession.refresh_token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotaviewerdevicesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaViewerDeviceSession.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReplacementTokenHash(); ok {
		if err := quotaviewerdevicesession.ReplacementTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "replacement_token_hash", err: fmt.Errorf(`ent: validator failed for field "QuotaViewerDeviceSession.replacement_token_hash": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuotaViewerDeviceSession.device"`)
	}
	return nil
}

func (_u *QuotaViewerDeviceSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotaviewerdevicesession.Table, quotaviewerdevicesession.Columns, sqlgraph.NewFieldSpec(quotaviewerdevicesession.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FamilyID(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldFamilyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshTokenHash(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldRefreshTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(quotaviewerdevicesession.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RotationID(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldRotationID, field.TypeString, value)
	}
	if _u.mutation.RotationIDCleared() {
		_spec.ClearField(quotaviewerdevicesession.FieldRotationID, field.TypeString)
	}
	if value, ok := _u.mutation.ReplacementTokenHash(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldReplacementTokenHash, field.TypeString, value)
	}
	if _u.mutation.ReplacementTokenHashCleared() {
		_spec.ClearField(quotaviewerdevicesession.FieldReplacementTokenHash, field.TypeString)
	}
	if value, ok := _u.mutation.RecoveryExpiresAt(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldRecoveryExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.RecoveryExpiresAtCleared() {
		_spec.ClearField(quotaviewerdevicesession.FieldRecoveryExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(quotaviewerdevicesession.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quotaviewerdevicesession.DeviceTable,
			Columns: []string{quotaviewerdevicesession.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quotaviewerdevice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quotaviewerdevicesession.DeviceTable,
			Columns: []string{quotaviewerdevicesession.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quotaviewerdevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotaviewerdevicesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuotaViewerDeviceSessionUpdateOne is the builder for updating a single QuotaViewerDeviceSession entity.
type QuotaViewerDeviceSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuotaViewerDeviceSessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetUpdatedAt(v time.Time) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetDeviceID(v int64) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetNillableDeviceID(v *int64) *QuotaViewerDeviceSessionUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetFamilyID sets the "family_id" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetFamilyID(v string) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.SetFamilyID(v)
	return _u
}

// SetNillableFamilyID sets the "family_id" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetNillableFamilyID(v *string) *QuotaViewerDeviceSessionUpdateOne {
	if v != nil {
		_u.SetFamilyID(*v)
	}
	return _u
}

// SetRefreshTokenHash sets the "refresh_token_hash" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetRefreshTokenHash(v string) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.SetRefreshTokenHash(v)
	return _u
}

// SetNillableRefreshTokenHash sets the "refresh_token_hash" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetNillableRefreshTokenHash(v *string) *QuotaViewerDeviceSessionUpdateOne {
	if v != nil {
		_u.SetRefreshTokenHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetStatus(v string) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetNillableStatus(v *string) *QuotaViewerDeviceSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetExpiresAt(v time.Time) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *QuotaViewerDeviceSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetConsumedAt(v time.Time) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetNillableConsumedAt(v *time.Time) *QuotaViewerDeviceSessionUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) ClearConsumedAt() *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// SetRotationID sets the "rotation_id" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetRotationID(v string) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.SetRotationID(v)
	return _u
}

// SetNillableRotationID sets the "rotation_id" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetNillableRotationID(v *string) *QuotaViewerDeviceSessionUpdateOne {
	if v != nil {
		_u.SetRotationID(*v)
	}
	return _u
}

// ClearRotationID clears the value of the "rotation_id" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) ClearRotationID() *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.ClearRotationID()
	return _u
}

// SetReplacementTokenHash sets the "replacement_token_hash" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetReplacementTokenHash(v string) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.SetReplacementTokenHash(v)
	return _u
}

// SetNillableReplacementTokenHash sets the "replacement_token_hash" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetNillableReplacementTokenHash(v *string) *QuotaViewerDeviceSessionUpdateOne {
	if v != nil {
		_u.SetReplacementTokenHash(*v)
	}
	return _u
}

// ClearReplacementTokenHash clears the value of the "replacement_token_hash" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) ClearReplacementTokenHash() *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.ClearReplacementTokenHash()
	return _u
}

// SetRecoveryExpiresAt sets the "recovery_expires_at" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetRecoveryExpiresAt(v time.Time) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.SetRecoveryExpiresAt(v)
	return _u
}

// SetNillableRecoveryExpiresAt sets the "recovery_expires_at" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetNillableRecoveryExpiresAt(v *time.Time) *QuotaViewerDeviceSessionUpdateOne {
	if v != nil {
		_u.SetRecoveryExpiresAt(*v)
	}
	return _u
}

// ClearRecoveryExpiresAt clears the value of the "recovery_expires_at" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) ClearRecoveryExpiresAt() *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.ClearRecoveryExpiresAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetRevokedAt(v time.Time) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetNillableRevokedAt(v *time.Time) *QuotaViewerDeviceSessionUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *QuotaViewerDeviceSessionUpdateOne) ClearRevokedAt() *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetDevice sets the "device" edge to the QuotaViewerDevice entity.
func (_u *QuotaViewerDeviceSessionUpdateOne) SetDevice(v *QuotaViewerDevice) *QuotaViewerDeviceSessionUpdateOne {
	return _u.SetDeviceID(v.ID)
}

// Mutation returns the QuotaViewerDeviceSessionMutation object of the builder.
func (_u *QuotaViewerDeviceSessionUpdateOne) Mutation() *QuotaViewerDeviceSessionMutation {
	return _u.mutation
}

// ClearDevice clears the "device" edge to the QuotaViewerDevice entity.
func (_u *QuotaViewerDeviceSessionUpdateOne) ClearDevice() *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.ClearDevice()
	return _u
}

// Where appends a list predicates to the QuotaViewerDeviceSessionUpdate builder.
func (_u *QuotaViewerDeviceSessionUpdateOne) Where(ps ...predicate.QuotaViewerDeviceSession) *QuotaViewerDeviceSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuotaViewerDeviceSessionUpdateOne) Select(field string, fields ...string) *QuotaViewerDeviceSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QuotaViewerDeviceSession entity.
func (_u *QuotaViewerDeviceSessionUpdateOne) Save(ctx context.Context) (*QuotaViewerDeviceSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuotaViewerDeviceSessionUpdateOne) SaveX(ctx context.Context) *QuotaViewerDeviceSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuotaViewerDeviceSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuotaViewerDeviceSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QuotaViewerDeviceSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := quotaviewerdevicesession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuotaViewerDeviceSessionUpdateOne) check() error {
	if v, ok := _u.mutation.RefreshTokenHash(); ok {
		if err := quotaviewerdevicesession.RefreshTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token_hash", err: fmt.Errorf(`ent: validator failed for field "QuotaViewerDeviceSession.refresh_token_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := quotaviewerdevicesession.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QuotaViewerDeviceSession.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReplacementTokenHash(); ok {
		if err := quotaviewerdevicesession.ReplacementTokenHashValidator(v); err != nil {
			return &ValidationError{Name: "replacement_token_hash", err: fmt.Errorf(`ent: validator failed for field "QuotaViewerDeviceSession.replacement_token_hash": %w`, err)}
		}
	}
	if _u.mutation.DeviceCleared() && len(_u.mutation.DeviceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "QuotaViewerDeviceSession.device"`)
	}
	return nil
}

func (_u *QuotaViewerDeviceSessionUpdateOne) sqlSave(ctx context.Context) (_node *QuotaViewerDeviceSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quotaviewerdevicesession.Table, quotaviewerdevicesession.Columns, sqlgraph.NewFieldSpec(quotaviewerdevicesession.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QuotaViewerDeviceSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quotaviewerdevicesession.FieldID)
		for _, f := range fields {
			if !quotaviewerdevicesession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quotaviewerdevicesession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FamilyID(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldFamilyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshTokenHash(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldRefreshTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(quotaviewerdevicesession.FieldConsumedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RotationID(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldRotationID, field.TypeString, value)
	}
	if _u.mutation.RotationIDCleared() {
		_spec.ClearField(quotaviewerdevicesession.FieldRotationID, field.TypeString)
	}
	if value, ok := _u.mutation.ReplacementTokenHash(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldReplacementTokenHash, field.TypeString, value)
	}
	if _u.mutation.ReplacementTokenHashCleared() {
		_spec.ClearField(quotaviewerdevicesession.FieldReplacementTokenHash, field.TypeString)
	}
	if value, ok := _u.mutation.RecoveryExpiresAt(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldRecoveryExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.RecoveryExpiresAtCleared() {
		_spec.ClearField(quotaviewerdevicesession.FieldRecoveryExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(quotaviewerdevicesession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(quotaviewerdevicesession.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.DeviceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quotaviewerdevicesession.DeviceTable,
			Columns: []string{quotaviewerdevicesession.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quotaviewerdevice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeviceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quotaviewerdevicesession.DeviceTable,
			Columns: []string{quotaviewerdevicesession.DeviceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quotaviewerdevice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &QuotaViewerDeviceSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quotaviewerdevicesession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
