// Code generated by ent, DO NOT EDIT.

package desktopdiagnostic

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the desktopdiagnostic type in the database.
	Label = "desktop_diagnostic"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeviceID holds the string denoting the device_id field in the database.
	FieldDeviceID = "device_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPublicID holds the string denoting the public_id field in the database.
	FieldPublicID = "public_id"
	// FieldAppVersion holds the string denoting the app_version field in the database.
	FieldAppVersion = "app_version"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldArchitecture holds the string denoting the architecture field in the database.
	FieldArchitecture = "architecture"
	// FieldOsVersion holds the string denoting the os_version field in the database.
	FieldOsVersion = "os_version"
	// FieldGatewayStatus holds the string denoting the gateway_status field in the database.
	FieldGatewayStatus = "gateway_status"
	// FieldCodexConfigStatus holds the string denoting the codex_config_status field in the database.
	FieldCodexConfigStatus = "codex_config_status"
	// FieldRequestSampleCount holds the string denoting the request_sample_count field in the database.
	FieldRequestSampleCount = "request_sample_count"
	// FieldRequestErrorCount holds the string denoting the request_error_count field in the database.
	FieldRequestErrorCount = "request_error_count"
	// FieldEncryptedPayload holds the string denoting the encrypted_payload field in the database.
	FieldEncryptedPayload = "encrypted_payload"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeDevice holds the string denoting the device edge name in mutations.
	EdgeDevice = "device"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the desktopdiagnostic in the database.
	Table = "desktop_diagnostics"
	// DeviceTable is the table that holds the device relation/edge.
	DeviceTable = "desktop_diagnostics"
	// DeviceInverseTable is the table name for the DesktopDevice entity.
	// It exists in this package in order to avoid circular dependency with the "desktopdevice" package.
	DeviceInverseTable = "desktop_devices"
	// DeviceColumn is the table column denoting the device relation/edge.
	DeviceColumn = "device_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "desktop_diagnostics"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for desktopdiagnostic fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeviceID,
	FieldUserID,
	FieldPublicID,
	FieldAppVersion,
	FieldPlatform,
	FieldArchitecture,
	FieldOsVersion,
	FieldGatewayStatus,
	FieldCodexConfigStatus,
	FieldRequestSampleCount,
	FieldRequestErrorCount,
	FieldEncryptedPayload,
	FieldExpiresAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// AppVersionValidator is a validator for the "app_version" field. It is called by the builders before save.
	AppVersionValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// ArchitectureValidator is a validator for the "architecture" field. It is called by the builders before save.
	ArchitectureValidator func(string) error
	// OsVersionValidator is a validator for the "os_version" field. It is called by the builders before save.
	OsVersionValidator func(string) error
	// GatewayStatusValidator is a validator for the "gateway_status" field. It is called by the builders before save.
	GatewayStatusValidator func(string) error
	// CodexConfigStatusValidator is a validator for the "codex_config_status" field. It is called by the builders before save.
	CodexConfigStatusValidator func(string) error
	// DefaultRequestSampleCount holds the default value on creation for the "request_sample_count" field.
	DefaultRequestSampleCount int
	// DefaultRequestErrorCount holds the default value on creation for the "request_error_count" field.
	DefaultRequestErrorCount int
)

// OrderOption defines the ordering options for the DesktopDiagnostic queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeviceID orders the results by the device_id field.
func ByDeviceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeviceID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPublicID orders the results by the public_id field.
func ByPublicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicID, opts...).ToFunc()
}

// ByAppVersion orders the results by the app_version field.
func ByAppVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppVersion, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByArchitecture orders the results by the architecture field.
func ByArchitecture(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArchitecture, opts...).ToFunc()
}

// ByOsVersion orders the results by the os_version field.
func ByOsVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOsVersion, opts...).ToFunc()
}

// ByGatewayStatus orders the results by the gateway_status field.
func ByGatewayStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGatewayStatus, opts...).ToFunc()
}

// ByCodexConfigStatus orders the results by the codex_config_status field.
func ByCodexConfigStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCodexConfigStatus, opts...).ToFunc()
}

// ByRequestSampleCount orders the results by the request_sample_count field.
func ByRequestSampleCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestSampleCount, opts...).ToFunc()
}

// ByRequestErrorCount orders the results by the request_error_count field.
func ByRequestErrorCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestErrorCount, opts...).ToFunc()
}

// ByEncryptedPayload orders the results by the encrypted_payload field.
func ByEncryptedPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEncryptedPayload, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByDeviceField orders the results by device field.
func ByDeviceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeviceStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newDeviceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeviceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DeviceTable, DeviceColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
