// Code generated by ent, DO NOT EDIT.

package modelcatalogmodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modelcatalogmodel type in the database.
	Label = "model_catalog_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldMetadataModelID holds the string denoting the metadata_model_id field in the database.
	FieldMetadataModelID = "metadata_model_id"
	// FieldDisplayNameZh holds the string denoting the display_name_zh field in the database.
	FieldDisplayNameZh = "display_name_zh"
	// FieldDisplayNameEn holds the string denoting the display_name_en field in the database.
	FieldDisplayNameEn = "display_name_en"
	// FieldSummaryZh holds the string denoting the summary_zh field in the database.
	FieldSummaryZh = "summary_zh"
	// FieldSummaryEn holds the string denoting the summary_en field in the database.
	FieldSummaryEn = "summary_en"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldLogoKey holds the string denoting the logo_key field in the database.
	FieldLogoKey = "logo_key"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldCapabilities holds the string denoting the capabilities field in the database.
	FieldCapabilities = "capabilities"
	// FieldContextWindow holds the string denoting the context_window field in the database.
	FieldContextWindow = "context_window"
	// FieldMaxOutputTokens holds the string denoting the max_output_tokens field in the database.
	FieldMaxOutputTokens = "max_output_tokens"
	// FieldPublicGroupID holds the string denoting the public_group_id field in the database.
	FieldPublicGroupID = "public_group_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFeatured holds the string denoting the featured field in the database.
	FieldFeatured = "featured"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the modelcatalogmodel in the database.
	Table = "model_catalog_models"
)

// Columns holds all SQL columns for modelcatalogmodel fields.
var Columns = []string{
	FieldID,
	FieldSlug,
	FieldModel,
	FieldPlatform,
	FieldMetadataModelID,
	FieldDisplayNameZh,
	FieldDisplayNameEn,
	FieldSummaryZh,
	FieldSummaryEn,
	FieldProvider,
	FieldLogoKey,
	FieldCategory,
	FieldTags,
	FieldCapabilities,
	FieldContextWindow,
	FieldMaxOutputTokens,
	FieldPublicGroupID,
	FieldStatus,
	FieldFeatured,
	FieldSortOrder,
	FieldPublishedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultMetadataModelID holds the default value on creation for the "metadata_model_id" field.
	DefaultMetadataModelID string
	// MetadataModelIDValidator is a validator for the "metadata_model_id" field. It is called by the builders before save.
	MetadataModelIDValidator func(string) error
	// DefaultDisplayNameZh holds the default value on creation for the "display_name_zh" field.
	DefaultDisplayNameZh string
	// DisplayNameZhValidator is a validator for the "display_name_zh" field. It is called by the builders before save.
	DisplayNameZhValidator func(string) error
	// DefaultDisplayNameEn holds the default value on creation for the "display_name_en" field.
	DefaultDisplayNameEn string
	// DisplayNameEnValidator is a validator for the "display_name_en" field. It is called by the builders before save.
	DisplayNameEnValidator func(string) error
	// DefaultSummaryZh holds the default value on creation for the "summary_zh" field.
	DefaultSummaryZh string
	// DefaultSummaryEn holds the default value on creation for the "summary_en" field.
	DefaultSummaryEn string
	// DefaultProvider holds the default value on creation for the "provider" field.
	DefaultProvider string
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// DefaultLogoKey holds the default value on creation for the "logo_key" field.
	DefaultLogoKey string
	// LogoKeyValidator is a validator for the "logo_key" field. It is called by the builders before save.
	LogoKeyValidator func(string) error
	// DefaultCategory holds the default value on creation for the "category" field.
	DefaultCategory string
	// CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	CategoryValidator func(string) error
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultCapabilities holds the default value on creation for the "capabilities" field.
	DefaultCapabilities []string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultFeatured holds the default value on creation for the "featured" field.
	DefaultFeatured bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ModelCatalogModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByMetadataModelID orders the results by the metadata_model_id field.
func ByMetadataModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetadataModelID, opts...).ToFunc()
}

// ByDisplayNameZh orders the results by the display_name_zh field.
func ByDisplayNameZh(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayNameZh, opts...).ToFunc()
}

// ByDisplayNameEn orders the results by the display_name_en field.
func ByDisplayNameEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayNameEn, opts...).ToFunc()
}

// BySummaryZh orders the results by the summary_zh field.
func BySummaryZh(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummaryZh, opts...).ToFunc()
}

// BySummaryEn orders the results by the summary_en field.
func BySummaryEn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummaryEn, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByLogoKey orders the results by the logo_key field.
func ByLogoKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogoKey, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByContextWindow orders the results by the context_window field.
func ByContextWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextWindow, opts...).ToFunc()
}

// ByMaxOutputTokens orders the results by the max_output_tokens field.
func ByMaxOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxOutputTokens, opts...).ToFunc()
}

// ByPublicGroupID orders the results by the public_group_id field.
func ByPublicGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicGroupID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFeatured orders the results by the featured field.
func ByFeatured(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatured, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
